import test from 'node:test';
import assert from 'node:assert/strict';
import {initialState,execute,DomainError,DAY,citizenView} from '../src/domain.ts';
import type {State} from '../src/domain.ts';
import {graduate,completeCourse} from './helpers.ts';
import {reconcile,exportBackup,restoreBackup} from '../src/recovery.ts';
let seq=0;const start=10*DAY,now=start+8*DAY,doctor='clinical-doctor',patient='clinical-patient',other='clinical-other';
const cmd=(type:string,payload:Record<string,unknown>={})=>({id:'healthcare_test_'+ ++seq,type,payload});
const run=(s:State,a:string,type:string,payload:Record<string,unknown>={},at=now)=>execute(s,a,cmd(type,payload),at);
const code=(value:string)=>(e:unknown)=>e instanceof DomainError&&e.code===value;
function setup(){let s=initialState();for(const actor of [doctor,patient,other])s=run(s,actor,'CreateCitizen',{name:actor,state:'Lagos',adultConfirmed:true},start).state;s=graduate(s,doctor,start);s=completeCourse(s,doctor,'secondary',start+5*DAY);s=completeCourse(s,doctor,'business',start+6*DAY);s=completeCourse(s,doctor,'medicine',start+7*DAY);const company=run(s,doctor,'RegisterCompany',{name:'Care House',sector:'healthcare',capital:200000});s=company.state;const companyId=String(company.receipt.detail.companyId),hospital=run(s,doctor,'RegisterHospital',{companyId});return{state:hospital.state,companyId,hospitalId:String(hospital.receipt.detail.hospitalId)};}
function intake(s:State,providerId='npc'){const result=run(s,patient,'RequestAssessment',{providerId,consent:true,acceptedConsultation:providerId==='npc'?0:5000});return{state:result.state,caseId:String(result.receipt.detail.caseId)};}
test('clinical assessment needs scoped consent and current professional permission, and unused funds refund after closure',()=>{
 let {state:s,hospitalId}=setup();assert.throws(()=>run(s,patient,'RequestAssessment',{providerId:hospitalId,acceptedConsultation:5000}),code('CARE_CONSENT'));const cash=s.balances['citizen:'+patient],episode=intake(s,hospitalId);s=episode.state;assert.throws(()=>run(s,other,'AssessPatient',{caseId:episode.caseId,choice:0},now+2000),code('CARE_PERMISSION'));assert.throws(()=>run(s,patient,'AssessPatient',{caseId:episode.caseId,choice:0},now+2000),code('CLINICAL_PERMISSION'));assert.equal(citizenView(s,other,now).healthcare!.cases.length,0);
 s=run(s,patient,'BlockCitizen',{citizenId:s.citizens[doctor].id}).state;assert.equal(citizenView(s,doctor,now).healthcare!.cases.length,0);assert.throws(()=>run(s,doctor,'AssessPatient',{caseId:episode.caseId,choice:0},now+2000),code('CARE_PERMISSION'));s=run(s,doctor,'CloseHospital',{hospitalId}).state;s=run(s,patient,'TransferCareToNPC',{caseId:episode.caseId}).state;assert.equal(s.balances['citizen:'+patient],cash);assert.equal(s.balances['consultation:'+episode.caseId],0);s=run(s,patient,'AssessPatient',{caseId:episode.caseId,choice:0},now+2000).state;assert.equal(s.healthcare!.cases[episode.caseId].status,'assessed');reconcile(s);
});
test('private treatment consumes hospital medicine and power, reserves fees and recovers once through provider absence',()=>{
 let {state:s,companyId,hospitalId}=setup();for(const [goodsId,quantity,acceptedUnitPrice] of [['medicine',2,2500],['energy',3,200]] as const)s=run(s,doctor,'BuyNPCSupply',{companyId,goodsId,quantity,acceptedUnitPrice}).state;
 const episode=intake(s,hospitalId);s=run(episode.state,doctor,'AssessPatient',{caseId:episode.caseId,choice:0},now+2000).state;const initialCash=s.balances['company:'+companyId];s=run(s,patient,'AcceptTreatment',{caseId:episode.caseId,acceptedFee:10000,acceptTerms:true},now+2001).state;assert.equal(s.balances['company:'+companyId],initialCash);assert.throws(()=>run(s,patient,'TreatPatient',{caseId:episode.caseId,choice:0},now+2002),code('CLINICAL_PERMISSION'));
 s=run(s,doctor,'TreatPatient',{caseId:episode.caseId,choice:0},now+2002).state;assert.equal(Object.values(s.commerce!.batches).find(b=>b.goods==='medicine')!.quantity,0);assert.throws(()=>run(s,patient,'CompleteRecovery',{caseId:episode.caseId},now+3000),code('RECOVERY_PENDING'));s=run(s,doctor,'CloseHospital',{hospitalId},now+4000).state;s=restoreBackup(exportBackup(s));const completed=cmd('CompleteRecovery',{caseId:episode.caseId});s=execute(s,patient,completed,now+62002).state;assert.equal(execute(s,patient,completed,now+63000).replayed,true);assert.equal(s.balances['company:'+companyId],initialCash+10000);assert.equal(s.balances['treatment:'+episode.caseId],0);assert.equal(s.healthcare!.cases[episode.caseId].status,'completed');reconcile(s);
});
test('insufficient real clinical supplies roll back the entire procedure and NPC transfer returns unearned payment',()=>{
 let {state:s,companyId,hospitalId}=setup();s=run(s,doctor,'BuyNPCSupply',{companyId,goodsId:'energy',quantity:1,acceptedUnitPrice:200}).state;const episode=intake(s,hospitalId);s=run(episode.state,doctor,'AssessPatient',{caseId:episode.caseId,choice:0},now+2000).state;s=run(s,patient,'AcceptTreatment',{caseId:episode.caseId,acceptedFee:10000,acceptTerms:true},now+2001).state;const before=JSON.stringify(s);assert.throws(()=>run(s,doctor,'TreatPatient',{caseId:episode.caseId,choice:0},now+2002),code('INPUTS_REQUIRED'));assert.equal(JSON.stringify(s),before);
 const cash=s.balances['citizen:'+patient];s=run(s,patient,'TransferCareToNPC',{caseId:episode.caseId},now+3000).state;assert.equal(s.balances['citizen:'+patient],cash+10000);assert.equal(s.healthcare!.cases[episode.caseId].condition,'routine');reconcile(s);
});
test('NPC clinical care uses capped supplies and emergency transport needs real assessment and one lease',()=>{
 let s=initialState();s=run(s,patient,'CreateCitizen',{name:'Care patient',state:'Lagos',adultConfirmed:true},start).state;assert.throws(()=>run(s,patient,'RequestEmergencyTransport',{caseId:'invented'}),code('CARE_PERMISSION'));
 // Isolated server incident fixture; a client cannot supply health or assessment severity.
 s.citizens[patient].life!.needs.health=60;const episode=intake(s);s=run(episode.state,patient,'AssessPatient',{caseId:episode.caseId,choice:0},now+2000).state;assert.equal(s.healthcare!.cases[episode.caseId].condition,'urgent');s=run(s,patient,'RequestEmergencyTransport',{caseId:episode.caseId},now+2001).state;assert.throws(()=>run(s,patient,'MoveCitizen',{dx:1,dy:0},now+3000),code('IN_TRANSIT'));assert.throws(()=>run(s,patient,'AcceptTreatment',{caseId:episode.caseId,acceptedFee:2500,acceptTerms:true},now+3000),code('CARE_CONSENT'));
 const trip=s.world!.trips[s.world!.activeTrips[patient]],arrival=cmd('ArriveTravel');s=execute(s,patient,arrival,trip.arriveAt).state;assert.equal(s.world!.positions[patient].interior,'clinic');assert.equal(execute(s,patient,arrival,trip.arriveAt+1).replayed,true);
 s=run(s,patient,'AcceptTreatment',{caseId:episode.caseId,acceptedFee:2500,acceptTerms:true},trip.arriveAt+1).state;s=run(s,patient,'TreatPatient',{caseId:episode.caseId,choice:0},trip.arriveAt+2).state;s=run(s,patient,'CompleteRecovery',{caseId:episode.caseId},trip.arriveAt+60002).state;assert.equal(s.healthcare!.cases[episode.caseId].status,'completed');assert.equal(Object.values(s.healthcare!.npcUse)[0],2);assert.equal(s.commerce!.stock!.balances['medicine:system:medical-treatment-consumed'],2);reconcile(s);
});
