import test from 'node:test';
import assert from 'node:assert/strict';
import {initialState,execute,DomainError,DAY,citizenView} from '../src/domain.ts';
import type {State} from '../src/domain.ts';
import {graduate,completeCourse} from './helpers.ts';
import {INSURANCE_RULES} from '../src/insurance.ts';
import {INCIDENT_START,homeExposureSetup,exposeHome} from './incident-helpers.ts';
import {reconcile,exportBackup,restoreBackup} from '../src/recovery.ts';
let sequence=0;const actor='insured-person',other='insurer-manager',start=INCIDENT_START,now=start+45*DAY;
const cmd=(type:string,payload:Record<string,unknown>={})=>({id:'insurance_test_'+ ++sequence,type,payload});
const run=(s:State,a:string,type:string,payload:Record<string,unknown>={},at=now)=>execute(s,a,cmd(type,payload),at);
const code=(value:string)=>(e:unknown)=>e instanceof DomainError&&e.code===value;
function setup(){let s=initialState();for(const a of [actor,other])s=run(s,a,'CreateCitizen',{name:a,state:'Lagos',adultConfirmed:true},start).state;return s;}
function buy(s:State,providerId='npc',coverage='property',assetId='npc-Lagos-home',a=actor,at=now){return run(s,a,'BuyInsurance',{providerId,coverage,...(coverage!=='health'?{assetId}:{}),acceptedPremium:5000,acceptedLimit:50000,acceptedExcess:5000,acceptTerms:true},at);}
function licensedInsurer(s:State){s=graduate(s,other,start+35*DAY);for(const [i,course] of ['secondary','business','finance','insurance'].entries())s=completeCourse(s,other,course,start+(40+i)*DAY);const company=run(s,other,'RegisterCompany',{name:'Funded Assurance',sector:'finance',capital:500000});s=company.state;const registered=run(s,other,'RegisterInsurer',{companyId:company.receipt.detail.companyId});return{state:registered.state,providerId:String(registered.receipt.detail.insurerId)};}
test('actual insured repair expense reserves a capped payout and pays once after recovery',()=>{
 let s=homeExposureSetup(setup(),actor);const insurer=licensedInsurer(s);s=insurer.state;const policy=buy(s,insurer.providerId);s=policy.state;const policyId=String(policy.receipt.detail.policyId),before=s.balances['citizen:'+actor];s=exposeHome(s,actor,start+47*DAY).state;const incident=Object.values(s.incidents!.records)[0];s=run(s,actor,'BuyNPCSupply',{goodsId:'materials',quantity:2,acceptedUnitPrice:2000},start+47*DAY).state;s=run(s,actor,'RepairProperty',{propertyId:'npc-Lagos-home',acceptedFee:10000},start+47*DAY).state;
 const submitted=run(s,actor,'SubmitClaim',{policyId,referenceId:incident.id,consent:true,amount:9999999},start+47*DAY);s=submitted.state;const claimId=String(submitted.receipt.detail.claimId);assert.throws(()=>run(s,'unrelated-actor','PayClaim',{claimId}),code('CITIZEN_REQUIRED'));s=run(s,other,'RequestClaimEvidence',{claimId},start+47*DAY).state;assert.throws(()=>run(s,actor,'SupplyClaimEvidence',{claimId},start+47*DAY),code('CLAIM_EVIDENCE'));s=run(s,actor,'SupplyClaimEvidence',{claimId,consent:true},start+47*DAY).state;assert.throws(()=>run(s,actor,'PayClaim',{claimId}),code('CLAIM_NOT_APPROVED'));s=run(s,other,'InvestigateClaim',{claimId},start+47*DAY).state;assert.equal(s.insurance!.claims[claimId].investigator,other);s=run(s,actor,'NPCInvestigateClaim',{claimId},start+47*DAY).state;s=run(s,actor,'DecideClaim',{claimId,choice:0,amount:9999999},start+47*DAY).state;assert.equal(s.insurance!.claims[claimId].payout,5000);assert.equal(s.balances['claim:'+claimId],5000);assert.equal(s.balances['policy:'+policyId],45000);s=run(s,actor,'BlockCitizen',{citizenId:s.citizens[other].id},start+47*DAY).state;assert.equal(citizenView(s,other,start+47*DAY).insurance.claims.length,0);s=run(s,other,'CloseInsurer',{insurerId:insurer.providerId},start+47*DAY).state;s=restoreBackup(exportBackup(s));const pay=cmd('PayClaim',{claimId});s=execute(s,actor,pay,start+47*DAY).state;assert.equal(execute(s,actor,pay,start+48*DAY).replayed,true);assert.equal(s.balances['citizen:'+actor],before-800-4000-10000+5000);assert.throws(()=>run(s,actor,'SubmitClaim',{policyId,referenceId:incident.id,consent:true}),code('CLAIM_DUPLICATE'));reconcile(s);
});
test('preexisting exposure and fabricated invoices cannot bypass waiting, evidence, denial or one independent appeal',()=>{
 let s=homeExposureSetup(setup(),actor);s=exposeHome(s,actor,start+46*DAY).state;const incident=Object.values(s.incidents!.records)[0],policy=buy(s,'npc','property','npc-Lagos-home',actor,start+46*DAY);s=policy.state;const policyId=String(policy.receipt.detail.policyId);s=run(s,actor,'BuyNPCSupply',{goodsId:'materials',quantity:2,acceptedUnitPrice:2000},start+47*DAY).state;s=run(s,actor,'RepairProperty',{propertyId:'npc-Lagos-home',acceptedFee:10000},start+47*DAY).state;
 const submit=run(s,actor,'SubmitClaim',{policyId,referenceId:incident.id,consent:true},start+47*DAY);s=submit.state;const claimId=String(submit.receipt.detail.claimId);s=run(s,actor,'NPCInvestigateClaim',{claimId},start+47*DAY).state;s=run(s,actor,'DecideClaim',{claimId,choice:0},start+47*DAY).state;assert.equal(s.insurance!.claims[claimId].status,'denied');assert.match(s.insurance!.claims[claimId].findings!,/predates/);s=run(s,actor,'AppealClaim',{claimId},start+47*DAY).state;s=run(s,actor,'NPCInvestigateClaim',{claimId},start+47*DAY).state;s=run(s,actor,'DecideClaim',{claimId,choice:0},start+47*DAY).state;assert.throws(()=>run(s,actor,'AppealClaim',{claimId}),code('CLAIM_APPEAL_UNAVAILABLE'));assert.equal(s.balances['policy:'+policyId],50000);
 const fake=run(s,actor,'SubmitClaim',{policyId,referenceId:'fake-invoice',consent:true},start+47*DAY);s=fake.state;assert.equal(s.insurance!.risk.length,1);assert.equal(citizenView(s,other,now).insurance.claims.length,0);reconcile(s);
});
test('player insurers cannot sell unfunded cover or steal protected premium and claim capital',()=>{
 let s=setup();s=graduate(s,other,start);for(const [i,course] of ['secondary','business','finance','insurance'].entries())s=completeCourse(s,other,course,start+(5+i)*DAY);const created=run(s,other,'RegisterCompany',{name:'Reserve Assurance',sector:'finance',capital:500000},start+9*DAY);s=created.state;const companyId=String(created.receipt.detail.companyId),registered=run(s,other,'RegisterInsurer',{companyId},start+9*DAY);s=registered.state;const providerId=String(registered.receipt.detail.insurerId);let firstPolicy='';
 for(let i=0;i<11;i++){const a='insurance-client-'+i;s=run(s,a,'CreateCitizen',{name:a,state:'Lagos',adultConfirmed:true},start+9*DAY).state;if(i===10){assert.throws(()=>buy(s,providerId,'health','',a,start+9*DAY),code('INSUFFICIENT_FUNDS'));break;}const policy=buy(s,providerId,'health','',a,start+9*DAY);s=policy.state;if(!i)firstPolicy=String(policy.receipt.detail.policyId);}
 assert.equal(s.balances['company:'+companyId],0);assert.equal(Object.keys(s.insurance!.policies).length,10);assert.equal(s.balances['policy-premium:'+firstPolicy],5000);assert.throws(()=>run(s,other,'EarnPolicyPremium',{policyId:firstPolicy},start+9*DAY),code('PREMIUM_PENDING'));
 const cash=s.balances['citizen:insurance-client-0'];s=run(s,'insurance-client-0','CancelInsurance',{policyId:firstPolicy},start+9*DAY).state;assert.equal(s.balances['company:'+companyId],50000);assert.equal(s.balances['citizen:insurance-client-0'],cash+5000);s=run(s,other,'CloseInsurer',{insurerId:providerId},start+9*DAY).state;assert.throws(()=>buy(s,providerId,'health','',actor,start+9*DAY),code('INSURER_CLOSED'));reconcile(s);
});
test('expired policies keep open claim and appeal reserves and release only reconciled unused backing',()=>{
 let s=homeExposureSetup(setup(),actor);const policy=buy(s);s=policy.state;const policyId=String(policy.receipt.detail.policyId),expiry=now+INSURANCE_RULES.duration;const claim=run(s,actor,'SubmitClaim',{policyId,referenceId:'missing-evidence',consent:true},expiry-1);s=claim.state;const claimId=String(claim.receipt.detail.claimId);assert.throws(()=>run(s,actor,'CloseExpiredPolicy',{policyId},expiry+8*DAY),code('POLICY_OBLIGATIONS'));s=run(s,actor,'NPCInvestigateClaim',{claimId},expiry+8*DAY).state;s=run(s,actor,'DecideClaim',{claimId,choice:0},expiry+8*DAY).state;assert.throws(()=>run(s,actor,'CloseExpiredPolicy',{policyId},expiry+9*DAY),code('POLICY_OBLIGATIONS'));s=run(s,actor,'CloseExpiredPolicy',{policyId},expiry+16*DAY).state;assert.equal(s.balances['policy:'+policyId],0);assert.equal(s.balances['policy-premium:'+policyId],0);assert.equal(s.insurance!.policies[policyId].status,'closed');reconcile(s);
});
test('actual incident onset and completed clinical invoices govern health cover rather than a submitted diagnosis',()=>{
 const doctor='insurance-clinician';let s=homeExposureSetup(setup(),actor);s=run(s,doctor,'CreateCitizen',{name:'Clinical provider',state:'Lagos',adultConfirmed:true},start).state;s=graduate(s,doctor,start+35*DAY);for(const [i,course] of ['secondary','business','medicine'].entries())s=completeCourse(s,doctor,course,start+(40+i)*DAY);const company=run(s,doctor,'RegisterCompany',{name:'Verified Clinic',sector:'healthcare',capital:200000});s=company.state;const companyId=String(company.receipt.detail.companyId),hospital=run(s,doctor,'RegisterHospital',{companyId});s=hospital.state;const hospitalId=String(hospital.receipt.detail.hospitalId);
 for(const [goodsId,quantity,acceptedUnitPrice] of [['medicine',2,2500],['energy',3,200]] as const)s=run(s,doctor,'BuyNPCSupply',{companyId,goodsId,quantity,acceptedUnitPrice}).state;const policy=buy(s,'npc','health');s=policy.state;const policyId=String(policy.receipt.detail.policyId);s=exposeHome(s,actor,start+47*DAY).state;const intake=run(s,actor,'RequestAssessment',{providerId:hospitalId,acceptedConsultation:5000,consent:true},start+47*DAY);s=intake.state;const caseId=String(intake.receipt.detail.caseId);
 s=run(s,doctor,'AssessPatient',{caseId,choice:0,diagnosis:'invented'},start+47*DAY+2000).state;s=run(s,actor,'AcceptTreatment',{caseId,acceptedFee:10000,acceptTerms:true},start+47*DAY+2001).state;s=run(s,doctor,'TreatPatient',{caseId,choice:0},start+47*DAY+2002).state;s=run(s,actor,'CompleteRecovery',{caseId},start+47*DAY+62002).state;assert.equal(s.healthcare!.cases[caseId].condition,'strain');
 const claim=run(s,actor,'SubmitClaim',{policyId,referenceId:caseId,consent:true,amount:999999},start+47*DAY+62003);s=claim.state;const claimId=claim.receipt.detail.claimId;s=run(s,actor,'NPCInvestigateClaim',{claimId},start+47*DAY+62004).state;s=run(s,actor,'DecideClaim',{claimId,choice:0},start+47*DAY+62005).state;assert.equal(s.insurance!.claims[String(claimId)].payout,10000);s=run(s,actor,'PayClaim',{claimId},start+47*DAY+62006).state;reconcile(s);
});
