import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {join} from 'node:path';
import {rm,writeFile} from 'node:fs/promises';
import {JSDOM,VirtualConsole} from 'jsdom';
import {createApp} from '../src/http.ts';
import {WorldStore} from '../src/store.ts';
import {DomainError,DAY,initialState,execute} from '../src/domain.ts';
import {graduate,completeCourse} from './helpers.ts';
import {temporaryFolder} from './temporary.ts';
const waitFor=async(check:()=>boolean)=>{for(let i=0;i<1000;i++){if(check())return;await new Promise(resolve=>setTimeout(resolve,10));}throw new Error('Interface did not reach the expected state');};
test('citizen creation and nearby wardrobe save curated appearance with safe response-loss retry over HTTP',async t=>{
 const directory=await temporaryFolder('appearance-interface-');t.after(()=>rm(directory,{recursive:true,force:true}));const file=join(directory,'world.json'),store=await WorldStore.open(file),actor='developer-citizen';let clock=10000,drop=false;
 const server=createApp({store,clock:()=>clock,authenticate:async req=>{if(req.headers['x-development-key']!=='appearance_ui_key')throw new DomainError('AUTH_REQUIRED','Enter the test key.',401);return{actorId:actor,sessionId:'appearance-ui-session',assurance:'aal1'};}});
 await new Promise<void>(resolve=>server.listen(0,'127.0.0.1',resolve));t.after(()=>new Promise<void>(resolve=>server.close(()=>resolve())));const address=server.address();if(!address||typeof address==='string')throw Error();const origin='http://127.0.0.1:'+address.port,errors:unknown[]=[],console=new VirtualConsole();console.on('jsdomError',e=>errors.push(e));
 const dom=await JSDOM.fromURL(origin,{runScripts:'dangerously',resources:'usable',pretendToBeVisual:true,virtualConsole:console,beforeParse(window){Object.defineProperty(window.crypto,'randomUUID',{value:randomUUID});window.AbortSignal=AbortSignal as typeof window.AbortSignal;window.fetch=async(url,options)=>{clock+=300;const response=await fetch(new URL(String(url),origin),options);if(drop&&options?.method==='POST'){drop=false;await response.text();throw new TypeError('Response lost after appearance commit');}return response;};}});t.after(()=>dom.window.close());
 if(dom.window.document.readyState!=='complete')await new Promise<void>(resolve=>dom.window.addEventListener('load',()=>resolve(),{once:true}));const doc=dom.window.document,el=(id:string)=>doc.getElementById(id)!,input=(id:string,value:string)=>(el(id) as HTMLInputElement).value=value,submit=(id:string)=>(el(id) as HTMLFormElement).requestSubmit();
 input('access-key','appearance_ui_key');submit('access-form');await waitFor(()=>!el('creation-panel').hidden);assert.equal(el('creation-appearance').querySelectorAll('select').length,7);input('citizen-name','Ada');input('create-appearance-hair','locs');input('create-appearance-outfit','tunic');input('create-appearance-top','wine');(el('adult-confirmed') as HTMLInputElement).checked=true;submit('create-form');await waitFor(()=>!el('citizen-panel').hidden);assert.equal(store.snapshot().citizens[actor].appearance!.hair,'locs');assert.equal(store.snapshot().citizens[actor].appearance!.outfit,'tunic');assert.equal(el('appearance-form').querySelector('button')!.disabled,true);
 const ready=()=>!el('refresh').hasAttribute('disabled'),click=async(button:HTMLElement)=>{button.click();await waitFor(ready);};
 for(let i=0;i<3;i++)await click(doc.querySelector('#world-controls [data-dx="-1"]') as HTMLElement);await click([...el('world-interactions').querySelectorAll('button')].find(b=>b.textContent==='Enter Starter shelter')!);
 const approach=[...el('appearance-form').querySelectorAll('button')].find(b=>b.textContent==='Walk to my wardrobe');assert.ok(approach);approach.click();await waitFor(()=>!el('appearance-form').querySelector('button')!.disabled&&ready());assert.equal(store.snapshot().world!.positions[actor].activity?.kind,'Dress');
 input('appearance-hair','braids');input('appearance-top','sage');drop=true;submit('appearance-form');await waitFor(()=>!el('retry-panel').hidden);assert.equal(store.snapshot().citizens[actor].appearance!.version,2);assert.equal(store.snapshot().citizens[actor].appearance!.hair,'braids');await click(el('retry'));assert.equal(store.snapshot().citizens[actor].appearance!.version,2);assert.equal((el('appearance-hair') as HTMLSelectElement).value,'braids');assert.equal((el('appearance-top') as HTMLSelectElement).value,'sage');assert.equal(dom.window.sessionStorage.getItem('simulator-pending'),null);
 assert.equal((await WorldStore.open(file)).snapshot().citizens[actor].appearance!.hair,'braids');assert.deepEqual(errors,[]);
});
test('corporate workbench submits exact reviewed terms and settles a funded dividend over real HTTP',async t=>{
 const directory=await temporaryFolder('corporate-interface-');t.after(()=>rm(directory,{recursive:true,force:true}));const file=join(directory,'world.json'),actor='developer-citizen',start=10*DAY,clock=start+7*DAY;
 let s=execute(initialState(),actor,{id:'create_corporate_ui',type:'CreateCitizen',payload:{name:'Owner',state:'Lagos',adultConfirmed:true}},start).state;
 s=graduate(s,actor,start);s=completeCourse(s,actor,'secondary',start+5*DAY);s=completeCourse(s,actor,'business',start+6*DAY);
 const company=execute(s,actor,{id:'register_corporate_ui',type:'RegisterCompany',payload:{name:'Interface Works',sector:'services',capital:100000}},clock);s=company.state;
 await writeFile(file,JSON.stringify(s));const store=await WorldStore.open(file);
 const server=createApp({store,clock:()=>clock,authenticate:async req=>{if(req.headers['x-development-key']!=='corporate_ui_key')throw new DomainError('AUTH_REQUIRED','Enter the test key.',401);return{actorId:actor,sessionId:'corporate-ui-session',assurance:'aal1'};}});
 await new Promise<void>(resolve=>server.listen(0,'127.0.0.1',resolve));t.after(()=>new Promise<void>(resolve=>server.close(()=>resolve())));const address=server.address();if(!address||typeof address==='string')throw new Error('Address missing');const origin='http://127.0.0.1:'+address.port,errors:unknown[]=[];
 const virtualConsole=new VirtualConsole();virtualConsole.on('jsdomError',error=>errors.push(error));
 const dom=await JSDOM.fromURL(origin,{runScripts:'dangerously',resources:'usable',pretendToBeVisual:true,virtualConsole,beforeParse(window){Object.defineProperty(window.crypto,'randomUUID',{value:randomUUID});window.AbortSignal=AbortSignal as typeof window.AbortSignal;window.confirm=()=>true;window.fetch=(url,options)=>fetch(new URL(String(url),origin),options);}});t.after(()=>dom.window.close());
 if(dom.window.document.readyState!=='complete')await new Promise<void>(resolve=>dom.window.addEventListener('load',()=>resolve(),{once:true}));const doc=dom.window.document;
 (doc.getElementById('access-key') as HTMLInputElement).value='corporate_ui_key';(doc.getElementById('access-form') as HTMLFormElement).requestSubmit();
 await waitFor(()=>!(doc.getElementById('citizen-panel') as HTMLElement).hidden);
 assert.equal((doc.getElementById('governance-panel') as HTMLElement).hidden,false);
 assert.equal((doc.getElementById('governance-company') as HTMLSelectElement).value,company.receipt.detail.companyId);
 (doc.getElementById('governance-amount') as HTMLInputElement).value='123.45';(doc.getElementById('governance-create') as HTMLFormElement).requestSubmit();
 await waitFor(()=>Object.keys(store.snapshot().governance?.actions??{}).length===1&&!(doc.getElementById('refresh') as HTMLButtonElement).disabled);
 const proposal=Object.values(store.snapshot().governance!.actions)[0];assert.equal(proposal.amount,12345);assert.equal(proposal.status,'ready');assert.equal(store.snapshot().balances['corporate:'+proposal.id],12345);
 const button=[...doc.querySelectorAll<HTMLButtonElement>('#governance-records button')].find(b=>b.textContent==='Settle approved funds and shares once');assert.ok(button);assert.equal(button.disabled,false);button.click();
 await waitFor(()=>store.snapshot().governance!.actions[proposal.id].status==='executed');assert.equal(store.snapshot().balances['corporate:'+proposal.id],0);
 assert.match(doc.getElementById('governance-records')!.textContent!,/dividend/);assert.deepEqual(errors,[]);
});
test('accessible DOM runs guide, funded work, practical study, households and response-loss retry over real HTTP',async t=>{
 const directory=await temporaryFolder('interface-');t.after(()=>rm(directory,{recursive:true,force:true}));const store=await WorldStore.open(join(directory,'world.json'));let clock=10*DAY,dropNext=false,requests=0;
 const server=createApp({store,clock:()=>clock,authenticate:async req=>{if(req.headers['x-development-key']!=='ui_test_access')throw new DomainError('AUTH_REQUIRED','Enter the local access key.',401);return{actorId:'developer-citizen',sessionId:'ui-session',assurance:'aal1'};}});
 await new Promise<void>(resolve=>server.listen(0,'127.0.0.1',resolve));t.after(()=>new Promise<void>(resolve=>server.close(()=>resolve())));const address=server.address();if(!address||typeof address==='string')throw new Error('Address missing');const origin='http://127.0.0.1:'+address.port,errors:unknown[]=[];
 const virtualConsole=new VirtualConsole();virtualConsole.on('jsdomError',error=>errors.push(error));
 const dom=await JSDOM.fromURL(origin,{runScripts:'dangerously',resources:'usable',pretendToBeVisual:true,virtualConsole,beforeParse(window){Object.defineProperty(window.crypto,'randomUUID',{value:randomUUID});window.AbortSignal=AbortSignal as typeof window.AbortSignal;window.fetch=async(url,options)=>{const response=await fetch(new URL(String(url),origin),options);requests++;if(dropNext&&options?.method==='POST'){dropNext=false;await response.text();throw new TypeError('Simulated response loss after commit');}return response;};}});t.after(()=>dom.window.close());
 if(dom.window.document.readyState!=='complete')await new Promise<void>(resolve=>dom.window.addEventListener('load',()=>resolve(),{once:true}));const doc=dom.window.document,el=(id:string)=>{const node=doc.getElementById(id);if(!node)throw new Error('Missing '+id);return node;},input=(id:string,value:string)=>{(el(id) as HTMLInputElement).value=value;};
 const submit=(id:string)=>(el(id) as HTMLFormElement).requestSubmit();
 input('access-key','ui_test_access');submit('access-form');await waitFor(()=>!el('creation-panel').hidden);assert.equal((el('citizen-state') as HTMLSelectElement).options.length,37);
 input('citizen-name','Ada');(el('adult-confirmed') as HTMLInputElement).checked=true;submit('create-form');await waitFor(()=>!el('citizen-panel').hidden);assert.equal(el('greeting').textContent,'Welcome, Ada.');
 const click=async(node:HTMLElement)=>{const before=requests;node.click();await waitFor(()=>requests>before&&!el('refresh').hasAttribute('disabled'));};
 await click(el('guide'));
 for(let i=0;i<3;i++){clock+=300;await click(doc.querySelector('#world-controls [data-dx="-1"]') as HTMLElement);}
 const worldAction=(text:string)=>{const b=[...el('world-interactions').querySelectorAll('button')].find(b=>b.textContent===text);if(!b)throw new Error('Missing world action '+text);return b;};
 await click(worldAction('Enter Starter shelter'));assert.equal(store.snapshot().world?.positions['developer-citizen'].interior,'shelter');await click(worldAction('Exit to the city'));await click(el('meal'));
 input('work-job','courier');await click(el('work'));for(let i=0;i<3;i++){clock+=2000;await click(el('refresh'));await click(el('work-task').querySelector('button')!);}
 clock+=60000;await click(el('refresh'));await click(el('work-actions').querySelector('button')!);assert.equal(store.snapshot().balances['citizen:developer-citizen'],2020000);
 await click(el('lessons').querySelector('details button')!);assert.deepEqual(store.snapshot().citizens['developer-citizen'].completedLessons,[1]);
 input('household-name','Ada household');(el('household-consent') as HTMLInputElement).checked=true;submit('household-create');await waitFor(()=>el('family-status').textContent?.includes('Ada household')??false);assert.ok(store.snapshot().citizens['developer-citizen'].life?.householdId);
 const before=store.snapshot().balances['citizen:developer-citizen'];dropNext=true;el('meal').click();await waitFor(()=>!el('retry-panel').hidden);assert.equal(store.snapshot().balances['citizen:developer-citizen'],before-5000);await click(el('retry'));assert.equal(store.snapshot().balances['citizen:developer-citizen'],before-5000);assert.equal(dom.window.sessionStorage.getItem('simulator-pending'),null);
 const propertyButton=(label:string)=>{const b=[...el('property-records').querySelectorAll('button')].find(b=>b.textContent===label);if(!b)throw new Error('Missing property action '+label);return b;};
 await click(propertyButton('Accept price and reserve title'));await click(propertyButton('Complete title transfer'));assert.equal(store.snapshot().property?.assets['npc-Lagos-land'].owner,'developer-citizen');
 assert.equal(el('teaching-panel').closest('#citizen-panel'),el('citizen-panel'));
 await click([...el('mobility-records').querySelectorAll('button')].find(b=>b.textContent==='Accept vehicle purchase terms')!);assert.equal(Object.values(store.snapshot().mobility!.vehicles)[0].owner,'developer-citizen');assert.equal(Object.values(store.snapshot().mobility!.vehicles)[0].fuel,0);
 const careButton=(text:string)=>{const b=[...el('healthcare-records').querySelectorAll('button')].find(b=>b.textContent===text);if(!b)throw new Error('Missing healthcare action '+text);return b;};
 await click(careButton('Consent to scoped assessment'));clock+=2000;await click(el('refresh'));await click(careButton('Use approved game assessment'));await click(careButton('Accept treatment terms and reserve '+new Intl.NumberFormat('en-NG',{style:'currency',currency:'NGN'}).format(0)));await click(careButton('Verify procedure and commit supplies'));clock+=60000;await click(el('refresh'));await click(careButton('Record completed recovery and settle care'));assert.equal(Object.values(store.snapshot().healthcare!.cases)[0].status,'completed');
 const policyButton=[...el('insurance-records').querySelectorAll('button')].find(b=>b.textContent==='Accept disclosed coverage and reserve backing')!;await click(policyButton);assert.equal(Object.values(store.snapshot().insurance!.policies)[0].remaining,50000);await click([...el('insurance-records').querySelectorAll('button')].find(b=>b.textContent==='Cancel unused coverage and refund premium')!);assert.equal(Object.values(store.snapshot().insurance!.policies)[0].status,'cancelled');
 assert.equal(doc.querySelectorAll('script[src="/phaser.js"]').length,0,'Data saver does not download optional graphics');assert.deepEqual(errors,[]);
 // JSDOM verifies event wiring and accessible flows; it is not a browser,
 // renderer, CSP, device, timing performance or visual acceptance result.
});
test('main keyboard walking submits server commands and never moves while editing a form',async t=>{
 const directory=await temporaryFolder('walking-interface-');t.after(()=>rm(directory,{recursive:true,force:true}));const store=await WorldStore.open(join(directory,'world.json'));await store.dispatch('walker',{id:'create_keyboard_citizen',type:'CreateCitizen',payload:{name:'Walker',state:'Lagos',adultConfirmed:true}},Date.now());
 const server=createApp({store,authenticate:async req=>{if(req.headers['x-development-key']!=='walking_key')throw new DomainError('AUTH_REQUIRED','Sign in.',401);return {actorId:'walker',sessionId:'walking-session',assurance:'aal1'};}});await new Promise<void>(resolve=>server.listen(0,'127.0.0.1',resolve));t.after(()=>new Promise<void>(resolve=>server.close(()=>resolve())));const a=server.address();if(!a||typeof a==='string')throw Error();const origin='http://127.0.0.1:'+a.port;
 const dom=await JSDOM.fromURL(origin,{resources:'usable',runScripts:'dangerously',pretendToBeVisual:true,beforeParse(window){Object.defineProperty(window.crypto,'randomUUID',{value:randomUUID});window.AbortSignal=AbortSignal as typeof window.AbortSignal;window.fetch=(url,init)=>fetch(new URL(String(url),origin),init);}});t.after(()=>dom.window.close());const doc=dom.window.document;
 if(doc.readyState!=='complete')await new Promise<void>(resolve=>dom.window.addEventListener('load',()=>resolve(),{once:true}));(doc.getElementById('access-key') as HTMLInputElement).value='walking_key';(doc.getElementById('access-form') as HTMLFormElement).requestSubmit();await waitFor(()=>!(doc.getElementById('citizen-panel') as HTMLElement).hidden);
 doc.dispatchEvent(new dom.window.KeyboardEvent('keydown',{key:'a',bubbles:true}));await waitFor(()=>store.snapshot().world!.positions.walker.x===6);doc.dispatchEvent(new dom.window.KeyboardEvent('keyup',{key:'a',bubbles:true}));assert.equal(store.snapshot().world!.positions.walker.facing,'left');
 const input=doc.getElementById('household-name') as HTMLInputElement;input.focus();input.dispatchEvent(new dom.window.KeyboardEvent('keydown',{key:'d',bubbles:true}));await new Promise(r=>setTimeout(r,350));assert.equal(store.snapshot().world!.positions.walker.x,6);
 doc.dispatchEvent(new dom.window.KeyboardEvent('keydown',{key:'d',bubbles:true}));await waitFor(()=>store.snapshot().world!.positions.walker.x===7);dom.window.dispatchEvent(new dom.window.Event('blur'));assert.equal(store.snapshot().world!.positions.walker.facing,'right');
});
test('main floor selection saves a paid object and click-to-walk reaches a usable fixture through real HTTP',async t=>{
 const directory=await temporaryFolder('furnishing-interface-');t.after(()=>rm(directory,{recursive:true,force:true}));const store=await WorldStore.open(join(directory,'world.json')),actor='resident';
 await store.dispatch(actor,{id:'create_floor_resident',type:'CreateCitizen',payload:{name:'Resident',state:'Lagos',adultConfirmed:true}},100);for(let i=0;i<3;i++)await store.dispatch(actor,{id:'floor_street_'+i,type:'MoveCitizen',payload:{dx:-1,dy:0}},1000+i*300);await store.dispatch(actor,{id:'floor_enter_home',type:'EnterBuilding',payload:{buildingId:'shelter'}},3000);const bought=await store.dispatch(actor,{id:'floor_buy_plant',type:'BuyFurniture',payload:{modelId:'plant',acceptedPrice:7000,finish:'sage',acceptTerms:true}},4000),itemId=String(bought.receipt.detail.furnitureId),homeId=store.snapshot().world!.positions[actor].homeId!;
 const server=createApp({store,authenticate:async req=>{if(req.headers['x-development-key']!=='floor_test_key')throw new DomainError('AUTH_REQUIRED','Sign in.',401);return {actorId:actor,sessionId:'floor-session',assurance:'aal1'};}});await new Promise<void>(resolve=>server.listen(0,'127.0.0.1',resolve));t.after(()=>new Promise<void>(resolve=>server.close(()=>resolve())));const a=server.address();if(!a||typeof a==='string')throw Error();const origin='http://127.0.0.1:'+a.port,errors:unknown[]=[];const vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e));
 const dom=await JSDOM.fromURL(origin,{resources:'usable',runScripts:'dangerously',pretendToBeVisual:true,virtualConsole:vc,beforeParse(window){Object.defineProperty(window.crypto,'randomUUID',{value:randomUUID});window.AbortSignal=AbortSignal as typeof window.AbortSignal;window.confirm=()=>true;window.fetch=(url,init)=>fetch(new URL(String(url),origin),init);}});t.after(()=>dom.window.close());const doc=dom.window.document;if(doc.readyState!=='complete')await new Promise<void>(resolve=>dom.window.addEventListener('load',()=>resolve(),{once:true}));(doc.getElementById('access-key') as HTMLInputElement).value='floor_test_key';(doc.getElementById('access-form') as HTMLFormElement).requestSubmit();await waitFor(()=>!(doc.getElementById('citizen-panel') as HTMLElement).hidden);
 const form=[...doc.querySelectorAll<HTMLFormElement>('#furnishing-records form')].find(f=>f.querySelector('h3')?.textContent==='Indoor palm planter')!;[...form.querySelectorAll('button')].find(b=>b.textContent==='Choose position on the floor')!.click();dom.window.dispatchEvent(new dom.window.CustomEvent('furniture-floor-select',{detail:{itemId,homeId,homeVersion:1,x:9,y:6,valid:true}}));assert.deepEqual([...form.querySelectorAll<HTMLInputElement>('input[type=number]')].map(i=>i.value),['9','6']);form.requestSubmit();await waitFor(()=>store.snapshot().furnishing!.items[itemId].placement?.x===9&&!(doc.getElementById('refresh') as HTMLButtonElement).disabled);assert.equal(store.snapshot().furnishing!.homes[homeId].version,2);
 const select=(x:number,y:number)=>dom.window.dispatchEvent(new dom.window.CustomEvent('world-tile-select',{detail:{x,y,homeId,leaseVersion:2}}));select(5,4);await waitFor(()=>store.snapshot().world!.positions[actor].interiorX===5&&store.snapshot().world!.positions[actor].interiorY===4&&!(doc.getElementById('refresh') as HTMLButtonElement).disabled);
 dom.window.dispatchEvent(new dom.window.CustomEvent('home-fixture-select',{detail:{fixtureId:'sofa',homeId,leaseVersion:2}}));await waitFor(()=>store.snapshot().world!.positions[actor].activity?.kind==='Sit');const count=Object.keys(store.snapshot().commands).length;select(100,100);await new Promise(r=>setTimeout(r,50));assert.equal(Object.keys(store.snapshot().commands).length,count);
 // A selected distant sink walks into range before interacting, rather than rejecting the selection.
 dom.window.dispatchEvent(new dom.window.CustomEvent('home-fixture-select',{detail:{fixtureId:'sink',homeId,leaseVersion:2}}));await waitFor(()=>store.snapshot().world!.positions[actor].activity?.kind==='Wash');
 const exit=[...doc.querySelectorAll<HTMLButtonElement>('#world-interactions button')].find(b=>b.textContent==='Exit to the city')!;await waitFor(()=>!exit.disabled);exit.click();await waitFor(()=>store.snapshot().world!.positions[actor].interior===null&&!(doc.getElementById('refresh') as HTMLButtonElement).disabled);
 // Use the accessible navigation action; the actual server gate remains near the door.
 const visit=[...doc.querySelectorAll<HTMLButtonElement>('#world-navigation button')].find(b=>b.textContent==='Visit Starter shelter')!;visit.click();await waitFor(()=>store.snapshot().world!.positions[actor].interior==='shelter'&&store.snapshot().world!.positions[actor].leaseVersion===4&&!(doc.getElementById('refresh') as HTMLButtonElement).disabled);
 const materials=[...doc.querySelectorAll<HTMLButtonElement>('#partition-build button')].find(b=>b.textContent==='Buy the required materials')!;materials.click();await waitFor(()=>Object.values(store.snapshot().commerce?.batches??{}).some(b=>b.goods==='materials'&&b.quantity===4)&&!(doc.getElementById('refresh') as HTMLButtonElement).disabled);
 (doc.getElementById('partition-build') as HTMLFormElement).requestSubmit();await waitFor(()=>store.snapshot().furnishing!.homes[homeId].partitions?.length===10&&!(doc.getElementById('refresh') as HTMLButtonElement).disabled);assert.equal(store.snapshot().furnishing!.homes[homeId].version,3);assert.match(doc.getElementById('home-architecture')!.textContent!,/Room plan: 2 areas/);assert.deepEqual(errors,[]);
});

test('object approach stops on an uncertain move response and blur without entering or settling an action',async t=>{
 const store=await WorldStore.open(),actor='route-resident';await store.dispatch(actor,{id:'create_route_resident',type:'CreateCitizen',payload:{name:'Resident',state:'Lagos',adultConfirmed:true}},100);let dropNext=true;
 const server=createApp({store,authenticate:async req=>{if(req.headers['x-development-key']!=='route_test_key')throw new DomainError('AUTH_REQUIRED','Sign in.',401);return{actorId:actor,sessionId:'route-session',assurance:'aal1'};}});await new Promise<void>(resolve=>server.listen(0,'127.0.0.1',resolve));t.after(()=>new Promise<void>(resolve=>server.close(()=>resolve())));const address=server.address();if(!address||typeof address==='string')throw Error();const origin='http://127.0.0.1:'+address.port,errors:unknown[]=[];const vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e));
 const dom=await JSDOM.fromURL(origin,{resources:'usable',runScripts:'dangerously',pretendToBeVisual:true,virtualConsole:vc,beforeParse(window){Object.defineProperty(window.crypto,'randomUUID',{value:randomUUID});window.AbortSignal=AbortSignal as typeof window.AbortSignal;window.fetch=async(url,init)=>{const response=await fetch(new URL(String(url),origin),init);if(dropNext&&init?.method==='POST'&&String(url)==='/api/commands'){dropNext=false;await response.text();throw new TypeError('Response lost after movement commit');}return response;};}});t.after(()=>dom.window.close());const doc=dom.window.document;if(doc.readyState!=='complete')await new Promise<void>(resolve=>dom.window.addEventListener('load',()=>resolve(),{once:true}));(doc.getElementById('access-key') as HTMLInputElement).value='route_test_key';(doc.getElementById('access-form') as HTMLFormElement).requestSubmit();await waitFor(()=>!(doc.getElementById('citizen-panel') as HTMLElement).hidden);
 const select=()=>dom.window.dispatchEvent(new dom.window.CustomEvent('building-select',{detail:{buildingId:'shelter',leaseVersion:1}}));select();await waitFor(()=>!(doc.getElementById('retry-panel') as HTMLElement).hidden);const committed=store.snapshot();assert.equal(committed.world!.positions[actor].x,6);assert.equal(committed.world!.positions[actor].interior,null);await new Promise(r=>setTimeout(r,400));assert.equal(Object.keys(store.snapshot().commands).length,Object.keys(committed.commands).length);
 (doc.getElementById('retry') as HTMLButtonElement).click();await waitFor(()=>dom.window.sessionStorage.getItem('simulator-pending')===null&&!(doc.getElementById('refresh') as HTMLButtonElement).disabled);await new Promise(r=>setTimeout(r,350));assert.equal(store.snapshot().world!.positions[actor].x,6);assert.equal(store.snapshot().world!.positions[actor].interior,null);
 select();await waitFor(()=>store.snapshot().world!.positions[actor].x===5);dom.window.dispatchEvent(new dom.window.Event('blur'));await new Promise(r=>setTimeout(r,450));assert.equal(store.snapshot().world!.positions[actor].interior,null);assert.equal(store.snapshot().world!.positions[actor].x,5);assert.deepEqual(errors,[]);
});
