import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {JSDOM,VirtualConsole} from 'jsdom';
import {WebSocket} from 'ws';
import {WorldStore} from '../src/store.ts';
import {createApp} from '../src/http.ts';
import {DomainError} from '../src/domain.ts';
import {RELATIONSHIP_RULES} from '../src/relationships.ts';
const waitFor=async(check:()=>boolean)=>{for(let i=0;i<800;i++){if(check())return;await new Promise(resolve=>setTimeout(resolve,10));}throw Error('Relationship interface did not settle');};
test('two authenticated clients opt in, consent to a friendship, recover lost acceptance and separately review home access before blocking',async t=>{
 const store=await WorldStore.open(),doms:JSDOM[]=[],sockets:WebSocket[]=[],errors:unknown[]=[];let clock=Date.now(),sequence=0,dropAcceptance=false;
 const run=(actor:string,type:string,payload:Record<string,unknown>={})=>store.dispatch(actor,{id:'social_ui_setup_'+ ++sequence,type,payload},clock+=700);
 for(const [actor,name] of [['social-host','Ada'],['social-guest','Bola']])await run(actor,'CreateCitizen',{name,state:'Lagos',adultConfirmed:true});
 for(let i=0;i<3;i++)await run('social-host','MoveCitizen',{dx:-1,dy:0});await run('social-host','EnterBuilding',{buildingId:'shelter'});
 const server=createApp({store,multiplayer:true,clock:()=>clock,authenticate:async req=>{const actor=String(req.headers['x-development-key']??'');if(!['social-host','social-guest'].includes(actor))throw new DomainError('AUTH_REQUIRED','Sign in.',401);return{actorId:actor,sessionId:actor+'-session',assurance:'aal1'};}});await new Promise<void>(resolve=>server.listen(0,'127.0.0.1',resolve));t.after(async()=>{doms.forEach(d=>d.window.close());sockets.forEach(s=>s.terminate());await new Promise<void>(resolve=>server.close(()=>resolve()));});const address=server.address();if(!address||typeof address==='string')throw Error();const origin='http://127.0.0.1:'+address.port;
 async function browser(actor:string){const vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e));const dom=await JSDOM.fromURL(origin,{runScripts:'dangerously',resources:'usable',pretendToBeVisual:true,virtualConsole:vc,beforeParse(w){Object.defineProperty(w.crypto,'randomUUID',{value:randomUUID});w.AbortSignal=AbortSignal as typeof w.AbortSignal;w.WebSocket=class extends WebSocket{constructor(url:string|URL){super(String(url),{origin});sockets.push(this);}} as unknown as typeof w.WebSocket;w.fetch=async(url,options)=>{if(String(url)==='/api/commands')clock+=700;const response=await fetch(new URL(String(url),origin),options);if(dropAcceptance&&actor==='social-guest'&&String(options?.body).includes('AcceptRelationship')){dropAcceptance=false;await response.text();throw new TypeError('Response lost after relationship acceptance');}return response;};}});doms.push(dom);const d=dom.window.document;if(d.readyState!=='complete')await new Promise<void>(resolve=>dom.window.addEventListener('load',()=>resolve(),{once:true}));(d.getElementById('access-key') as HTMLInputElement).value=actor;(d.getElementById('access-form') as HTMLFormElement).requestSubmit();await waitFor(()=>d.getElementById('connection-status')!.textContent!.startsWith('Connected')&&!(d.getElementById('refresh') as HTMLButtonElement).disabled);const saver=d.getElementById('data-saver') as HTMLInputElement;saver.checked=true;saver.dispatchEvent(new dom.window.Event('change'));return dom;}
 const host=await browser('social-host'),guest=await browser('social-guest'),hd=host.window.document,gd=guest.window.document;
 const button=(d:Document,root:string,label:string)=>[...d.querySelectorAll<HTMLButtonElement>(root+' button')].find(b=>b.textContent===label);
 const idle=(d:Document)=>!(d.getElementById('refresh') as HTMLButtonElement).disabled;
 assert.equal((gd.getElementById('privacy-relationships') as HTMLInputElement).checked,false);
 (gd.getElementById('privacy-relationships') as HTMLInputElement).checked=true;(gd.getElementById('privacy-form') as HTMLFormElement).requestSubmit();await waitFor(()=>store.snapshot().citizens['social-guest'].life!.privacy.relationships===true&&idle(gd));
 const invite=hd.querySelector<HTMLFormElement>('#relationships-records form[data-action=invite]')!;invite.querySelector<HTMLInputElement>('[name=citizenId]')!.value=store.snapshot().citizens['social-guest'].id;invite.querySelector<HTMLInputElement>('[name=consent]')!.checked=true;invite.requestSubmit();await waitFor(()=>!!button(gd,'#relationships-records','Accept relationship')&&idle(hd)&&idle(gd));
 const r=Object.values(store.snapshot().relationships!.records)[0],accept=button(gd,'#relationships-records','Accept relationship')!.form!;accept.requestSubmit();await new Promise(resolve=>setTimeout(resolve,20));assert.equal(store.snapshot().relationships!.records[r.id].status,'invited');
 dropAcceptance=true;accept.querySelector<HTMLInputElement>('[name=consent]')!.checked=true;accept.requestSubmit();await waitFor(()=>!(gd.getElementById('retry-panel') as HTMLElement).hidden);assert.equal(store.snapshot().relationships!.records[r.id].status,'active');await waitFor(()=>!button(gd,'#retry-panel','Retry last action')!.disabled);button(gd,'#retry-panel','Retry last action')!.click();await waitFor(()=>(gd.getElementById('retry-panel') as HTMLElement).hidden&&!!button(hd,'#relationships-records','End relationship')&&idle(hd)&&idle(gd));assert.equal(Object.values(store.snapshot().commands).filter(c=>c.receipt.type==='AcceptRelationship').length,1);
 assert.deepEqual(store.snapshot().world!.positions['social-guest'].interior,null);assert.equal(Object.values(store.snapshot().furnishing!.visits??{}).length,0);
 const homeForm=button(hd,'#relationships-records','Invite for a 15-minute home visit')!.form!;homeForm.querySelector<HTMLInputElement>('[name=consent]')!.checked=true;homeForm.requestSubmit();await waitFor(()=>!!button(gd,'#home-visits-records','Accept home visit')&&idle(hd)&&idle(gd));const visit=Object.values(store.snapshot().furnishing!.visits!)[0];assert.equal(visit.status,'invited');assert.equal(store.snapshot().world!.positions['social-guest'].interior,null);
 button(gd,'#relationships-records','Block citizen')!.click();await waitFor(()=>store.snapshot().relationships!.records[r.id].status==='ended'&&hd.getElementById('relationships-records')!.textContent!.includes('Ended: blocked.')&&gd.getElementById('relationships-records')!.textContent!.includes('Ended: blocked.'));assert.equal(store.snapshot().furnishing!.visits![visit.id].status,'ended');assert.ok(!button(hd,'#relationships-records','Invite for a 15-minute home visit'));assert.deepEqual(errors,[]);
 // A revoked session must clear the private panel, not retain old consent text.
 await store.revokeSession('social-guest','social-guest-session');await waitFor(()=>gd.getElementById('citizen-panel')!.hidden);assert.equal(gd.getElementById('relationships-records')!.children.length,0);assert.equal(gd.getElementById('relationships-panel')!.hidden,true);
});
test('a pending relationship expires on the connected recipient screen with no new business event or recipient action',async t=>{
 const store=await WorldStore.open();let clock=Date.now();const created=clock-RELATIONSHIP_RULES.invitationDuration+10000;let sequence=0;
 const run=(actor:string,type:string,payload:Record<string,unknown>={})=>store.dispatch(actor,{id:'social_expiry_'+ ++sequence,type,payload},created);
 for(const [actor,name] of [['expiry-ada','Ada'],['expiry-bola','Bola']])await run(actor,'CreateCitizen',{name,state:'Lagos',adultConfirmed:true});await run('expiry-bola','SetPrivacy',{relationships:true});await run('expiry-ada','InviteRelationship',{citizenId:store.snapshot().citizens['expiry-bola'].id,kind:'friend',termsVersion:RELATIONSHIP_RULES.version,acceptTerms:true});
 const server=createApp({store,multiplayer:true,clock:()=>clock,authenticate:async req=>{if(req.headers['x-development-key']!=='expiry-bola')throw new DomainError('AUTH_REQUIRED','Sign in.',401);return{actorId:'expiry-bola',sessionId:'expiry-session',assurance:'aal1'};}});await new Promise<void>(resolve=>server.listen(0,'127.0.0.1',resolve));const a=server.address();if(!a||typeof a==='string')throw Error();const origin='http://127.0.0.1:'+a.port,sockets:WebSocket[]=[],errors:unknown[]=[],vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e));
 const dom=await JSDOM.fromURL(origin,{runScripts:'dangerously',resources:'usable',pretendToBeVisual:true,virtualConsole:vc,beforeParse(w){Object.defineProperty(w.crypto,'randomUUID',{value:randomUUID});w.AbortSignal=AbortSignal as typeof w.AbortSignal;w.WebSocket=class extends WebSocket{constructor(url:string|URL){super(String(url),{origin});sockets.push(this);}} as unknown as typeof w.WebSocket;w.fetch=(url,options)=>fetch(new URL(String(url),origin),options);}});t.after(async()=>{dom.window.close();sockets.forEach(s=>s.terminate());await new Promise<void>(resolve=>server.close(()=>resolve()));});const d=dom.window.document;if(d.readyState!=='complete')await new Promise<void>(resolve=>dom.window.addEventListener('load',()=>resolve(),{once:true}));(d.getElementById('access-key') as HTMLInputElement).value='expiry-bola';(d.getElementById('access-form') as HTMLFormElement).requestSubmit();await waitFor(()=>d.getElementById('connection-status')!.textContent!.startsWith('Connected')&&!!d.querySelector('#relationships-records form[data-action=accept]'));
 const cursor=store.snapshot().outbox.length,r=Object.values(store.snapshot().relationships!.records)[0];clock=r.expiresAt;
 await waitFor(()=>d.getElementById('relationships-records')!.textContent!.includes('Ended: expired.')&&!d.querySelector('#relationships-records form[data-action=accept]'));assert.equal(store.snapshot().outbox.length,cursor);assert.equal(store.snapshot().relationships!.records[r.id].status,'invited');assert.deepEqual(errors,[]);
});
