import {createHash} from 'node:crypto';
import {DomainError,post} from './domain.ts';
import {DAY} from './rules.ts';
import type {State,Command} from './domain.ts';
import {hasLicence} from './education.ts';
import {positionFor,travelQuote} from './world.ts';
import {stockPost} from './stock.ts';
import type {StockState} from './stock.ts';
import {issuedShares,proportionalDividend} from './governance.ts';
import {activeNeeds,citizenLife} from './life.ts';
export const GOODS=[
 {id:'seeds',name:'Seed units',price:500,shelfLife:90*DAY}, {id:'water',name:'Water units',price:100,shelfLife:90*DAY},
 {id:'grain',name:'Grain',price:1000,shelfLife:30*DAY},{id:'food',name:'Prepared food',price:5000,shelfLife:7*DAY},
 {id:'fuel',name:'Fuel litres',price:300,shelfLife:180*DAY},{id:'ore',name:'Mineral ore',price:1000,shelfLife:365*DAY},
 {id:'crude',name:'Crude feedstock',price:1200,shelfLife:365*DAY},{id:'materials',name:'Building materials',price:2000,shelfLife:365*DAY},
 {id:'energy',name:'Stored power units',price:200,shelfLife:30*DAY},{id:'medicine',name:'Basic game medical supplies',price:2500,shelfLife:30*DAY},
 {id:'devices',name:'Consumer devices',price:15000,shelfLife:365*DAY},{id:'tourism',name:'Verified visitor service vouchers',price:12000,shelfLife:7*DAY}
];
export const RECIPES=[
 {id:'farming',name:'Grow a grain batch',sector:'agriculture',inputs:{seeds:2,water:4,fuel:1},output:'grain',quantity:20,labour:25000,node:null},
 {id:'milling',name:'Prepare food',sector:'manufacturing',inputs:{grain:5,fuel:1},output:'food',quantity:5,labour:10000,node:null},
 {id:'mining',name:'Extract mineral ore',sector:'mining',inputs:{fuel:2,materials:1},output:'ore',quantity:10,labour:20000,node:'mineral'},
 {id:'oil',name:'Extract crude feedstock',sector:'energy',inputs:{materials:1,energy:4},output:'crude',quantity:10,labour:25000,node:'oil'},
 {id:'refining',name:'Refine fuel',sector:'energy',inputs:{crude:5,energy:3},output:'fuel',quantity:20,labour:20000,node:null},
 {id:'manufacturing',name:'Produce building materials',sector:'manufacturing',inputs:{ore:4,fuel:2},output:'materials',quantity:5,labour:25000,node:null},
 {id:'power',name:'Generate stored power',sector:'energy',inputs:{fuel:3},output:'energy',quantity:30,labour:15000,node:null},
 {id:'technology',name:'Assemble devices',sector:'technology',inputs:{materials:3,energy:4},output:'devices',quantity:2,labour:25000,node:null},
 {id:'tourism',name:'Deliver visitor services',sector:'tourism',inputs:{food:2,energy:1},output:'tourism',quantity:4,labour:10000,node:null}
];
export const SECTORS=['agriculture','manufacturing','mining','energy','ports','tourism','technology','education','healthcare','transport','media','security','finance','services'];
export type Company={id:string;name:string;region:string;sector:string;members:Record<string,string>;shares:Record<string,number>;issuedShares?:number;lastActive:Record<string,number>;status:'active'|'distressed'|'restructuring'|'closed';actingManager:string|null;version:number};
type RoleInvite={id:string;company:string;sender:string;recipient:string;role:string;expiresAt:number;status:'pending'|'accepted'|'declined'};
type Batch={id:string;owner:string;region:string;goods:string;quantity:number;unitCost:number;createdAt:number;expiresAt:number;source:string;quality:number;version:number};
type Listing={id:string;batch:string;company:string;quantity:number;remaining:number;price:number;status:'open'|'closed';version:number};
type Quote={id:string;actor:string;listing:string;quantity:number;price:number;shipping:number;destination:string;duration:number;expiresAt:number;status:'quoted'|'funded'};
type Order={id:string;quote:string;buyer:string;company:string;goods:string;quantity:number;unitCost:number;price:number;shipping:number;origin:string;destination:string;status:'funded'|'picked'|'carrier-assigned'|'dispatched'|'in-transit'|'delivered'|'accepted'|'cancelled'|'disputed'|'damaged'|'refunded';lastStageAt:number;arriveAt:number;deliveredAt:number|null;custody:{at:number;holder:string;stage:string}[];version:number};
type Production={id:string;company:string;recipe:string;quantity:number;cost:number;startedAt:number;readyAt:number;status:'running'|'completed';version:number};
type Review={id:string;order:string;actor:string;company:string;score:number;text:string;at:number;editedAt:number|null};
export type CommerceState={stock?:StockState;companies:Record<string,Company>;invites:Record<string,RoleInvite>;batches:Record<string,Batch>;listings:Record<string,Listing>;quotes:Record<string,Quote>;orders:Record<string,Order>;production:Record<string,Production>;reviews:Record<string,Review>;npcStock:Record<string,number>;nodes:Record<string,number>;warehouse:Record<string,number>;roads:Record<string,number>;fuelPrice:number;risk:{id:string;reason:string;references:string[];at:number}[]};
export const getCommerce=(state:State)=>state.commerce??={companies:{},invites:{},batches:{},listings:{},quotes:{},orders:{},production:{},reviews:{},npcStock:{},nodes:{},warehouse:{},roads:{},fuelPrice:300,risk:[]};
export function consumeNpcMeal(state:State,actor:string,now:number,key:string,assistance=false){
 const c=state.citizens[actor],region=positionFor(state,c,now).region,m=getCommerce(state),period=region+':'+Math.floor(now/DAY)+':food',remaining=m.npcStock[period]??10000;
 if(!assistance&&remaining<=0)throw new DomainError('FOOD_STOCK_LIMIT','The ordinary NPC period stock is exhausted. Protective assistance remains available.');if(!assistance)m.npcStock[period]=remaining-1;
 stockPost(state,{id:'meal:'+key,goods:'food',at:now,reason:assistance?'Budgeted protective food':'Purchased NPC meal consumption',entries:[{account:'system:'+(assistance?'protective-food:':'npc-food:')+period,quantity:-1},{account:'system:meal-consumed',quantity:1}]});
}
const integer=(v:unknown,min=1,max=100000000)=>{if(!Number.isSafeInteger(v)||(v as number)<min||(v as number)>max)throw new DomainError('INVALID_AMOUNT','Use a whole amount within the displayed limits.',400);return v as number;};
const idFor=(key:string)=>createHash('sha256').update(key).digest('hex').slice(0,24);
export function companyPermission(state:State,actor:string,id:string,operation:'manage'|'inventory'|'hire'|'govern',now:number){
 const company=getCommerce(state).companies[id];if(!company||company.status==='closed')throw new DomainError('COMPANY_NOT_FOUND','This company is unavailable.',404);
 const role=company.members[actor],allowed=operation==='govern'?['founder','cofounder','ceo']:['founder','cofounder','ceo','manager'];
 if(!allowed.includes(role)&&!(company.actingManager===actor&&operation!=='govern'))throw new DomainError('COMPANY_PERMISSION','Your company role does not permit this action.',403);
 company.lastActive[actor]=now;return company;
}
export function shippingQuote(state:State,origin:string,destination:string){
 const commerce=getCommerce(state),distance=origin===destination?10:travelQuote(origin,destination).distance,road=commerce.roads[origin+'>'+destination]??100;
 const fuel=Math.ceil(distance*.04*commerce.fuelPrice),wear=Math.ceil(distance*(100-road)*.3),driver=5000,margin=1000;
 return{price:driver+fuel+wear+margin,duration:Math.ceil((15000+distance*100)*(1+(100-road)/100)),distance,road,fuelPrice:commerce.fuelPrice,components:{driver,fuel,wear,margin},explanation:'Driver + distance × fuel consumption × fuel price + road wear + carrier margin. Existing stock keeps its recorded acquisition cost.'};
}
function usedCapacity(state:State,owner:string,region:string,exceptOrder?:string){const m=getCommerce(state);return Object.values(m.batches).filter(b=>b.owner===owner&&b.region===region).reduce((n,b)=>n+b.quantity,0)+Object.values(m.listings).filter(l=>l.status==='open'&&m.batches[l.batch].owner===owner&&m.batches[l.batch].region===region).reduce((n,l)=>n+l.remaining,0)+Object.values(m.production).filter(p=>p.status==='running'&&'company:'+p.company===owner&&m.companies[p.company].region===region).reduce((n,p)=>n+p.quantity,0)+Object.values(m.orders).filter(o=>o.id!==exceptOrder&&!['accepted','cancelled','refunded'].includes(o.status)&&((owner==='citizen:'+o.buyer&&o.destination===region)||(owner==='company:'+o.company&&o.origin===region&&['funded','picked','carrier-assigned'].includes(o.status)))).reduce((n,o)=>n+o.quantity,0);}
function capacity(state:State,owner:string,region:string,quantity:number,exceptOrder?:string){const m=getCommerce(state),max=m.warehouse[owner+':'+region]??(owner.startsWith('citizen:')?200:1000);if(usedCapacity(state,owner,region,exceptOrder)+quantity>max)throw new DomainError('WAREHOUSE_FULL','This location has insufficient available warehouse space.');}
function batch(state:State,id:string,owner:string,region:string,goods:string,quantity:number,cost:number,source:string,now:number,sourceAccount='system:source:'+source){const product=GOODS.find(g=>g.id===goods)!;getCommerce(state).batches[id]={id,owner,region,goods,quantity,unitCost:Math.ceil(cost/quantity),createdAt:now,expiresAt:now+product.shelfLife,source,quality:100,version:1};stockPost(state,{id:'create:'+id,goods,at:now,reason:'Recorded stock source or custody transfer',entries:[{account:sourceAccount,quantity:-quantity},{account:'batch:'+id,quantity}]});}
export function consumeSupply(state:State,owner:string,region:string,goods:string,quantity:number,now:number,key:string,destinationAccount='system:production-input',reason='Verified recipe input'){const items=Object.values(getCommerce(state).batches).filter(b=>b.owner===owner&&b.region===region&&b.goods===goods&&b.expiresAt>now&&b.quality>0).sort((a,b)=>a.expiresAt-b.expiresAt);if(items.reduce((n,b)=>n+b.quantity,0)<quantity)throw new DomainError('INPUTS_REQUIRED','Obtain the actual recipe inputs at this location first.');let cost=0;for(const b of items){const take=Math.min(b.quantity,quantity);b.quantity-=take;b.version++;stockPost(state,{id:'consume:'+key+':'+b.id,goods,at:now,reason,entries:[{account:'batch:'+b.id,quantity:-take},{account:destinationAccount,quantity:take}]});quantity-=take;cost+=take*b.unitCost;if(!quantity)break;}return cost;}
export function commerceCommand(state:State,actor:string,command:Command,now:number,key:string):Record<string,unknown>|undefined{
 const types=['RegisterCompany','FundCompany','InviteCompanyRole','AcceptCompanyRole','ReviewCompanyContinuity','BuyNPCSupply','ExpandWarehouse','StartProduction','FinishProduction','ListGoods','CancelListing','QuoteOrder','FundOrder','AdvanceOrder','AcceptOrder','CancelOrder','DisputeOrder','ReviewService','PayDividend','RefundDamagedOrder','DisposeExpiredStock','RequestFoodAssistance','EatStoredFood'];if(!types.includes(command.type))return;
 const citizen=state.citizens[actor];if(!citizen)throw new DomainError('CITIZEN_REQUIRED','Create your citizen first.');const m=getCommerce(state),p=command.payload,pos=positionFor(state,citizen,now);
 if(command.type==='RequestFoodAssistance'){
  const day='food-help:'+actor+':'+Math.floor(now/DAY),used=state.npcSpend[day]??0;if(used>=2)throw new DomainError('ASSISTANCE_LIMIT','Two protective meals per day are available.');if(now>=citizen.protectionEndsAt&&(state.balances['citizen:'+actor]??0)>=5000)throw new DomainError('ASSISTANCE_ELIGIBILITY','This protective programme is for new citizens and those without basic meal funds.');consumeNpcMeal(state,actor,now,key,true);state.npcSpend[day]=used+1;citizenLife(state,citizen,now);activeNeeds(citizen,now);citizen.life!.needs.hunger=Math.min(100,citizen.life!.needs.hunger+35);return{message:'One capped protective meal provided. No cash reward was issued.'};
 }
 if(command.type==='EatStoredFood'){
  consumeSupply(state,'citizen:'+actor,pos.region,'food',1,now,key);citizenLife(state,citizen,now);activeNeeds(citizen,now);citizen.life!.needs.hunger=Math.min(100,citizen.life!.needs.hunger+35);return{message:'One available local food unit was consumed.'};
 }
 if(command.type==='DisposeExpiredStock'){
  const b=m.batches[String(p.batchId)],company=p.companyId?companyPermission(state,actor,String(p.companyId),'inventory',now):null,owner=company?'company:'+company.id:'citizen:'+actor;
  if(!b||b.owner!==owner||b.expiresAt>now||!b.quantity)throw new DomainError('DISPOSAL_UNAVAILABLE','Choose your expired available stock.');const quantity=b.quantity;stockPost(state,{id:'dispose:'+b.id,goods:b.goods,at:now,reason:'Expired available stock',entries:[{account:'batch:'+b.id,quantity:-quantity},{account:'system:expired-stock',quantity}]});b.quantity=0;b.quality=0;b.version++;return{batchId:b.id,quantity,message:'Expired available stock disposed with an audit record.'};
 }
 if(command.type==='RegisterCompany'){
  if(!hasLicence(state,actor,'business',now))throw new DomainError('BUSINESS_LICENCE_REQUIRED','Complete business training and obtain a current game licence.');const name=typeof p.name==='string'?p.name.trim():'';if(name.length<2||name.length>60||!SECTORS.includes(String(p.sector)))throw new DomainError('INVALID_COMPANY','Use a name and listed sector.',400);
  const capital=integer(p.capital,100000),id='company_'+idFor(key),fee=10000;post(state,key,now,'Company registration and capital',[{account:'citizen:'+actor,amount:-(capital+fee)},{account:'company:'+id,amount:capital},{account:'treasury:state:'+pos.region,amount:fee}]);m.companies[id]={id,name,sector:String(p.sector),region:pos.region,members:{[actor]:'founder'},shares:{[actor]:100000},lastActive:{[actor]:now},status:'active',actingManager:null,version:1};return{companyId:id,message:'Company registered with its own account and 100,000 issued shares. Job roles confer no shares.'};
 }
 if(command.type==='FundCompany'){
  const company=m.companies[String(p.companyId)];if(!company||company.status==='closed')throw new DomainError('COMPANY_NOT_FOUND','Choose an active company.',404);if(p.acceptGift!==true)throw new DomainError('TERMS_REQUIRED','This capital contribution is a gift and grants no shares.');const value=integer(p.amount);post(state,key,now,'Company capital contribution',[{account:'citizen:'+actor,amount:-value},{account:'company:'+company.id,amount:value}]);company.version++;return{amount:value,message:'Contribution recorded in the company account; ownership is unchanged.'};
 }
 if(command.type==='AcceptCompanyRole'){
  const invite=m.invites[String(p.invitationId)];if(!invite||invite.recipient!==actor||invite.status!=='pending'||invite.expiresAt<=now)throw new DomainError('INVITATION_CLOSED','This role invitation is unavailable.');if(state.life?.blocks[actor]?.includes(invite.sender)||state.life?.blocks[invite.sender]?.includes(actor))throw new DomainError('CONTACT_BLOCKED','This invitation cannot be accepted.',403);if(p.consent!==true)throw new DomainError('CONSENT_REQUIRED','Accept the duties and scoped permissions first.');const company=m.companies[invite.company];if(company.status==='closed')throw new DomainError('COMPANY_CLOSED','This company has closed.');company.members[actor]=invite.role;company.lastActive[actor]=now;company.version++;invite.status='accepted';return{message:'Company role accepted. Your personal assets remain separate.'};
 }
 if(command.type==='ReviewCompanyContinuity'){
  const company=m.companies[String(p.companyId)];if(!company||!company.members[actor])throw new DomainError('COMPANY_PERMISSION','Only a member can review continuity.',403);const controllers=Object.keys(company.members).filter(a=>['founder','cofounder','ceo'].includes(company.members[a]));const absent=controllers.every(a=>now-(company.lastActive[a]??0)>=7*DAY);
  if(absent){const candidates=Object.keys(company.members).filter(a=>a!==actor?now-(company.lastActive[a]??0)<7*DAY:true);company.actingManager=candidates.sort()[0]??null;company.version++;}return{actingManager:company.actingManager,notice:controllers.every(a=>now-(company.lastActive[a]??0)>=3*DAY),message:absent?'Bounded acting management recorded; ownership and secured obligations persist.':'NPC carriers and already funded obligations remain available.'};
 }
 if(command.type==='BuyNPCSupply'){
  const goods=GOODS.find(g=>g.id===p.goodsId);if(!goods||['devices','tourism'].includes(goods.id))throw new DomainError('INVALID_GOODS','Choose the essential NPC catalogue.',400);const quantity=integer(p.quantity,1,100),company=p.companyId?companyPermission(state,actor,String(p.companyId),'inventory',now):null,owner=company?'company:'+company.id:'citizen:'+actor,region=company?.region??pos.region;
  const unitPrice=goods.id==='fuel'?m.fuelPrice:goods.price;if(p.acceptedUnitPrice!==unitPrice)throw new DomainError('QUOTE_CHANGED','Review the current unit price.');const stockKey=region+':'+Math.floor(now/DAY)+':'+goods.id,remaining=m.npcStock[stockKey]??10000;if(quantity>remaining)throw new DomainError('NPC_STOCK_LIMIT','The period’s fallback stock is exhausted.');capacity(state,owner,region,quantity);const cost=quantity*unitPrice;
  post(state,key,now,'Budgeted NPC essential supply',[{account:owner,amount:-cost},{account:'system:npc-supply-provider',amount:cost}]);m.npcStock[stockKey]=remaining-quantity;const id='batch_'+idFor(key);batch(state,id,owner,region,goods.id,quantity,cost,'npc-fallback:'+stockKey,now);return{batchId:id,quantity,cost,message:'Finite NPC stock and the acquisition cost were recorded.'};
 }
 if(command.type==='QuoteOrder'){
  const listing=m.listings[String(p.listingId)];if(!listing||listing.status!=='open')throw new DomainError('LISTING_CLOSED','This offer is unavailable.');const quantity=integer(p.quantity,1,100);if(quantity>listing.remaining)throw new DomainError('OUT_OF_STOCK','There are not enough available units.');const company=m.companies[listing.company],quote=shippingQuote(state,company.region,pos.region),id='quote_'+idFor(key);capacity(state,'citizen:'+actor,pos.region,quantity);m.quotes[id]={id,actor,listing:listing.id,quantity,price:listing.price*quantity,shipping:quote.price,destination:pos.region,duration:quote.duration,expiresAt:now+30000,status:'quoted'};return{quoteId:id,total:listing.price*quantity+quote.price,...quote,message:'Quote valid for 30 seconds. Goods unlock on acceptance; after verified delivery, the seller may settle after a 24-hour review window.'};
 }
 if(command.type==='FundOrder'){
  const quote=m.quotes[String(p.quoteId)];if(!quote||quote.actor!==actor||quote.status!=='quoted'||quote.expiresAt<=now)throw new DomainError('QUOTE_EXPIRED','Request a fresh quote.');if(p.acceptedTotal!==quote.price+quote.shipping||p.acceptTerms!==true)throw new DomainError('TERMS_REQUIRED','Review the total and settlement terms.');const listing=m.listings[quote.listing];if(listing.status!=='open'||listing.remaining<quote.quantity)throw new DomainError('OUT_OF_STOCK','Another buyer reserved the available stock.');capacity(state,'citizen:'+actor,quote.destination,quote.quantity);
  const id='order_'+idFor(key),b=m.batches[listing.batch];if(b.expiresAt<=now)throw new DomainError('STOCK_EXPIRED','This batch is past its shelf life.');post(state,key,now,'Funded goods and carrier escrow',[{account:'citizen:'+actor,amount:-(quote.price+quote.shipping)},{account:'escrow:'+id,amount:quote.price+quote.shipping}]);listing.remaining-=quote.quantity;listing.version++;stockPost(state,{id:'reserve:'+id,goods:b.goods,at:now,reason:'Funded stock reservation',entries:[{account:'listing:'+listing.id,quantity:-quote.quantity},{account:'order:'+id,quantity:quote.quantity}]});quote.status='funded';m.orders[id]={id,quote:quote.id,buyer:actor,company:listing.company,goods:b.goods,quantity:quote.quantity,unitCost:b.unitCost,price:quote.price,shipping:quote.shipping,origin:b.region,destination:quote.destination,status:'funded',lastStageAt:now,arriveAt:now+quote.duration+10000,deliveredAt:null,custody:[{at:now,holder:'warehouse:'+listing.company,stage:'reserved'}],version:1};return{orderId:id,message:'Stock and payment are reserved exactly once.'};
 }
 if(['AdvanceOrder','AcceptOrder','CancelOrder','DisputeOrder','ReviewService','RefundDamagedOrder'].includes(command.type)){
  const order=m.orders[String(p.orderId)],company=order?m.companies[order.company]:null;if(!order||!company)throw new DomainError('ORDER_NOT_FOUND','This order is unavailable.',404);const seller=!!company.members[actor]&&['founder','cofounder','ceo','manager'].includes(company.members[actor]);if(order.buyer!==actor&&!seller)throw new DomainError('ORDER_PERMISSION','Only a party to this order can act.',403);
  if(command.type==='RefundDamagedOrder'){
   const source=m.batches[m.listings[m.quotes[order.quote].listing].batch];
   if(['accepted','cancelled','refunded'].includes(order.status)||now<source.expiresAt)throw new DomainError('DAMAGE_NOT_VERIFIED','A recorded expired batch is required for this automatic refund.');
   post(state,key,now,'Verified spoiled cargo refund',[{account:'escrow:'+order.id,amount:-(order.price+order.shipping)},{account:'citizen:'+order.buyer,amount:order.price+order.shipping}]);stockPost(state,{id:'spoil:'+order.id,goods:order.goods,at:now,reason:'Verified expired cargo',entries:[{account:'order:'+order.id,quantity:-order.quantity},{account:'system:expired-cargo',quantity:order.quantity}]});order.status='refunded';order.version++;order.custody.push({at:now,holder:'quarantine',stage:'expired-and-refunded'});return{message:'Expired goods quarantined and the buyer refunded once; no replacement stock was fabricated.'};
  }
  if(command.type==='CancelOrder'){
   if(order.buyer!==actor||order.status!=='funded')throw new DomainError('ORDER_COMMITTED','Cancellation is available before picking.');const listing=m.listings[m.quotes[order.quote].listing];if(listing.status==='open'){listing.remaining+=order.quantity;listing.version++;}else{const b=m.batches[listing.batch];b.quantity+=order.quantity;b.version++;}stockPost(state,{id:'cancel:'+order.id,goods:order.goods,at:now,reason:'Returned unpicked stock',entries:[{account:'order:'+order.id,quantity:-order.quantity},{account:listing.status==='open'?'listing:'+listing.id:'batch:'+listing.batch,quantity:order.quantity}]});post(state,key,now,'Unpicked order refund',[{account:'escrow:'+order.id,amount:-(order.price+order.shipping)},{account:'citizen:'+actor,amount:order.price+order.shipping}]);order.status='cancelled';order.version++;return{message:'Unpicked goods and payment returned.'};
  }
  if(command.type==='DisputeOrder'){if(order.buyer!==actor||order.status!=='delivered'||now-(order.deliveredAt??now)>DAY)throw new DomainError('DISPUTE_WINDOW','The delivery dispute window is unavailable.');const reason=typeof p.reason==='string'?p.reason.trim():'';if(reason.length<10||reason.length>1000)throw new DomainError('REASON_REQUIRED','Explain the dispute in 10 to 1,000 characters.',400);order.status='disputed';order.version++;m.risk.push({id:'risk_'+idFor(key),reason,references:[order.id],at:now});return{message:'Payment and goods remain reserved for independent review.'};}
  if(command.type==='AdvanceOrder'){
   const source=m.batches[m.listings[m.quotes[order.quote].listing].batch];if(!['accepted','cancelled','refunded','disputed','damaged'].includes(order.status)&&now>=source.expiresAt){order.status='damaged';order.version++;order.custody.push({at:now,holder:'quarantine',stage:'expired'});return{message:'The cargo expired. A verified refund is available.'};}
   const stages=['funded','picked','carrier-assigned','dispatched','in-transit','delivered'] as const,step=stages.indexOf(order.status as typeof stages[number]);if(step<0||step>=stages.length-1)throw new DomainError('ORDER_SETTLED','This order cannot advance.');if(now-order.lastStageAt<2000||(order.status==='in-transit'&&now<order.arriveAt))throw new DomainError('SHIPMENT_PENDING','The carrier stage or route time is still pending.');order.status=stages[step+1];order.lastStageAt=now;order.version++;order.custody.push({at:now,holder:order.status==='delivered'?'destination:'+order.destination:'npc-carrier',stage:order.status});if(order.status==='delivered')order.deliveredAt=now;return{stage:order.status,message:'Verified NPC custody advanced without changing the goods quantity.'};
  }
  if(command.type==='AcceptOrder'){
   if(order.status!=='delivered'||(order.buyer!==actor&&now-(order.deliveredAt??now)<DAY))throw new DomainError('ACCEPTANCE_REQUIRED','Acceptance requires verified delivery and buyer consent or the disclosed review timeout.');if(now>=m.batches[m.listings[m.quotes[order.quote].listing].batch].expiresAt)throw new DomainError('STOCK_EXPIRED','The cargo expired. Request its verified refund.');capacity(state,'citizen:'+order.buyer,order.destination,order.quantity,order.id);const tax=Math.floor(order.price*250/10000);
   post(state,key,now,'Accepted goods, tax and carrier settlement',[{account:'escrow:'+order.id,amount:-(order.price+order.shipping)},{account:'company:'+company.id,amount:order.price-tax},{account:'treasury:state:'+company.region,amount:tax},{account:'system:npc-carrier',amount:order.shipping}]);batch(state,'delivered_'+order.id,'citizen:'+order.buyer,order.destination,order.goods,order.quantity,order.price+order.shipping,order.id,now,'order:'+order.id);m.batches['delivered_'+order.id].expiresAt=m.batches[m.listings[m.quotes[order.quote].listing].batch].expiresAt;order.status='accepted';order.version++;return{message:'Goods ownership, seller proceeds, carrier fee and state tax settled once.'};
  }
  if(order.status!=='accepted'||order.buyer!==actor||company.members[actor])throw new DomainError('REVIEW_INELIGIBLE','Only an independent buyer of a completed service may review.');const score=integer(p.score,1,5),text=typeof p.text==='string'?p.text.trim():'';if(text.length>500)throw new DomainError('REVIEW_TOO_LONG','Use at most 500 characters.',400);const id='review_'+order.id,old=m.reviews[id];if(old&&now-old.at>7*DAY)throw new DomainError('REVIEW_CLOSED','The seven-day review edit window has closed.');m.reviews[id]={id,order:order.id,actor,company:company.id,score,text,at:old?.at??now,editedAt:old?now:null};if(Object.values(m.reviews).filter(r=>r.actor===actor&&r.company===company.id).length>=3&&!m.risk.some(r=>r.reason==='Repeated related reviews'&&r.references.includes(company.id)))m.risk.push({id:'risk_'+idFor(key),reason:'Repeated related reviews',references:[company.id,order.id],at:now});return{message:'One verified review record stored; edits preserve the original transaction reference.'};
 }
 const company=companyPermission(state,actor,String(p.companyId),['InviteCompanyRole','PayDividend'].includes(command.type)?'govern':'inventory',now),owner='company:'+company.id;
 if(command.type==='InviteCompanyRole'){
  const recipient=Object.values(state.citizens).find(c=>c.id===p.citizenId),role=String(p.role);if(!recipient||!['cofounder','ceo','manager'].includes(role)||recipient.actorId===actor)throw new DomainError('INVALID_ROLE','Choose a citizen and listed company role.',400);const id='company_invite_'+idFor(key);if(state.life?.blocks[actor]?.includes(recipient.actorId)||state.life?.blocks[recipient.actorId]?.includes(actor))throw new DomainError('CONTACT_BLOCKED','This role invitation cannot be sent.',403);m.invites[id]={id,company:company.id,sender:actor,recipient:recipient.actorId,role,expiresAt:now+7*DAY,status:'pending'};return{invitationId:id,message:'Role invitation sent. No shares transfer through this invitation.'};
 }
 if(command.type==='ExpandWarehouse'){
  const units=integer(p.units,100,1000),fee=units*100;if(p.acceptedFee!==fee)throw new DomainError('QUOTE_CHANGED','Review the storage expansion price.');post(state,key,now,'Warehouse capacity expansion',[{account:owner,amount:-fee},{account:'system:warehouse-provider',amount:fee}]);const location=owner+':'+company.region;m.warehouse[location]=(m.warehouse[location]??1000)+units;return{capacity:m.warehouse[location],message:'Paid storage capacity expanded.'};
 }
 if(command.type==='StartProduction'){
  const recipe=RECIPES.find(r=>r.id===p.recipeId);if(!recipe||recipe.sector!==company.sector)throw new DomainError('RECIPE_PERMISSION','Use a recipe for this company’s sector.');if(company.status!=='active')throw new DomainError('COMPANY_DISTRESSED','Resolve the company’s distress before new production.');if(Object.values(m.production).some(r=>r.company===company.id&&r.status==='running'))throw new DomainError('PRODUCTION_BUSY','Complete the running batch first.');const inputCost=Object.entries(recipe.inputs).reduce((n,[goods,quantity])=>n+consumeSupply(state,owner,company.region,goods,quantity!,now,key),0);
  if(recipe.node){const node=company.region+':'+recipe.node+':'+Math.floor(now/DAY),remaining=m.nodes[node]??2000;if(remaining<recipe.quantity)throw new DomainError('NODE_DEPLETED','This resource node’s period capacity is depleted.');m.nodes[node]=remaining-recipe.quantity;}capacity(state,owner,company.region,recipe.quantity);post(state,key,now,'Verified NPC production labour and power',[{account:owner,amount:-recipe.labour},{account:'system:production-labour',amount:recipe.labour}]);const id='production_'+idFor(key);m.production[id]={id,company:company.id,recipe:recipe.id,quantity:recipe.quantity,cost:inputCost+recipe.labour,startedAt:now,readyAt:now+60000,status:'running',version:1};return{productionId:id,message:'Actual inputs consumed, labour paid and finite production capacity committed.'};
 }
 if(command.type==='FinishProduction'){
  const production=m.production[String(p.productionId)];if(!production||production.company!==company.id||production.status!=='running')throw new DomainError('PRODUCTION_NOT_FOUND','This production batch is unavailable.');if(now<production.readyAt)throw new DomainError('PRODUCTION_PENDING','The batch is still processing.');const recipe=RECIPES.find(r=>r.id===production.recipe)!;production.status='completed';production.version++;batch(state,'output_'+production.id,owner,company.region,recipe.output,production.quantity,production.cost,production.id,now);return{batchId:'output_'+production.id,quantity:production.quantity,message:'One output batch was recorded from the consumed recipe inputs.'};
 }
 if(command.type==='ListGoods'){
  const b=m.batches[String(p.batchId)];if(!b||b.owner!==owner||b.region!==company.region||b.expiresAt<=now)throw new DomainError('STOCK_PERMISSION','Choose this company’s current local stock.');const quantity=integer(p.quantity,1,b.quantity),price=integer(p.price,1,10000000),id='listing_'+idFor(key);b.quantity-=quantity;b.version++;stockPost(state,{id:'list:'+id,goods:b.goods,at:now,reason:'Reserved advertised stock',entries:[{account:'batch:'+b.id,quantity:-quantity},{account:'listing:'+id,quantity}]});m.listings[id]={id,batch:b.id,company:company.id,quantity,remaining:quantity,price,status:'open',version:1};return{listingId:id,message:'The advertised units are reserved from the actual batch.'};
 }
 if(command.type==='CancelListing'){
  const listing=m.listings[String(p.listingId)];if(!listing||listing.company!==company.id||listing.status!=='open')throw new DomainError('LISTING_CLOSED','This offer is unavailable.');const b=m.batches[listing.batch];b.quantity+=listing.remaining;b.version++;stockPost(state,{id:'unlist:'+listing.id,goods:b.goods,at:now,reason:'Returned unsold stock',entries:[{account:'listing:'+listing.id,quantity:-listing.remaining},{account:'batch:'+b.id,quantity:listing.remaining}]});listing.remaining=0;listing.status='closed';listing.version++;return{message:'Unsold reserved units returned to their original batch.'};
 }
 if(command.type==='PayDividend'){
  if(Object.values(company.members).filter(r=>['founder','cofounder','ceo'].includes(r)).length>1)throw new DomainError('MULTI_APPROVAL_REQUIRED','Multiple controllers require a recorded corporate approval before protected distributions.');if(company.status!=='active')throw new DomainError('COMPANY_DISTRESSED','Protected payouts require an active company.');const value=integer(p.amount);if(p.acceptTerms!==true)throw new DomainError('TERMS_REQUIRED','Confirm the proportional distribution.');if(Object.values(company.shares).reduce((n,units)=>n+units,0)!==issuedShares(company))throw new Error('Invalid cap table');post(state,key,now,'Proportional company dividend',[{account:owner,amount:-value},...proportionalDividend(company,value)]);company.version++;return{amount:value,message:'Dividends paid from existing company funds according to issued shares.'};
 }
 throw new DomainError('UNKNOWN_COMMAND','Unknown commerce action.',400);
}
export function commerceView(state:State,actor:string,now:number){
 const m=state.commerce;if(!m)return{goods:GOODS,sectors:SECTORS,recipes:RECIPES,companies:[],inventory:[],listings:[],orders:[],quotes:[],production:[],invitations:[],reviews:[]};const owned=Object.values(m.companies).filter(c=>c.members[actor]||c.shares[actor]),ids=new Set(owned.map(c=>c.id));
 return{goods:GOODS.map(g=>({...g,price:g.id==='fuel'?m.fuelPrice:g.price})),sectors:SECTORS,recipes:RECIPES,companies:owned.map(c=>({...c,balance:state.balances['company:'+c.id]??0,role:c.members[actor],shareUnits:c.shares[actor]??0,members:Object.entries(c.members).map(([a,role])=>({citizenId:state.citizens[a]?.id,name:state.citizens[a]?.name,role})),shares:Object.entries(c.shares).map(([a,units])=>({citizenId:state.citizens[a]?.id,units})),lastActive:undefined})),inventory:Object.values(m.batches).filter(b=>b.owner==='citizen:'+actor||ids.has(b.owner.slice(8))),listings:Object.values(m.listings).filter(l=>l.status==='open').map(l=>({...l,companyName:m.companies[l.company].name,region:m.batches[l.batch].region,goods:m.batches[l.batch].goods})),orders:Object.values(m.orders).filter(o=>o.buyer===actor||ids.has(o.company)).map(o=>({...o,buyer:state.citizens[o.buyer]?.id})),quotes:Object.values(m.quotes).filter(q=>q.actor===actor),production:Object.values(m.production).filter(p=>ids.has(p.company)),invitations:Object.values(m.invites).filter(i=>i.recipient===actor&&i.status==='pending'&&i.expiresAt>now),reviews:Object.values(m.reviews).map(r=>({...r,actor:state.citizens[r.actor]?.id}))};
}
