import {createHash} from 'node:crypto';
import {DAY,DomainError,post,LESSONS} from './domain.ts';
import type {State,Command,Citizen} from './domain.ts';
import {CURRICULUM_VERSION,foundationExam} from './curriculum.ts';
import {positionFor} from './world.ts';
import {companyPermission,getCommerce} from './commerce.ts';
export const TRACKS=['ordinary','medicine','police','military','business','politics','technical','creative'];
const exercise=(prompt:string,choices:string[],correct:number)=>({prompt,choices,correct});
export const PRACTICALS=[
 [],
 [exercise('A stranger requests your account key. How do you respond?',['Send it','Keep it private, block the training sender','Give them household ownership'],1),exercise('Prepare a report of the training message.',['Include the message reference and reason','Invent a conviction','Publish private account details'],0)],
 [exercise('Your payslip records ₦250 from reserved wages. What is available?',['The settled amount, after other reservations','All escrow in the world','Tomorrow’s wages too'],0),exercise('A contract promises ₦250 but reserves nothing.',['Accept because the owner is wealthy','Check secured pay, duties and cancellation terms','Hand over your password'],1)],
 [exercise('Sample notice: NPC officer, case DEMO-1, hearing tomorrow, right to review. Your response?',['Inspect grounds and request the hearing','Treat arrest as conviction','Pay real money'],0),exercise('The sample file contains a disputed witness statement.',['Delete it','Ask the court to assess it and retain appeal rights','Immediately punish the witness'],1)],
 [exercise('A wealthy friend offers a medicine job before your licence.',['Accept clinical powers immediately','Complete the required study, exam, practice and licence','Buy a premium badge'],1)]
];
const moduleTask=(name:string)=>[
 exercise('Review the official '+name+' curriculum. Who controls certification?',['The authoritative examination rules','A private tutor’s promise','A premium purchase'],0),
 exercise('An instructor is absent. What keeps this course available?',['Approved NPC teaching or transfer','Buying a vote','Sharing your login'],0),
 exercise('Before acting professionally, what must you check?',['Current licence, scope and supervised practice requirements','Family wealth','A costume'],0)
];
export const COURSES=[
 {id:'secondary',name:'Secondary foundations',track:'secondary',prerequisite:null,fee:50000,practice:0,licence:false},
 {id:'vocational',name:'Vocational foundations',track:'vocational',prerequisite:null,fee:100000,practice:0,licence:false},
 {id:'medicine',name:'Health and clinical programme',track:'medicine',prerequisite:'secondary',fee:200000,practice:3,licence:true},
 {id:'police',name:'Police academy',track:'police',prerequisite:'secondary',fee:150000,practice:2,licence:true},
 {id:'military',name:'Military academy',track:'military',prerequisite:'secondary',fee:150000,practice:2,licence:true},
 {id:'business',name:'Business fundamentals',track:'business',prerequisite:'secondary',fee:100000,practice:0,licence:true},
 {id:'politics',name:'Civic leadership',track:'politics',prerequisite:'secondary',fee:100000,practice:0,licence:true},
 {id:'technical',name:'Technical trades and apprenticeship',track:'technical',prerequisite:'vocational',fee:125000,practice:3,licence:true},
 {id:'creative',name:'Creative and media programme',track:'creative',prerequisite:'vocational',fee:75000,practice:1,licence:true},
 {id:'finance',name:'Financial institution management',track:'finance',prerequisite:'business',fee:150000,practice:2,licence:true},
 {id:'driving',name:'Driving and road-safety programme',track:'driving',prerequisite:null,fee:25000,practice:2,licence:true},
 {id:'insurance',name:'Insurance and claims practice',track:'insurance',prerequisite:'finance',fee:150000,practice:2,licence:true}
].map(c=>({...c,tasks:moduleTask(c.name),duration:60000,version:'courses-1.0',exam:[
 exercise('You have completed study. What gives you professional authority?',['A passing official exam and required practice/licence','A private message','A cosmetic'],0),
 exercise('What should a paid school disclose?',['Fees, curriculum, completion and refund terms','Only a promised salary','Other students’ passwords'],0),
 exercise('Can experience replace an official qualification?',['No; it can supplement eligibility','Yes if you know a wealthy citizen','Yes if you change the clock'],0),
 exercise('Who can spend a restricted tuition award?',['The approved provider for the named course','Anyone with the award ID','An election campaign'],0),
 exercise('What happens if an instructor leaves?',['NPC cover or approved transfer preserves progress','The official certificate is sold to someone else','Your personal wallet is confiscated'],0)
 ]}));
type Foundation={practicals:Record<string,number>;goal:string|null};
type Enrolment={id:string;actor:string;course:string;startedAt:number;lastStepAt:number;steps:number;attempts:number;practice:number;lastPracticeAt:number;status:'studying'|'exam-passed'|'completed'|'cancelled';tuition:number;scholarshipId:string|null;certificate:string|null;version:number;schoolId?:string|null};
type Scholarship={id:string;donor:string;recipient:string;course:string;amount:number;expiresAt:number;status:'offered'|'used'|'refunded';enrolmentId:string|null};
type Licence={id:string;actor:string;track:string;issuedAt:number;expiresAt:number;enrolmentId:string;version:number};
type School={id:string;company:string;courses:string[];teachers:string[];capacity:number;status:'open'|'closed';curriculumVersion:string;version:number};
type Mentorship={id:string;student:string;mentor:string;enrolment:string;expiresAt:number;status:'invited'|'accepted'|'declined'|'ended';version:number};
type PracticeSession={id:string;mentorship:string;student:string;mentor:string;enrolment:string;at:number;status:'offered'|'confirmed'|'cancelled';version:number};
export type EducationState={foundation:Record<string,Foundation>;enrolments:Record<string,Enrolment>;scholarships:Record<string,Scholarship>;licences:Record<string,Licence>;schools?:Record<string,School>;mentorships?:Record<string,Mentorship>;practiceSessions?:Record<string,PracticeSession>};
const getEducation=(state:State)=>state.education??={foundation:{},enrolments:{},scholarships:{},licences:{}};
const person=(state:State,actor:string)=>{const c=state.citizens[actor];if(!c)throw new DomainError('CITIZEN_REQUIRED','Create your citizen first.');return c;};
const record=(state:State,actor:string)=>getEducation(state).foundation[actor]??={practicals:{},goal:null};
function qualifiedTeacher(state:State,actor:string,courseId:string,now:number){const course=COURSES.find(c=>c.id===courseId);return!!course&&!!state.citizens[actor]?.certificate&&(!course.licence||hasLicence(state,actor,course.track,now));}
const blocked=(state:State,a:string,b:string)=>state.life?.blocks[a]?.includes(b)||state.life?.blocks[b]?.includes(a);
function unlock(c:Citizen,day:number,now:number){if(!Number.isInteger(day)||day<1||day>5)throw new DomainError('INVALID_LESSON','Choose lesson 1 to 5.',400);if(now<c.enrolledAt+(day-1)*DAY)throw new DomainError('LESSON_LOCKED','This foundation module has not unlocked yet.');if(day>1&&!c.completedLessons.includes(day-1))throw new DomainError('PREREQUISITE_REQUIRED','Complete the previous module first.');}
function practicalReady(state:State,c:Citizen,now:number,day:number){
 if(day===1)return positionFor(state,c,now).visited.includes('shelter')&&c.lastShiftAt!==null&&Object.values(state.commands).some(x=>x.receipt.actorId===c.actorId&&x.receipt.type==='BuyBasicMeal');
 const progress=record(state,c.actorId);return(progress.practicals[String(day)]??0)===PRACTICALS[day-1].length&&(day!==2||Object.values(state.commands).some(x=>x.receipt.actorId===c.actorId&&x.receipt.type==='SetPrivacy'))&&(day!==5||!!progress.goal);
}
export function hasLicence(state:State,actor:string,track:string,now:number){return Object.values(state.education?.licences??{}).some(l=>l.actor===actor&&l.track===track&&l.expiresAt>now);}
export function educationCommand(state:State,actor:string,command:Command,now:number,key:string):Record<string,unknown>|undefined{
 const types=['FoundationPractice','ChooseGoal','CompleteLesson','SubmitExam','OfferScholarship','RefundScholarship','EnrollCourse','StudyCourse','TakeCourseExam','SupervisedPractice','IssueLicence','RenewLicence','CancelCourse','OpenSchool','CloseSchool','InviteMentor','AcceptMentorship','DeclineMentorship','OfferMentoredPractice','LeaveMentorship'];if(!types.includes(command.type))return;
 const c=person(state,actor),e=getEducation(state),p=command.payload,f=record(state,actor);
 if(command.type==='LeaveMentorship'){
  const mentorship=e.mentorships?.[String(p.mentorshipId)];if(!mentorship||![mentorship.student,mentorship.mentor].includes(actor)||mentorship.status==='ended')throw new DomainError('MENTORSHIP_UNAVAILABLE','This relationship is unavailable.');mentorship.status='ended';mentorship.version++;for(const session of Object.values(e.practiceSessions??{}))if(session.mentorship===mentorship.id&&session.status==='offered'){session.status='cancelled';session.version++;}return{message:'Mentoring ended. No new delegated practice or progress access remains; NPC completion stays available.'};
 }
 if(command.type==='OpenSchool'){
  const company=companyPermission(state,actor,String(p.companyId),'govern',now);if(company.sector!=='education')throw new DomainError('EDUCATION_SECTOR','A registered education company is required.');const courses=p.courseIds;if(!Array.isArray(courses)||!courses.length||courses.length>COURSES.length||new Set(courses).size!==courses.length||courses.some(id=>!qualifiedTeacher(state,actor,String(id),now)))throw new DomainError('TEACHER_QUALIFICATION','Choose official courses for which you hold current teaching eligibility.');
  e.schools??={};if(Object.values(e.schools).some(s=>s.company===company.id))throw new DomainError('SCHOOL_EXISTS','This company already registered a school.');const id='school_'+key;e.schools[id]={id,company:company.id,courses:courses as string[],teachers:[actor],capacity:20,status:'open',curriculumVersion:'courses-1.0',version:1};return{schoolId:id,message:'Official courses opened with finite places. NPC instruction preserves progress, and certificates still require authoritative exams and practice.'};
 }
 if(command.type==='CloseSchool'){
  const school=e.schools?.[String(p.schoolId)];if(!school)throw new DomainError('SCHOOL_NOT_FOUND','This school is unavailable.',404);companyPermission(state,actor,school.company,'govern',now);if(school.status==='closed')throw new DomainError('SCHOOL_CLOSED','This school is already closed.');school.status='closed';school.version++;return{message:'New enrolments closed. Existing reserved tuition, NPC teaching, exams and refunds remain available.'};
 }
 if(command.type==='InviteMentor'){
  const enrolment=e.enrolments[String(p.enrolmentId)],mentor=Object.values(state.citizens).find(c=>c.id===p.citizenId);if(!enrolment||enrolment.actor!==actor||!mentor||mentor.actorId===actor||!qualifiedTeacher(state,mentor.actorId,enrolment.course,now))throw new DomainError('MENTOR_ELIGIBILITY','Choose a qualified citizen for your own course.');if(blocked(state,actor,mentor.actorId))throw new DomainError('CONTACT_BLOCKED','This mentoring invitation cannot be sent.',403);e.mentorships??={};const id='mentorship_'+key;e.mentorships[id]={id,student:actor,mentor:mentor.actorId,enrolment:enrolment.id,expiresAt:now+7*DAY,status:'invited',version:1};return{mentorshipId:id,message:'Invitation sent. It shares only this course’s practice progress, grants no certificate power and transfers no money.'};
 }
 if(['AcceptMentorship','DeclineMentorship'].includes(command.type)){
  const mentorship=e.mentorships?.[String(p.mentorshipId)];if(!mentorship||mentorship.mentor!==actor||mentorship.status!=='invited'||mentorship.expiresAt<=now)throw new DomainError('INVITATION_CLOSED','This mentoring invitation is unavailable.');if(command.type==='AcceptMentorship'&&(p.consent!==true||blocked(state,actor,mentorship.student)))throw new DomainError('CONSENT_REQUIRED','Accept the scoped teaching terms and contact permissions.');mentorship.status=command.type==='AcceptMentorship'?'accepted':'declined';mentorship.version++;return{message:'Mentoring decision recorded; no private financial or message access was granted.'};
 }
 if(command.type==='OfferMentoredPractice'){
  const mentorship=e.mentorships?.[String(p.mentorshipId)],enrolment=mentorship?e.enrolments[mentorship.enrolment]:null;if(!mentorship||mentorship.mentor!==actor||mentorship.status!=='accepted'||mentorship.expiresAt<=now||!enrolment||enrolment.status!=='exam-passed'||!qualifiedTeacher(state,actor,enrolment.course,now)||blocked(state,actor,mentorship.student))throw new DomainError('MENTOR_PERMISSION','An accepted, current course-specific mentorship is required.',403);if(p.choice!==0)throw new DomainError('PRACTICE_REVIEW','Use the supervisor’s approved game procedure.');e.practiceSessions??={};if(Object.values(e.practiceSessions).some(s=>s.enrolment===enrolment.id&&s.status==='offered'))throw new DomainError('PRACTICE_PENDING','The student must confirm the existing session first.');const id='practice_'+key;e.practiceSessions[id]={id,mentorship:mentorship.id,student:mentorship.student,mentor:actor,enrolment:enrolment.id,at:now,status:'offered',version:1};return{practiceSessionId:id,message:'Verified mentor procedure offered; student confirmation and server eligibility are still required.'};
 }
 if(command.type==='ChooseGoal'){if(!TRACKS.includes(String(p.goal)))throw new DomainError('INVALID_GOAL','Choose a listed life direction.',400);f.goal=String(p.goal);return{goal:f.goal,message:'Your direction is recorded. You can change it without losing credentials.'};}
 if(command.type==='FoundationPractice'){
  const day=Number(p.day);unlock(c,day,now);const tasks=PRACTICALS[day-1],step=f.practicals[String(day)]??0;if(!tasks.length)throw new DomainError('WORLD_TASK_REQUIRED','Visit shelter, purchase a meal and complete paid starter work.');
  if(step>=tasks.length)throw new DomainError('PRACTICE_COMPLETE','The practical activity is already recorded.');if(p.choice!==tasks[step].correct)throw new DomainError('PRACTICE_REVIEW','Review the explanation and try again.');f.practicals[String(day)]=step+1;return{day,step:step+1,message:'The NPC training activity is recorded. Training examples grant no authority over other players.'};
 }
 if(command.type==='CompleteLesson'){
  const day=Number(p.day);unlock(c,day,now);if(!practicalReady(state,c,now,day))throw new DomainError('PRACTICAL_REQUIRED','Finish this module’s practical actions first.');if(!c.completedLessons.includes(day))c.completedLessons.push(day);if(day===5)c.reviewRequired=false;return{day,title:LESSONS[day-1],curriculumVersion:CURRICULUM_VERSION};
 }
 if(command.type==='SubmitExam'){
  if(c.certificate)throw new DomainError('ALREADY_CERTIFIED','Your foundation certificate is already recorded.');if(c.completedLessons.length!==5||now<c.enrolledAt+4*DAY)throw new DomainError('EXAM_LOCKED','Complete all five foundation modules first.');if(c.reviewRequired)throw new DomainError('REVIEW_REQUIRED','Review module five before retaking the exam.');
  const exam=foundationExam(state,actor),answers=p.answers;if(!Array.isArray(answers)||answers.length!==20||answers.some(a=>!Number.isInteger(a)||a<0||a>3))throw new DomainError('INVALID_EXAM','Answer all 20 examination questions.',400);if(p.examId!==exam.id)throw new DomainError('EXAM_CHANGED','Refresh the current exam before submitting.');
  const score=exam.questions.filter((q,i)=>q.correct===answers[i]).length*5,passed=score>=80;c.examAttempts.push({at:now,score,passed});c.reviewRequired=!passed;if(passed)c.certificate={id:'foundation_'+c.id,curriculumVersion:CURRICULUM_VERSION,issuedAt:now};return{score,passed,certificate:c.certificate,review:passed?[]:LESSONS,message:passed?'Foundation certificate recorded.':'Review module five. Your work, shelter and free retake remain available.'};
 }
 if(command.type==='OfferScholarship'){
  const recipient=Object.values(state.citizens).find(x=>x.id===p.citizenId),course=COURSES.find(x=>x.id===p.courseId);if(!recipient||!course)throw new DomainError('INVALID_AWARD','Choose an existing citizen and official course.',400);if(p.acceptedFee!==course.fee)throw new DomainError('QUOTE_CHANGED','Review the restricted tuition amount.');const id='award_'+key;
  post(state,key,now,'Restricted tuition award',[{account:'citizen:'+actor,amount:-course.fee},{account:'scholarship:'+id,amount:course.fee}]);e.scholarships[id]={id,donor:actor,recipient:recipient.actorId,course:course.id,amount:course.fee,expiresAt:now+30*DAY,status:'offered',enrolmentId:null};return{scholarshipId:id,message:'Tuition reserved for this recipient and course. It cannot be withdrawn as personal cash.'};
 }
 if(command.type==='RefundScholarship'){
  const award=e.scholarships[String(p.scholarshipId)];if(!award||award.donor!==actor)throw new DomainError('AWARD_NOT_FOUND','This award is unavailable.',404);if(award.status!=='offered'||now<award.expiresAt)throw new DomainError('AWARD_COMMITTED','Only an expired unused award can be refunded.');post(state,key,now,'Expired tuition award refund',[{account:'scholarship:'+award.id,amount:-award.amount},{account:'citizen:'+actor,amount:award.amount}]);award.status='refunded';return{message:'Unused restricted funds returned to the donor.'};
 }
 if(command.type==='EnrollCourse'){
  const course=COURSES.find(x=>x.id===p.courseId);if(!course)throw new DomainError('INVALID_COURSE','Choose an official course.',400);if(!c.certificate)throw new DomainError('FOUNDATION_REQUIRED','Earn your foundation certificate first.');
  if(course.prerequisite&&!Object.values(e.enrolments).some(x=>x.actor===actor&&x.course===course.prerequisite&&x.status==='completed'))throw new DomainError('COURSE_PREREQUISITE','Complete the prerequisite track first.');
  if(Object.values(e.enrolments).some(x=>x.actor===actor&&x.course===course.id&&x.status!=='cancelled'))throw new DomainError('ALREADY_ENROLLED','This course is already in your education record.');if(p.acceptedFee!==course.fee||p.acceptTerms!==true)throw new DomainError('TERMS_REQUIRED','Review the fee and refund terms before enrolling.');
  const school=p.schoolId?e.schools?.[String(p.schoolId)]:null;if(p.schoolId&&(!school||school.status!=='open'||!school.courses.includes(course.id)||Object.values(e.enrolments).filter(x=>x.schoolId===school.id&&!['completed','cancelled'].includes(x.status)).length>=school.capacity))throw new DomainError('SCHOOL_UNAVAILABLE','This official course has no available place at that school.');if(school&&positionFor(state,c,now).region!==getCommerce(state).companies[school.company].region)throw new DomainError('SCHOOL_LOCATION','Travel to the school’s region before enrolment.');
  const award=p.scholarshipId?e.scholarships[String(p.scholarshipId)]:null;if(p.scholarshipId&&(!award||award.recipient!==actor||award.course!==course.id||award.status!=='offered'||award.expiresAt<=now))throw new DomainError('AWARD_INVALID','This award cannot pay this tuition.');
  const id='course_'+key;post(state,key,now,'Reserved course tuition',[{account:award?'scholarship:'+award.id:'citizen:'+actor,amount:-course.fee},{account:'tuition:'+id,amount:course.fee}]);e.enrolments[id]={id,actor,course:course.id,startedAt:now,lastStepAt:now,steps:0,attempts:0,practice:0,lastPracticeAt:0,status:'studying',tuition:course.fee,scholarshipId:award?.id??null,certificate:null,version:1,schoolId:school?.id??null};if(award){award.status='used';award.enrolmentId=id;}return{enrolmentId:id,message:'Tuition reserved. Cancel before passing the exam for a full refund to the original funding source; NPC instruction stays available.'};
 }
 const enrolment=e.enrolments[String(p.enrolmentId)];
 if(command.type==='RenewLicence'){
  const licence=e.licences[String(p.licenceId)];if(!licence||licence.actor!==actor)throw new DomainError('LICENCE_NOT_FOUND','This licence is unavailable.',404);const course=COURSES.find(x=>x.track===licence.track)!;
  if(now<licence.expiresAt-DAY)throw new DomainError('RENEWAL_EARLY','Renewal opens one day before expiry.');if(p.choice!==0||p.acceptedFee!==Math.ceil(course.fee*.05))throw new DomainError('RENEWAL_REVIEW','Review the continuing-practice rule and renewal fee.');post(state,key,now,'Licence renewal',[{account:'citizen:'+actor,amount:-Math.ceil(course.fee*.05)},{account:'system:licensing-fees',amount:Math.ceil(course.fee*.05)}]);licence.expiresAt=Math.max(now,licence.expiresAt)+30*DAY;licence.version++;return{message:'Your current licence was renewed.',expiresAt:licence.expiresAt};
 }
 if(!enrolment||enrolment.actor!==actor)throw new DomainError('ENROLMENT_NOT_FOUND','This enrolment is unavailable.',404);const course=COURSES.find(x=>x.id===enrolment.course)!;
 if(command.type==='CancelCourse'){
  if(enrolment.status!=='studying')throw new DomainError('COURSE_COMMITTED','This completed examination cannot be cancelled.');const award=enrolment.scholarshipId?e.scholarships[enrolment.scholarshipId]:null;post(state,key,now,'Uncompleted tuition refund',[{account:'tuition:'+enrolment.id,amount:-enrolment.tuition},{account:award?'scholarship:'+award.id:'citizen:'+actor,amount:enrolment.tuition}]);if(award){award.status='offered';award.enrolmentId=null;}enrolment.status='cancelled';enrolment.version++;return{message:'Reserved tuition returned to its original funding source.'};
 }
 if(command.type==='StudyCourse'){
  if(enrolment.status!=='studying'||enrolment.steps>=course.tasks.length)throw new DomainError('STUDY_COMPLETE','Study checks are already complete.');if(now-enrolment.lastStepAt<2000)throw new DomainError('STUDY_COOLDOWN','Review the next activity first.');if(p.choice!==course.tasks[enrolment.steps].correct)throw new DomainError('STUDY_REVIEW','Review this official curriculum activity.');enrolment.steps++;enrolment.lastStepAt=now;enrolment.version++;return{message:'Official course activity recorded.'};
 }
 if(command.type==='TakeCourseExam'){
  if(enrolment.status!=='studying'||enrolment.steps!==course.tasks.length||now<enrolment.startedAt+course.duration)throw new DomainError('COURSE_EXAM_LOCKED','Complete the study and minimum course interval.');const answers=p.answers;if(!Array.isArray(answers)||answers.length!==course.exam.length||answers.some(x=>!Number.isInteger(x)||x<0||x>2))throw new DomainError('INVALID_EXAM','Answer every course exam question.',400);
  const score=course.exam.filter((q,i)=>answers[i]===q.correct).length*20;enrolment.attempts++;enrolment.version++;if(score<80)return{score,passed:false,message:'Free retake available after reviewing the official activities.'};
  const school=enrolment.schoolId?e.schools?.[enrolment.schoolId]:null,officialFee=school?Math.floor(enrolment.tuition*.1):enrolment.tuition;post(state,key,now,'Earned course tuition',[{account:'tuition:'+enrolment.id,amount:-enrolment.tuition},{account:'system:official-education-provider',amount:officialFee},...(school?[{account:'company:'+school.company,amount:enrolment.tuition-officialFee}]:[])]);enrolment.status=course.practice?'exam-passed':'completed';if(!course.practice)enrolment.certificate='qualification_'+createHash('sha256').update(enrolment.id).digest('hex').slice(0,24);return{score,passed:true,message:course.practice?'Exam passed. Complete supervised NPC practice before certification.':'Official qualification recorded.'};
 }
 if(command.type==='SupervisedPractice'){
  if(enrolment.status!=='exam-passed'||now-enrolment.lastPracticeAt<60000)throw new DomainError('PRACTICE_UNAVAILABLE','Practice requires a passed exam and one minute between sessions.');if(p.choice!==0)throw new DomainError('PRACTICE_REVIEW','Use the supervisor’s approved procedure.');
  const session=p.practiceSessionId?e.practiceSessions?.[String(p.practiceSessionId)]:null;
  if(p.practiceSessionId&&(!session||session.student!==actor||session.enrolment!==enrolment.id||session.status!=='offered'||e.mentorships?.[session.mentorship]?.status!=='accepted'||(e.mentorships?.[session.mentorship]?.expiresAt??0)<=now||!qualifiedTeacher(state,session.mentor,enrolment.course,now)||blocked(state,actor,session.mentor)))throw new DomainError('PRACTICE_SESSION_INVALID','A current qualified mentor and your own unconfirmed session are required.');
  if(session){session.status='confirmed';session.version++;}enrolment.practice++;enrolment.lastPracticeAt=now;enrolment.version++;if(enrolment.practice>=course.practice){enrolment.status='completed';enrolment.certificate='qualification_'+createHash('sha256').update(enrolment.id).digest('hex').slice(0,24);}return{sessions:enrolment.practice,message:session?'Qualified mentor practice confirmed by the student and server.':'Verified NPC-supervised practice recorded.'};
 }
 if(enrolment.status!=='completed'||!course.licence)throw new DomainError('QUALIFICATION_REQUIRED','Complete the required qualification and practice.');const id='licence_'+enrolment.id;if(e.licences[id])throw new DomainError('ALREADY_LICENSED','This qualification already has a licence.');e.licences[id]={id,actor,track:course.track,issuedAt:now,expiresAt:now+30*DAY,enrolmentId:enrolment.id,version:1};return{licenceId:id,message:'A scoped game licence is recorded. It grants no real professional credential.'};
}
export function educationView(state:State,actor:string,now:number){
 const c=state.citizens[actor];if(!c)return null;const copy=structuredClone(state),f=record(copy,actor),e=getEducation(copy);
 return{schools:Object.values(e.schools??{}).map(s=>({...s,name:state.commerce?.companies[s.company].name,region:state.commerce?.companies[s.company].region,teachers:s.teachers.map(a=>({citizenId:state.citizens[a]?.id,name:state.citizens[a]?.name})),available:s.capacity-Object.values(e.enrolments).filter(x=>x.schoolId===s.id&&!['completed','cancelled'].includes(x.status)).length})),mentorships:Object.values(e.mentorships??{}).filter(m=>m.student===actor||m.mentor===actor).map(m=>({...m,student:state.citizens[m.student]?.id,mentor:state.citizens[m.mentor]?.id,course:e.enrolments[m.enrolment].course,progress:m.status==='accepted'&&m.expiresAt>now&&!blocked(state,m.student,m.mentor)?e.enrolments[m.enrolment].practice:null,statusOfCourse:m.status==='accepted'&&m.expiresAt>now&&!blocked(state,m.student,m.mentor)?e.enrolments[m.enrolment].status:null})),practiceSessions:Object.values(e.practiceSessions??{}).filter(s=>s.student===actor||s.mentor===actor).map(s=>({...s,student:state.citizens[s.student]?.id,mentor:state.citizens[s.mentor]?.id})),foundation:{...f,practicals:LESSONS.map((title,i)=>{const day=i+1,step=f.practicals[String(day)]??0,current=PRACTICALS[i][step];return{day,title,ready:practicalReady(copy,copy.citizens[actor],now,day),step,total:PRACTICALS[i].length,current:current?{prompt:current.prompt,choices:current.choices}:null};})},tracks:TRACKS,courses:COURSES.map(({tasks,exam,...course})=>({...course,terms:'Full tuition refund before exam pass, returned to the original funding source. Approved NPC instruction remains available.'})),enrolments:Object.values(e.enrolments).filter(x=>x.actor===actor).map(x=>{const course=COURSES.find(c=>c.id===x.course)!,task=course.tasks[x.steps];return{...x,courseName:course.name,practiceRequired:course.practice,task:task?{prompt:task.prompt,choices:task.choices}:null,exam:course.exam.map(({prompt,choices})=>({prompt,choices})),examAt:x.startedAt+course.duration,nextStudyAt:x.lastStepAt+2000,nextPracticeAt:x.lastPracticeAt+60000};}),scholarships:Object.values(e.scholarships).filter(x=>x.recipient===actor||x.donor===actor).map(x=>({...x,recipient:state.citizens[x.recipient]?.id,donor:state.citizens[x.donor]?.id})),licences:Object.values(e.licences).filter(x=>x.actor===actor).map(x=>({...x,current:x.expiresAt>now}))};
}
