import {DomainError,post} from './domain.ts';
import type {State,Command} from './domain.ts';
import {DAY} from './rules.ts';
import {companyPermission,getCommerce} from './commerce.ts';
import {hasLicence} from './education.ts';
import {STARTER_JOBS} from './jobs.ts';
import {activeNeeds,citizenLife} from './life.ts';
export const CAREER_ROLES=[
 ...STARTER_JOBS.map(j=>({id:j.id,name:j.name,track:null,skill:j.skill,tasks:j.tasks,sector:null})),
 {id:'clinical-assistant',name:'Clinical practitioner',track:'medicine',skill:'medicine',sector:'healthcare',tasks:[{label:'Review the fictional treatment record',choices:['Check consent, scope and recorded supplies','Invent a real diagnosis','Ignore referral limits'],correct:0},{label:'Use the recorded treatment plan',choices:['Follow the approved game procedure','Create supplies for free','Change another citizen’s licence'],correct:0},{label:'Close the case',choices:['Record outcome and referral','Publish private medical records','Claim a second fee'],correct:0}]},
 {id:'mechanic',name:'Technical mechanic',track:'technical',skill:'repair',sector:null,tasks:[{label:'Inspect the service',choices:['Record condition and authorised repair','Invent damage','Transfer ownership'],correct:0},{label:'Use repair inputs',choices:['Use approved supplies and scope','Ignore the parts record','Charge secretly'],correct:0},{label:'Verify completion',choices:['Record the tested outcome','Invent extra work','Hide the receipt'],correct:0}]},
 {id:'accountant',name:'Accountant',track:'business',skill:'accounting',sector:null,tasks:[{label:'Inspect the books',choices:['Reconcile posted journals','Edit balances directly','Delete tax entries'],correct:0},{label:'Review a variance',choices:['Retain evidence and reasons','Invent a payment','Hide a liability'],correct:0},{label:'Close the report',choices:['Publish scoped findings','Publish passwords','Buy a vote'],correct:0}]},
 {id:'journalist',name:'Journalist',track:'creative',skill:'journalism',sector:'media',tasks:[{label:'Review the source',choices:['Verify the game record','Invent a conviction','Publish private messages'],correct:0},{label:'Prepare the report',choices:['Label opinion and uncertainty','Claim a poll is representative without sampling','Hide the source'],correct:0},{label:'Publish safely',choices:['Retain corrections and reporting routes','Disable complaints','Sell ballot access'],correct:0}]}
];
type Vacancy={id:string;company:string;role:string;wage:number;slots:number;remaining:number;reserveShifts:number;deadline:number;status:'open'|'closed';schedule:string;terms:string;version:number};
type Application={id:string;actor:string;vacancy:string;status:'submitted'|'reviewed'|'interview-offered'|'interview-completed'|'rejected'|'offered'|'accepted'|'withdrawn';reason:string|null;submittedAt:number;interviewPassed:boolean;version:number};
type Contract={id:string;actor:string;company:string;vacancy:string;role:string;wage:number;remainingShifts:number;status:'active'|'notice'|'terminated';acceptedAt:number;noticeAt:number|null;terminationReason:string|null;version:number};
type Shift={id:string;contract:string;actor:string;startedAt:number;lastStepAt:number;steps:number;status:'active'|'paid'|'cancelled';wage:number;version:number};
export type EmploymentState={vacancies:Record<string,Vacancy>;applications:Record<string,Application>;contracts:Record<string,Contract>;shifts:Record<string,Shift>;active:Record<string,string>};
const getEmployment=(state:State)=>state.employment??={vacancies:{},applications:{},contracts:{},shifts:{},active:{}};
const number=(v:unknown,min:number,max:number)=>{if(!Number.isSafeInteger(v)||(v as number)<min||(v as number)>max)throw new DomainError('INVALID_WORK_TERMS','Use an amount within the displayed work limits.',400);return v as number;};
const roleFor=(id:unknown)=>CAREER_ROLES.find(r=>r.id===id);
const terms='Each accepted shift reserves the full wage. Three verified checks and a one-minute interval earn payment. Four shifts maximum per day. Either party can give one-day notice with a reason. Started work remains payable. No account passwords or private messages are required.';
function eligibility(state:State,actor:string,roleId:string,now:number){const role=roleFor(roleId)!;if(role.track&&!hasLicence(state,actor,role.track,now))throw new DomainError('JOB_CREDENTIAL_REQUIRED','This role requires a current '+role.track+' game licence.');}
const interview=[{prompt:'What secures your committed wage?',choices:['A reserved payment under the contract','A private promise','A screenshot'],correct:0},{prompt:'What belongs in a hiring review?',choices:['Relevant credentials and published duties','Your password','Unrelated private messages'],correct:0}];
export function employmentCommand(state:State,actor:string,command:Command,now:number,key:string):Record<string,unknown>|undefined{
 const types=['PostVacancy','ApplyForJob','ReviewApplication','OfferInterview','CompleteInterview','OfferEmployment','AcceptEmployment','WithdrawApplication','CloseVacancy','ReservePayroll','BeginContractWork','ContractWorkStep','SettleContractWork','CancelContractWork','GiveEmploymentNotice','FinishEmployment'];if(!types.includes(command.type))return;
 const citizen=state.citizens[actor];if(!citizen)throw new DomainError('CITIZEN_REQUIRED','Create your citizen first.');const e=getEmployment(state),m=getCommerce(state),p=command.payload;
 if(command.type==='PostVacancy'){
  const company=companyPermission(state,actor,String(p.companyId),'hire',now),role=roleFor(p.roleId);if(!role||(role.sector&&role.sector!==company.sector))throw new DomainError('INVALID_ROLE','Choose a role permitted for this sector.',400);if(company.status!=='active')throw new DomainError('COMPANY_DISTRESSED','Resolve company distress before new hiring.');
  const wage=number(p.wage,25000,1000000),slots=number(p.slots,1,10),reserveShifts=number(p.reserveShifts,1,4),deadline=number(p.deadline,now+60000,now+30*DAY);if(p.acceptTerms!==true)throw new DomainError('TERMS_REQUIRED','Review the secured wage and notice terms.');const id='vacancy_'+key,amount=wage*slots*reserveShifts;
  post(state,key,now,'Secured advertised payroll',[{account:'company:'+company.id,amount:-amount},{account:'payroll:'+id,amount}]);e.vacancies[id]={id,company:company.id,role:role.id,wage,slots,remaining:slots,reserveShifts,deadline,status:'open',schedule:'Short asynchronous shifts; maximum four per day',terms,version:1};return{vacancyId:id,reserved:amount,message:'The advertised wage horizon is prefunded.'};
 }
 if(command.type==='ApplyForJob'){
  const vacancy=e.vacancies[String(p.vacancyId)];if(!vacancy||vacancy.status!=='open'||vacancy.deadline<=now||!vacancy.remaining)throw new DomainError('VACANCY_CLOSED','This vacancy is unavailable.');eligibility(state,actor,vacancy.role,now);
  if(Object.values(e.applications).some(a=>a.actor===actor&&a.vacancy===vacancy.id&&!['rejected','withdrawn'].includes(a.status)))throw new DomainError('APPLICATION_EXISTS','Your application is already recorded.');const id='application_'+key;e.applications[id]={id,actor,vacancy:vacancy.id,status:'submitted',reason:null,submittedAt:now,interviewPassed:false,version:1};return{applicationId:id,message:'Application submitted with only relevant game credentials.'};
 }
 if(['ReviewApplication','OfferInterview','CompleteInterview','OfferEmployment','AcceptEmployment','WithdrawApplication'].includes(command.type)){
  const application=e.applications[String(p.applicationId)];if(!application)throw new DomainError('APPLICATION_NOT_FOUND','This application is unavailable.',404);const vacancy=e.vacancies[application.vacancy],company=m.companies[vacancy.company];
  if(['CompleteInterview','AcceptEmployment','WithdrawApplication'].includes(command.type)){if(application.actor!==actor)throw new DomainError('APPLICATION_PERMISSION','Only the applicant may take this action.',403);}else companyPermission(state,actor,company.id,'hire',now);
  if(command.type==='WithdrawApplication'){if(application.status==='accepted')throw new DomainError('EMPLOYMENT_ACTIVE','Use the contract’s notice process.');application.status='withdrawn';application.version++;return{message:'Application withdrawn.'};}
  if(command.type==='ReviewApplication'){
   if(application.status!=='submitted')throw new DomainError('APPLICATION_STAGE','This application has already been reviewed.');const reason=typeof p.reason==='string'?p.reason.trim():'';if(reason.length<5||reason.length>500)throw new DomainError('REASON_REQUIRED','Record a relevant hiring reason.',400);application.status=p.reject===true?'rejected':'reviewed';application.reason=reason;application.version++;return{message:p.reject===true?'Rejection and reason recorded.':'Review recorded. No unrelated personal records were supplied.'};
  }
  if(command.type==='OfferInterview'){if(application.status!=='reviewed')throw new DomainError('APPLICATION_STAGE','Review this application first.');application.status='interview-offered';application.version++;return{message:'Approved interview activities offered.'};}
  if(command.type==='CompleteInterview'){
   if(application.status!=='interview-offered')throw new DomainError('INTERVIEW_UNAVAILABLE','There is no offered interview.');const answers=p.answers;if(!Array.isArray(answers)||answers.length!==interview.length||answers.some(a=>!Number.isInteger(a)||a<0||a>2))throw new DomainError('INVALID_INTERVIEW','Answer the interview activities.',400);application.interviewPassed=interview.every((q,i)=>answers[i]===q.correct);application.status='interview-completed';application.version++;return{passed:application.interviewPassed,message:'Interview result recorded; an offer still requires employer decision.'};
  }
  if(command.type==='OfferEmployment'){if(application.status!=='interview-completed'||!application.interviewPassed||!vacancy.remaining||vacancy.status!=='open')throw new DomainError('OFFER_UNAVAILABLE','The interview, vacancy and funded position must remain eligible.');eligibility(state,application.actor,vacancy.role,now);application.status='offered';application.version++;return{terms:vacancy.terms,wage:vacancy.wage,message:'A secured employment offer is ready for applicant consent.'};}
  if(application.status!=='offered'||p.acceptTerms!==true||!vacancy.remaining||vacancy.status!=='open')throw new DomainError('OFFER_UNAVAILABLE','Review a current offer and explicitly accept its terms.');eligibility(state,actor,vacancy.role,now);
  const id='employment_'+key,amount=vacancy.wage*vacancy.reserveShifts;post(state,key,now,'Allocated secured employment wages',[{account:'payroll:'+vacancy.id,amount:-amount},{account:'payroll:'+id,amount}]);e.contracts[id]={id,actor,company:company.id,vacancy:vacancy.id,role:vacancy.role,wage:vacancy.wage,remainingShifts:vacancy.reserveShifts,status:'active',acceptedAt:now,noticeAt:null,terminationReason:null,version:1};vacancy.remaining--;vacancy.version++;application.status='accepted';application.version++;company.members[actor]??='employee';company.lastActive[actor]=now;company.version++;return{contractId:id,message:'Employment accepted. Earned wages and personal assets remain protected.'};
 }
 if(command.type==='CloseVacancy'){
  const v=e.vacancies[String(p.vacancyId)];if(!v)throw new DomainError('VACANCY_NOT_FOUND','This vacancy is unavailable.',404);companyPermission(state,actor,v.company,'hire',now);if(v.status!=='open')throw new DomainError('VACANCY_CLOSED','This vacancy is already closed.');const amount=state.balances['payroll:'+v.id]??0;if(amount)post(state,key,now,'Uncommitted vacancy payroll returned',[{account:'payroll:'+v.id,amount:-amount},{account:'company:'+v.company,amount}]);v.remaining=0;v.status='closed';v.version++;return{message:'Uncommitted funds returned. Accepted contracts retain their own reserves.'};
 }
 const contract=e.contracts[String(p.contractId)];if(!contract)throw new DomainError('CONTRACT_NOT_FOUND','This employment contract is unavailable.',404);
 const employer=m.companies[contract.company],worker=actor===contract.actor;
 if(['ReservePayroll','GiveEmploymentNotice','FinishEmployment'].includes(command.type)){if(!worker||command.type==='ReservePayroll')companyPermission(state,actor,contract.company,'hire',now);}else if(!worker)throw new DomainError('WORKER_PERMISSION','Only the contracted worker can do this task.',403);
 if(command.type==='ReservePayroll'){
  if(contract.status!=='active')throw new DomainError('CONTRACT_CLOSED','This contract cannot take new commitments.');const shifts=number(p.shifts,1,4),amount=contract.wage*shifts;if(contract.remainingShifts+shifts>4)throw new DomainError('PAYROLL_LIMIT','Reserve at most four upcoming shifts.');post(state,key,now,'Extended secured payroll',[{account:'company:'+contract.company,amount:-amount},{account:'payroll:'+contract.id,amount}]);contract.remainingShifts+=shifts;contract.version++;return{message:'Additional wages reserved from existing company funds.'};
 }
 if(command.type==='GiveEmploymentNotice'){
  if(contract.status!=='active')throw new DomainError('NOTICE_EXISTS','This contract already has notice or has closed.');const reason=typeof p.reason==='string'?p.reason.trim():'';if(reason.length<5||reason.length>500)throw new DomainError('REASON_REQUIRED','Record a termination or resignation reason.',400);contract.status='notice';contract.noticeAt=now+DAY;contract.terminationReason=reason;contract.version++;return{noticeAt:contract.noticeAt,message:'One-day notice recorded. Started work remains payable.'};
 }
 if(command.type==='FinishEmployment'){
  if(contract.status!=='notice'||now<(contract.noticeAt??Infinity))throw new DomainError('NOTICE_PENDING','The disclosed notice period has not ended.');const amount=state.balances['payroll:'+contract.id]??0;if(amount)post(state,key,now,'Uncommitted employment reserve returned',[{account:'payroll:'+contract.id,amount:-amount},{account:'company:'+contract.company,amount}]);contract.status='terminated';contract.remainingShifts=0;contract.version++;if(employer.members[contract.actor]==='employee'&&!Object.values(e.contracts).some(c=>c.id!==contract.id&&c.actor===contract.actor&&c.company===contract.company&&c.status!=='terminated'))delete employer.members[contract.actor];return{message:'Employment ended. Started task escrow remains payable to its worker.'};
 }
 const active=e.shifts[e.active[actor]],role=roleFor(contract.role)!;
 if(command.type==='BeginContractWork'){
  if(contract.status!=='active'||!contract.remainingShifts)throw new DomainError('PAYROLL_REQUIRED','New work requires an active contract and a secured wage.');if(active?.status==='active')throw new DomainError('WORK_ACTIVE','Finish the current contracted task.');eligibility(state,actor,contract.role,now);
  const completed=Object.values(e.shifts).filter(s=>s.actor===actor&&s.status==='paid'&&Math.floor(s.startedAt/DAY)===Math.floor(now/DAY));if(completed.length>=4)throw new DomainError('WORK_LIMIT','The published daily contracted-work limit is reached.');const id='contract_shift_'+key;post(state,key,now,'Secured committed work',[{account:'payroll:'+contract.id,amount:-contract.wage},{account:'escrow:'+id,amount:contract.wage}]);contract.remainingShifts--;contract.version++;e.shifts[id]={id,contract:contract.id,actor,startedAt:now,lastStepAt:now,steps:0,status:'active',wage:contract.wage,version:1};e.active[actor]=id;return{shiftId:id,message:'Your committed wage moved to protected task escrow.'};
 }
 if(!active||active.status!=='active'||active.contract!==contract.id)throw new DomainError('WORK_REQUIRED','Begin this contract’s paid task first.');
 if(command.type==='ContractWorkStep'){
  if(active.steps>=role.tasks.length||now-active.lastStepAt<2000)throw new DomainError('WORK_STAGE','Review the current task or wait for settlement.');if(p.choice!==role.tasks[active.steps].correct)throw new DomainError('TASK_REVIEW','Choose the approved action for this task.');active.steps++;active.lastStepAt=now;active.version++;return{message:'Verified contracted task activity recorded.'};
 }
 if(command.type==='CancelContractWork'){
  if(active.steps===role.tasks.length)throw new DomainError('EARNED_WORK','Your completed checks retain their earned wage.');const destination=contract.status==='terminated'?'company:'+contract.company:'payroll:'+contract.id;post(state,key,now,'Uncompleted contracted task released',[{account:'escrow:'+active.id,amount:-active.wage},{account:destination,amount:active.wage}]);if(contract.status!=='terminated')contract.remainingShifts++;active.status='cancelled';active.version++;delete e.active[actor];return{message:'Uncompleted task reserve returned under the contract; no earned wage was removed.'};
 }
 if(active.steps!==role.tasks.length||now-active.startedAt<60000)throw new DomainError('TASKS_REQUIRED','Complete all checks and the one-minute work interval.');
 const tax=now<citizen.protectionEndsAt?0:Math.floor(active.wage*250/10000);post(state,key,now,'Verified contracted wage and income tax',[{account:'escrow:'+active.id,amount:-active.wage},{account:'citizen:'+actor,amount:active.wage-tax},...(tax?[{account:'treasury:state:'+citizen.state,amount:tax}]:[])]);active.status='paid';active.version++;delete e.active[actor];citizenLife(state,citizen,now);activeNeeds(citizen,now);citizen.life!.skills[role.skill]=(citizen.life!.skills[role.skill]??0)+1;citizen.life!.needs.energy=Math.max(20,citizen.life!.needs.energy-10);return{shiftId:active.id,contractId:contract.id,gross:active.wage,tax,net:active.wage-tax,message:'Your reserved wage and tax settled once, regardless of employer activity.'};
}
export function employmentView(state:State,actor:string,now:number){
 const e=state.employment,m=state.commerce,roles=CAREER_ROLES.map(({tasks,...role})=>role);if(!e)return{roles,vacancies:[],applications:[],contracts:[],shifts:[],interview:interview.map(({prompt,choices})=>({prompt,choices}))};const companies=new Set(Object.values(m?.companies??{}).filter(c=>['founder','cofounder','ceo','manager'].includes(c.members[actor])||c.actingManager===actor).map(c=>c.id));
 return{roles,vacancies:Object.values(e.vacancies).filter(v=>v.status==='open'||companies.has(v.company)).map(v=>({...v,companyName:m!.companies[v.company].name,region:m!.companies[v.company].region,eligible:!roleFor(v.role)?.track||hasLicence(state,actor,roleFor(v.role)!.track!,now)})),applications:Object.values(e.applications).filter(a=>a.actor===actor||companies.has(e.vacancies[a.vacancy].company)).map(a=>({...a,actor:state.citizens[a.actor]?.id,name:state.citizens[a.actor]?.name})),contracts:Object.values(e.contracts).filter(c=>c.actor===actor||companies.has(c.company)).map(c=>({...c,actor:state.citizens[c.actor]?.id,reserve:state.balances['payroll:'+c.id]??0})),shifts:Object.values(e.shifts).filter(s=>s.actor===actor||companies.has(e.contracts[s.contract].company)).map(s=>{const role=roleFor(e.contracts[s.contract].role)!,task=role.tasks[s.steps];return{...s,actor:state.citizens[s.actor]?.id,settlementAt:s.startedAt+60000,nextStepAt:s.lastStepAt+2000,task:task?{label:task.label,choices:task.choices}:null};}),interview:interview.map(({prompt,choices})=>({prompt,choices}))};
}
