import {DomainError,post} from './domain.ts';
import type {State,Command} from './domain.ts';
import {DAY} from './rules.ts';
import {companyPermission,getCommerce} from './commerce.ts';
import {hasLicence,COURSES} from './education.ts';
type Institution={id:string;company:string;active:boolean;rateBps:number;reserveBps:number;version:number};
type Saving={id:string;actor:string;provider:string;principal:number;rateBps:number;lastAccruedAt:number;remainder:string;owed:number;paidInterest:number;version:number};
type Loan={id:string;actor:string;provider:string;principal:number;interest:number;lateFee:number;paid:number;instalment:number;startedAt:number;nextDueAt:number;maturity:number;status:'active'|'hardship'|'paid';hardshipUsed:boolean;lateReviewed:boolean;educationAward:string|null;termsVersion:string;version:number;waived?:number};
export type FinanceState={institutions:Record<string,Institution>;savings:Record<string,Saving>;loans:Record<string,Loan>;npcLending:Record<string,number>;npcInterest:Record<string,number>;transfers:{id:string;sender:string;recipient:string;amount:number;at:number}[];risk:{id:string;reason:string;references:string[];at:number}[]};
const finance=(state:State)=>state.finance??={institutions:{},savings:{},loans:{},npcLending:{},npcInterest:{},transfers:[],risk:[]};
const value=(v:unknown,min=1,max=100000000)=>{if(!Number.isSafeInteger(v)||(v as number)<min||(v as number)>max)throw new DomainError('INVALID_AMOUNT','Choose an integer amount within the published limits.',400);return v as number;};
const loanTerms='Four weekly instalments; fixed 5% total interest; late fees capped at 10% of original principal, assessed once after seven days of grace. One 14-day hardship extension is available. Debt grants no control over your account, education, shelter or work.';
function provider(state:State,id:string){if(id==='npc')return{account:'system:npc-credit-issuance',name:'NPC community bank',rateBps:100};const bank=finance(state).institutions[id];if(!bank||!bank.active)throw new DomainError('BANK_UNAVAILABLE','This financial provider is unavailable.');return{account:'company:'+bank.company,name:getCommerce(state).companies[bank.company].name,rateBps:bank.rateBps};}
function accrue(s:Saving,now:number){const elapsed=Math.min(30*DAY,Math.max(0,now-s.lastAccruedAt)),denominator=BigInt(10000)*BigInt(30*DAY),numerator=BigInt(s.remainder)+BigInt(s.principal)*BigInt(s.rateBps)*BigInt(elapsed),amount=Number(numerator/denominator);if(!Number.isSafeInteger(s.owed+amount))throw new Error('Interest overflow');s.owed+=amount;s.remainder=(numerator%denominator).toString();s.lastAccruedAt=now;}
function incomeCapacity(state:State,actor:string,now:number){
 const receipts=Object.values(state.commands).map(c=>c.receipt).filter(r=>r.actorId===actor&&r.at>=now-7*DAY&&r.at<=now);let income=0;
 for(const r of receipts){if(r.type==='CompleteShift')income+=Number(r.detail.amount);if(r.type==='SettleContractWork'){const shift=state.employment?.shifts[String(r.detail.shiftId)],contract=shift?state.employment?.contracts[shift.contract]:null,self=contract?state.commerce?.companies[contract.company].shares[actor]:true;if(shift&&contract&&!self)income+=Number(r.detail.net);}}
 return Math.min(500000,income*4);
}
export function financeCommand(state:State,actor:string,command:Command,now:number,key:string):Record<string,unknown>|undefined{
 const types=['TransferMoney','RegisterBank','DepositSavings','WithdrawSavings','CollectSavingsInterest','RequestLoan','RepayLoan','RequestLoanHardship','ReviewLoan','CloseBank','CancelEducationLoan'];if(!types.includes(command.type))return;
 const c=state.citizens[actor];if(!c)throw new DomainError('CITIZEN_REQUIRED','Create your citizen first.');const f=finance(state),p=command.payload;
 if(command.type==='TransferMoney'){
  const recipient=Object.values(state.citizens).find(c=>c.id===p.citizenId);if(!recipient||recipient.actorId===actor)throw new DomainError('INVALID_RECIPIENT','Choose another existing citizen.',400);if(p.confirmRecipient!==recipient.id)throw new DomainError('RECIPIENT_REVIEW','Confirm the exact recipient citizen ID.');if(state.life?.blocks[actor]?.includes(recipient.actorId)||state.life?.blocks[recipient.actorId]?.includes(actor))throw new DomainError('CONTACT_BLOCKED','This unsolicited transfer cannot be sent.',403);const amount=value(p.amount);post(state,key,now,'Consented peer transfer',[{account:'citizen:'+actor,amount:-amount},{account:'citizen:'+recipient.actorId,amount}]);f.transfers.push({id:key,sender:actor,recipient:recipient.actorId,amount,at:now});
  const circular=f.transfers.filter(t=>now-t.at<60000&&t.sender===recipient.actorId&&t.recipient===actor);if(circular.length>=2)f.risk.push({id:'risk_'+key,reason:'Rapid circular transfers; review required, no automatic confiscation',references:circular.map(t=>t.id).concat(key),at:now});return{amount,recipient:recipient.id,message:'Transfer and receipt recorded once.'};
 }
 if(command.type==='RegisterBank'){
  const company=companyPermission(state,actor,String(p.companyId),'govern',now);if(company.sector!=='finance'||!hasLicence(state,actor,'finance',now))throw new DomainError('FINANCE_LICENCE_REQUIRED','A finance company and current finance licence are required.');if(Object.values(f.institutions).some(b=>b.company===company.id))throw new DomainError('BANK_EXISTS','This company already registered its financial institution.');if((state.balances['company:'+company.id]??0)<500000)throw new DomainError('BANK_CAPITAL','Retain at least ₦5,000 in funded company capital.');const id='bank_'+key;f.institutions[id]={id,company:company.id,active:true,rateBps:100,reserveBps:10000,version:1};return{institutionId:id,message:'Bank registered with 100% protected deposit reserves. Interest and lending use company capital, never customer deposits.'};
 }
 if(command.type==='DepositSavings'){
  const bank=provider(state,String(p.providerId)),amount=value(p.amount);if(p.acceptTerms!==true||p.acceptedRateBps!==bank.rateBps)throw new DomainError('TERMS_REQUIRED','Accept the monthly rate, funding source, withdrawal and 30-day offline accrual cap.');const id='saving_'+actor+':'+String(p.providerId),old=f.savings[id];if(old)accrue(old,now);post(state,key,now,'Protected savings deposit',[{account:'citizen:'+actor,amount:-amount},{account:'saving:'+id,amount}]);
  const saving=old??{id,actor,provider:String(p.providerId),principal:0,rateBps:bank.rateBps,lastAccruedAt:now,remainder:'0',owed:0,paidInterest:0,version:0};saving.principal+=amount;saving.version++;f.savings[id]=saving;return{savingsId:id,message:'Principal is fully reserved. NPC interest uses a disclosed daily subsidy; player-bank interest depends on its funded capital. Withdrawal does not need manager permission.'};
 }
 if(command.type==='WithdrawSavings'||command.type==='CollectSavingsInterest'){
  const saving=f.savings[String(p.savingsId)];if(!saving||saving.actor!==actor)throw new DomainError('SAVINGS_NOT_FOUND','This savings account is unavailable.',404);accrue(saving,now);
  if(command.type==='WithdrawSavings'){const amount=value(p.amount,1,saving.principal);post(state,key,now,'Protected savings withdrawal',[{account:'saving:'+saving.id,amount:-amount},{account:'citizen:'+actor,amount}]);saving.principal-=amount;saving.version++;return{amount,message:'Your reserved principal was returned. Accrued unpaid interest remains in the record.'};}
  if(!saving.owed)throw new DomainError('INTEREST_PENDING','No whole minor-unit interest is payable yet.');const bank=provider(state,saving.provider),amount=saving.owed,period=String(Math.floor(now/DAY));if(saving.provider==='npc'){if((f.npcInterest[period]??0)+amount>1000000)throw new DomainError('INTEREST_BUDGET','Today’s declared NPC interest subsidy is committed. Principal withdrawal remains available.');f.npcInterest[period]=(f.npcInterest[period]??0)+amount;}
  post(state,key,now,'Funded savings interest',[{account:saving.provider==='npc'?'system:npc-savings-subsidy':bank.account,amount:-amount},{account:'citizen:'+actor,amount}]);saving.paidInterest+=amount;saving.owed=0;saving.version++;return{amount,message:'Interest paid from its recorded provider or subsidy source.'};
 }
 if(command.type==='RequestLoan'){
  const principal=value(p.principal,1000,500000),bank=provider(state,String(p.providerId));if(p.acceptTerms!==true||p.acceptedInterestBps!==500)throw new DomainError('TERMS_REQUIRED','Review the fixed 5% interest, four instalments, caps and hardship terms.');const outstanding=Object.values(f.loans).filter(l=>l.actor===actor&&l.status!=='paid').reduce((n,l)=>n+l.principal+l.interest+l.lateFee-l.paid,0);if(principal+outstanding>incomeCapacity(state,actor,now))throw new DomainError('LOAN_AFFORDABILITY','Recent verified independent wages do not support this additional obligation.');
  const course=p.courseId?COURSES.find(c=>c.id===p.courseId):null;if(p.courseId&&(!course||!c.certificate||principal!==course.fee))throw new DomainError('EDUCATION_LOAN_SCOPE','An education loan must match official tuition and foundation eligibility.');const id='loan_'+key,interest=Math.ceil(principal*.05),period=String(Math.floor(now/DAY));if(p.providerId==='npc'){if((f.npcLending[period]??0)+principal>100000000)throw new DomainError('CREDIT_BUDGET','The NPC period lending budget is committed.');f.npcLending[period]=(f.npcLending[period]??0)+principal;}
  const award=course?'loan_award_'+key:null;post(state,key,now,'Funded disclosed virtual loan',[{account:bank.account,amount:-principal},{account:award?'scholarship:'+award:'citizen:'+actor,amount:principal}]);if(course){state.education??={foundation:{},enrolments:{},scholarships:{},licences:{}};state.education.scholarships[award!]={id:award!,donor:'loan-provider:'+String(p.providerId),recipient:actor,course:course.id,amount:principal,expiresAt:now+30*DAY,status:'offered',enrolmentId:null};}
  f.loans[id]={id,actor,provider:String(p.providerId),principal,interest,lateFee:0,paid:0,instalment:Math.ceil((principal+interest)/4),startedAt:now,nextDueAt:now+7*DAY,maturity:now+28*DAY,status:'active',hardshipUsed:false,lateReviewed:false,educationAward:award,termsVersion:'virtual-credit-1.0',version:1};return{loanId:id,principal,interest,terms:loanTerms,message:award?'Restricted tuition funded; the loan does not create withdrawable scholarship cash.':'Disclosed loan funded with a separate liability record.'};
 }
 if(command.type==='CloseBank'){
  const bank=f.institutions[String(p.institutionId)];if(!bank)throw new DomainError('BANK_NOT_FOUND','This institution is unavailable.',404);companyPermission(state,actor,bank.company,'govern',now);if(!bank.active)throw new DomainError('BANK_CLOSED','This institution already closed.');bank.active=false;bank.version++;return{message:'New deposits and loans closed. Existing principal stays reserved and freely withdrawable; liabilities remain recorded.'};
 }
 const loan=f.loans[String(p.loanId)];if(!loan||loan.actor!==actor)throw new DomainError('LOAN_NOT_FOUND','This loan is unavailable.',404);
 if(command.type==='CancelEducationLoan'){
  const award=loan.educationAward?state.education?.scholarships[loan.educationAward]:null;if(!award||award.status!=='offered')throw new DomainError('TUITION_COMMITTED','Cancellation requires unused restricted tuition or a refunded uncompleted enrolment.');
  const returned=Math.max(0,loan.principal-loan.paid),refund=loan.principal-returned,source=loan.provider==='npc'?'system:npc-bank-repayments':'company:'+f.institutions[loan.provider].company;
  post(state,key,now,'Unused education loan cancellation',[{account:'scholarship:'+award.id,amount:-loan.principal},{account:source,amount:returned},{account:'citizen:'+actor,amount:refund}]);
  const paidExtras=Math.max(0,loan.paid-loan.principal),retainedInterest=Math.min(loan.interest,paidExtras),retainedFee=Math.min(loan.lateFee,Math.max(0,paidExtras-retainedInterest));loan.waived=loan.interest+loan.lateFee-retainedInterest-retainedFee;loan.interest=retainedInterest;loan.lateFee=retainedFee;loan.paid=loan.principal+retainedInterest+retainedFee;loan.status='paid';loan.version++;award.status='refunded';return{principalReturned:returned,previousPrincipalPaymentsReturned:refund,waived:loan.waived,message:'Unused tuition returned to its actual funding sources; unpaid charges were waived. No new money was created.'};
 }
 if(loan.status==='paid')throw new DomainError('LOAN_SETTLED','This obligation is already paid.');
 if(command.type==='RequestLoanHardship'){
  if(loan.hardshipUsed)throw new DomainError('HARDSHIP_USED','The published hardship extension has already been used.');loan.hardshipUsed=true;loan.status='hardship';loan.nextDueAt+=14*DAY;loan.maturity+=14*DAY;loan.version++;return{message:'One 14-day hardship extension recorded. No extra interest or forced work was added.'};
 }
 if(command.type==='ReviewLoan'){
  if(now>loan.nextDueAt+7*DAY&&!loan.lateReviewed){loan.lateFee=Math.min(Math.ceil(loan.principal*.1),loan.principal+loan.interest-loan.paid);loan.lateReviewed=true;loan.version++;}return{lateFee:loan.lateFee,message:'Late fees are capped and assessed once. Basic services remain available.'};
 }
 const amount=value(p.amount,1,loan.principal+loan.interest+loan.lateFee-loan.paid),bank=loan.provider==='npc'?{account:'system:npc-bank-repayments'}:{account:'company:'+f.institutions[loan.provider].company};post(state,key,now,'Recorded loan repayment',[{account:'citizen:'+actor,amount:-amount},{account:bank.account,amount}]);loan.paid+=amount;loan.version++;const instalments=Math.min(4,Math.floor(loan.paid/loan.instalment));loan.nextDueAt=loan.startedAt+(instalments+1)*7*DAY+(loan.hardshipUsed?14*DAY:0);if(loan.paid===loan.principal+loan.interest+loan.lateFee)loan.status='paid';return{amount,remaining:loan.principal+loan.interest+loan.lateFee-loan.paid,message:'Repayment recorded; no client balance or debt amount was trusted.'};
}
export function financeView(state:State,actor:string,now:number){const f=state.finance;return{providers:[{id:'npc',name:'NPC community bank',rateBps:100,reserveBps:10000},...Object.values(f?.institutions??{}).filter(b=>b.active).map(b=>({...b,name:state.commerce?.companies[b.company].name}))],terms:loanTerms,savings:Object.values(f?.savings??{}).filter(s=>s.actor===actor).map(s=>{const copy=structuredClone(s);accrue(copy,now);return{...copy,actor:state.citizens[actor]?.id,terms:'1% per 30 days on time-weighted principal; offline accrual is capped at 30 days. Reserved principal can always be withdrawn. Interest depends on provider funding.'};}),loans:Object.values(f?.loans??{}).filter(l=>l.actor===actor).map(l=>({...l,actor:state.citizens[actor]?.id,remaining:l.principal+l.interest+l.lateFee-l.paid})),affordabilityCap:incomeCapacity(state,actor,now)};}
