import {createHash} from 'node:crypto';
import {DomainError,post} from './domain.ts';
import type {State,Command} from './domain.ts';
import {DAY} from './rules.ts';
import {positionFor} from './world.ts';
import {hasLicence} from './education.ts';
import {getCommerce,companyPermission,consumeSupply} from './commerce.ts';
import {activeNeeds,citizenLife} from './life.ts';
import {stockPost} from './stock.ts';
export const HEALTH_RULES={version:'game-health-1.0',consultation:5000,treatment:10000,npcTreatment:2500,recoveryTime:60000,beds:10,npcDailySupplies:100000,patientDailyTreatments:4};
type Hospital={id:string;company:string;region:string;quality:number;beds:number;active:boolean;version:number};
export type CareCase={id:string;patient:string;provider:string;region:string;intake:{health:number;energy:number};incidentId?:string|null;exposureAt?:number;condition:'routine'|'strain'|'urgent'|null;status:'queued'|'assessed'|'funded'|'recovering'|'completed'|'cancelled';consultation:number;paidConsultation?:number;fee:number;createdAt:number;recoveryAt:number|null;assessor:string|null;referral:string|null;transport:string|null;version:number};
export type HealthcareState={hospitals:Record<string,Hospital>;cases:Record<string,CareCase>;npcUse:Record<string,number>;patientUse:Record<string,number>};
const get=(s:State)=>s.healthcare??={hospitals:{},cases:{},npcUse:{},patientUse:{}};
const id=(key:string)=>createHash('sha256').update(key).digest('hex').slice(0,24);
function staff(s:State,actor:string,h:Hospital,now:number){if(!hasLicence(s,actor,'medicine',now))return false;const company=s.commerce?.companies[h.company];return !!company&&company.status!=='closed'&&(['founder','cofounder','ceo'].includes(company.members[actor])||Object.values(s.employment?.contracts??{}).some(c=>c.company===company.id&&c.actor===actor&&c.role==='clinical-practitioner'&&c.status==='active'));}
function provider(s:State,providerId:unknown,region:string){if(providerId==='npc')return null;const h=get(s).hospitals[String(providerId)];if(!h||!h.active||h.region!==region||s.commerce?.companies[h.company].status==='closed')throw new DomainError('HOSPITAL_UNAVAILABLE','Choose an active local hospital or NPC baseline care.');return h;}
function clinicalAccess(s:State,actor:string,c:CareCase,h:Hospital,now:number){return staff(s,actor,h,now)&&!s.life?.blocks[actor]?.includes(c.patient)&&!s.life?.blocks[c.patient]?.includes(actor);}
function casePermission(s:State,actor:string,caseId:unknown,now:number,patientOnly=false){const c=get(s).cases[String(caseId)],h=c&&c.provider!=='npc'?get(s).hospitals[c.provider]:null;if(!c||!(c.patient===actor||!patientOnly&&h&&clinicalAccess(s,actor,c,h,now)))throw new DomainError('CARE_PERMISSION','Only the patient or their currently qualified treating staff may access this case.',403);return{c,h};}
function presence(s:State,c:CareCase,actor:string,h:Hospital|null,now:number){const patient=positionFor(s,s.citizens[c.patient],now);if(patient.region!==c.region||s.world!.activeTrips[c.patient]||(h&&positionFor(s,s.citizens[actor],now).region!==h.region))throw new DomainError('CLINIC_LOCATION','Patient and treating staff must be in the recorded region without an active patient journey.');}
function npcSupplies(s:State,c:CareCase,now:number,key:string){const m=get(s),day=c.region+':'+Math.floor(now/DAY),used=m.npcUse[day]??0;if(used+2>HEALTH_RULES.npcDailySupplies)throw new DomainError('HEALTH_SUPPLY_BUDGET','The clinical supply period is committed. Protective basic care remains available.');m.npcUse[day]=used+2;getCommerce(s);stockPost(s,{id:'npc-medical:'+key,goods:'medicine',at:now,reason:'Budgeted NPC clinical supplies',entries:[{account:'system:npc-medical-source:'+day,quantity:-2},{account:'system:medical-treatment-consumed',quantity:2}]});stockPost(s,{id:'npc-clinical-power:'+key,goods:'energy',at:now,reason:'Budgeted NPC clinical power',entries:[{account:'system:npc-clinical-power-source:'+day,quantity:-2},{account:'system:clinical-power-consumed',quantity:2}]});}
export function healthcareCommand(s:State,actor:string,cmd:Command,now:number,key:string):Record<string,unknown>|undefined{
 const types=['RegisterHospital','CloseHospital','RequestAssessment','AssessPatient','AcceptTreatment','TreatPatient','CompleteRecovery','CancelHealthcare','TransferCareToNPC','RequestEmergencyTransport'];if(!types.includes(cmd.type))return;
 const citizen=s.citizens[actor];if(!citizen)throw new DomainError('CITIZEN_REQUIRED','Create your citizen first.');const m=get(s),p=cmd.payload,pos=positionFor(s,citizen,now);
 if(cmd.type==='RegisterHospital'){const company=companyPermission(s,actor,String(p.companyId),'govern',now);if(company.sector!=='healthcare'||!hasLicence(s,actor,'medicine',now))throw new DomainError('CLINICAL_LICENCE_REQUIRED','Hospital governance requires a healthcare company and current clinical licence.');if((s.balances['company:'+company.id]??0)<100000)throw new DomainError('HOSPITAL_BUDGET','Retain at least ₦1,000 of real operating funds.');if(Object.values(m.hospitals).some(h=>h.company===company.id))throw new DomainError('HOSPITAL_EXISTS','This company already registered its hospital.');const hospitalId='hospital_'+id(key);m.hospitals[hospitalId]={id:hospitalId,company:company.id,region:company.region,quality:100,beds:HEALTH_RULES.beds,active:true,version:1};return{hospitalId,message:'Clinical facility registered. Patient treatment requires current qualified staff, actual medicine and power, and reserved fees.'};}
 if(cmd.type==='CloseHospital'){const h=m.hospitals[String(p.hospitalId)];if(!h)throw new DomainError('HOSPITAL_UNAVAILABLE','Choose your hospital.');companyPermission(s,actor,h.company,'govern',now);h.active=false;h.version++;return{message:'New intake closed. Patients retain refunds for unearned care and NPC continuation; verified recovery stays payable.'};}
 if(cmd.type==='RequestAssessment'){if(s.world!.activeTrips[actor])throw new DomainError('IN_TRANSIT','Finish the current journey before clinical intake.');if(p.consent!==true)throw new DomainError('CARE_CONSENT','Consent to sharing this game-health episode with currently qualified treating staff.');if(Object.values(m.cases).some(c=>c.patient===actor&&!['completed','cancelled'].includes(c.status)))throw new DomainError('CARE_ACTIVE','Complete, cancel or transfer your existing episode.');const h=provider(s,p.providerId,pos.region);if(h&&Object.values(m.cases).filter(c=>c.provider===h.id&&!['completed','cancelled'].includes(c.status)).length>=h.beds)throw new DomainError('HOSPITAL_CAPACITY','This facility has no available clinical slot. NPC care remains available.');citizenLife(s,citizen,now);activeNeeds(citizen,now);const consultation=h?HEALTH_RULES.consultation:0;if(p.acceptedConsultation!==consultation)throw new DomainError('CARE_TERMS','Accept the exact assessment fee. NPC assessment is free.');const exposure=Object.values(s.incidents?.records??{}).filter(i=>i.actor===actor&&i.healthAfter<i.healthBefore&&i.at<=now).sort((a,b)=>b.at-a.at)[0];const caseId='care_'+id(key);if(consultation)post(s,key,now,'Reserved clinical consultation',[{account:'citizen:'+actor,amount:-consultation},{account:'consultation:'+caseId,amount:consultation}]);m.cases[caseId]={id:caseId,patient:actor,provider:h?.id??'npc',region:pos.region,intake:{health:citizen.life!.needs.health,energy:citizen.life!.needs.energy},incidentId:exposure?.id??null,exposureAt:exposure?.at??now,condition:null,status:'queued',consultation,fee:0,createdAt:now,recoveryAt:null,assessor:null,referral:null,transport:null,version:1};return{caseId,message:'Game-health assessment queued with scoped consent. This is a fictional clinical activity.'};}
 const {c,h}=casePermission(s,actor,p.caseId,now);
 if(cmd.type==='AssessPatient'){if(c.status!=='queued'||now<c.createdAt+2000||p.choice!==0)throw new DomainError('ASSESSMENT_PROCEDURE','Use the approved game assessment after the intake interval.');if(h&&(!staff(s,actor,h,now)||!h.active))throw new DomainError('CLINICAL_PERMISSION','Current treating staff are required; the patient may transfer to NPC care.',403);if(!h&&actor!==c.patient)throw new DomainError('CARE_PERMISSION','Only the patient requests their NPC procedure.',403);presence(s,c,actor,h,now);if(h)consumeSupply(s,'company:'+h.company,h.region,'energy',1,now,key);const patient=s.citizens[c.patient];citizenLife(s,patient,now);activeNeeds(patient,now);c.intake={health:patient.life!.needs.health,energy:patient.life!.needs.energy};c.condition=c.intake.health<=60?'urgent':c.intake.health<90?'strain':'routine';c.referral=c.condition==='urgent'?'NPC emergency clinic':null;c.status='assessed';c.paidConsultation=c.consultation;c.assessor=h?actor:'npc';c.version++;if(c.consultation)post(s,key,now,'Verified clinical consultation',[{account:'consultation:'+c.id,amount:-c.consultation},{account:'company:'+h!.company,amount:c.consultation}]);return{message:'Recorded game condition: '+c.condition+'. '+(c.referral?'Emergency NPC referral available.':'Treatment needs separate patient consent and funding.')};}
 if(cmd.type==='AcceptTreatment'){if(actor!==c.patient||c.status!=='assessed'||c.transport)throw new DomainError('CARE_CONSENT','Only the assessed patient can accept an available treatment.');provider(s,c.provider,c.region);const patient=s.citizens[c.patient],fee=h?HEALTH_RULES.treatment:now<patient.protectionEndsAt||(s.balances['citizen:'+actor]??0)<HEALTH_RULES.npcTreatment?0:HEALTH_RULES.npcTreatment;if(p.acceptedFee!==fee||p.acceptTerms!==true)throw new DomainError('CARE_TERMS','Accept the exact treatment cost, supply requirements and one-minute recovery.');if(fee)post(s,key,now,'Reserved clinical treatment',[{account:'citizen:'+actor,amount:-fee},{account:'treatment:'+c.id,amount:fee}]);c.fee=fee;c.status='funded';c.version++;return{message:'Treatment payment reserved. No health reward or provider earnings occur before the verified procedure.'};}
 if(cmd.type==='TreatPatient'){if(c.status!=='funded'||p.choice!==0)throw new DomainError('TREATMENT_PROCEDURE','Use the approved game procedure for a funded, consented episode.');if(h&&(!staff(s,actor,h,now)||!h.active))throw new DomainError('CLINICAL_PERMISSION','Current treating staff are required.',403);if(!h&&actor!==c.patient)throw new DomainError('CARE_PERMISSION','Only the patient requests this NPC procedure.',403);presence(s,c,actor,h,now);const period=c.patient+':'+Math.floor(now/DAY);if((m.patientUse[period]??0)>=HEALTH_RULES.patientDailyTreatments)throw new DomainError('TREATMENT_DAILY_LIMIT','Four clinical procedures per day are supported. Basic care remains available.');if(h){consumeSupply(s,'company:'+h.company,h.region,'medicine',2,now,key+':medicine');consumeSupply(s,'company:'+h.company,h.region,'energy',2,now,key+':power');}else npcSupplies(s,c,now,key);m.patientUse[period]=(m.patientUse[period]??0)+1;c.status='recovering';c.recoveryAt=now+Math.ceil(HEALTH_RULES.recoveryTime*(1+(100-(h?.quality??100))/100));c.version++;return{message:'Actual supplies committed. Recorded recovery time must pass before health and fees settle.'};}
 if(cmd.type==='CompleteRecovery'){if(c.status!=='recovering'||now<c.recoveryAt!)throw new DomainError('RECOVERY_PENDING','The verified recovery interval is still in progress.');if(c.fee)post(s,key,now,'Verified clinical recovery settlement',[{account:'treatment:'+c.id,amount:-c.fee},{account:h?'company:'+h.company:'system:clinical-provider',amount:c.fee}]);const patient=s.citizens[c.patient];citizenLife(s,patient,now);activeNeeds(patient,now);patient.life!.needs.health=Math.min(100,patient.life!.needs.health+40);patient.life!.needs.energy=Math.min(100,patient.life!.needs.energy+20);c.status='completed';c.version++;return{message:'Verified recovery improved game health and settled earned care once.'};}
 if(['CancelHealthcare','TransferCareToNPC'].includes(cmd.type)){if(actor!==c.patient||!['queued','assessed','funded'].includes(c.status)||c.transport)throw new DomainError('CARE_COMMITTED','Only the patient can cancel or transfer care before a procedure or transport starts.');const consultation=c.status==='queued'?c.consultation:0,fee=c.status==='funded'?c.fee:0;if(consultation+fee)post(s,key,now,'Unearned clinical fees refunded',[{account:'consultation:'+c.id,amount:-consultation},{account:'treatment:'+c.id,amount:-fee},{account:'citizen:'+actor,amount:consultation+fee}]);c.fee=0;if(cmd.type==='CancelHealthcare'){c.status='cancelled';c.version++;return{message:'Unearned fees returned. Completed consultation and committed supplies are not recreated.'};}c.provider='npc';c.region=pos.region;c.consultation=0;c.status=c.condition?'assessed':'queued';c.version++;return{message:'NPC continuation preserved the existing assessment and returned unused private treatment funds.'};}
 if(cmd.type==='RequestEmergencyTransport'){if(actor!==c.patient||c.status!=='assessed'||c.condition!=='urgent'||c.region!==pos.region||c.transport||s.world!.activeTrips[actor])throw new DomainError('EMERGENCY_ELIGIBILITY','An evidenced urgent assessment and free location lease are required.');const tripId='emergency_'+id(key);s.world!.trips[tripId]={id:tripId,actor,origin:pos.region,destination:pos.region,departAt:now,arriveAt:now+10000,fee:0,status:'travelling',leaseVersion:pos.leaseVersion,careCaseId:c.id};s.world!.activeTrips[actor]=tripId;c.transport=tripId;c.version++;return{message:'Free regional emergency transport recorded. One location lease remains locked until arrival.'};}
 throw new Error('Unreachable healthcare command');
}
export function settleEmergencyTransport(s:State,tripId:string,cancel:boolean){const trip=s.world!.trips[tripId];if(!trip.careCaseId)return;const c=get(s).cases[trip.careCaseId];if(!c||c.transport!==trip.id||c.patient!==trip.actor)throw new Error('Emergency episode mismatch');c.transport=null;if(!cancel){c.provider='npc';c.consultation=0;c.region=trip.destination;}c.version++;}
export function healthcareView(s:State,actor:string,now:number){if(!s.citizens[actor])return null;const m=s.healthcare??{hospitals:{},cases:{},npcUse:{},patientUse:{}},region=s.world?.positions[actor]?.region??s.citizens[actor].state,providers=[{id:'npc',name:'NPC community clinic',region,consultation:0,treatment:now<s.citizens[actor].protectionEndsAt||(s.balances['citizen:'+actor]??0)<HEALTH_RULES.npcTreatment?0:HEALTH_RULES.npcTreatment},...Object.values(m.hospitals).filter(h=>h.region===region&&h.active).map(h=>({id:h.id,name:s.commerce!.companies[h.company].name,region:h.region,consultation:HEALTH_RULES.consultation,treatment:HEALTH_RULES.treatment}))];return{rules:HEALTH_RULES,providers,hospitals:Object.values(m.hospitals).filter(h=>s.commerce?.companies[h.company].members[actor]).map(h=>({...h,clinicalStaff:staff(s,actor,h,now)})),cases:Object.values(m.cases).filter(c=>c.patient===actor||c.provider!=='npc'&&clinicalAccess(s,actor,c,m.hospitals[c.provider],now)).map(c=>({...c,patient:s.citizens[c.patient].id,patientName:s.citizens[c.patient].name,assessor:c.assessor==='npc'?'npc':c.assessor?s.citizens[c.assessor]?.id:null,canTreat:c.provider==='npc'?c.patient===actor:clinicalAccess(s,actor,c,m.hospitals[c.provider],now),quote:providers.find(p=>p.id===c.provider)?.treatment??0}))};}
export function reconcileHealthcare(s:State){for(const c of Object.values(s.healthcare?.cases??{})){if(!s.citizens[c.patient]||c.provider!=='npc'&&!s.healthcare?.hospitals[c.provider])throw new Error('Healthcare episode mismatch');if((s.balances['consultation:'+c.id]??0)!==(c.status==='queued'?c.consultation:0)||(s.balances['treatment:'+c.id]??0)!==(['funded','recovering'].includes(c.status)?c.fee:0))throw new Error('Healthcare reserve mismatch');if(c.transport&&s.world?.trips[c.transport]?.careCaseId!==c.id)throw new Error('Emergency transport mismatch');}}
