import {createHmac,createHash} from 'node:crypto';
import type {State} from './domain.ts';
import {DAY} from './rules.ts';
export type Incident={id:string;actor:string;owner:string;asset:string;kind:'vehicle-breakdown'|'property-fire';at:number;severity:number;loss:number;healthBefore:number;healthAfter:number;source:string;invoice?:{actor:string;amount:number;command:string;at:number};version:number};
export type IncidentState={records:Record<string,Incident>;lastExposure:Record<string,number>};
export const getIncidents=(s:State)=>s.incidents??={records:{},lastExposure:{}};
export function incidentRoll(s:State,source:string){return parseInt(createHmac('sha256',s.life!.seed).update('incident:'+source).digest('hex').slice(0,8),16)%100;}
export function recordIncident(s:State,actor:string,owner:string,asset:string,kind:Incident['kind'],at:number,loss:number,source:string){const m=getIncidents(s);if(m.lastExposure[asset]!==undefined&&at-m.lastExposure[asset]<DAY)return null;const citizen=s.citizens[actor],before=citizen.life!.needs.health,floor=at<citizen.protectionEndsAt?80:60,after=Math.max(floor,before-20);citizen.life!.needs.health=after;const incidentId='incident_'+createHash('sha256').update(source).digest('hex').slice(0,24);m.records[incidentId]={id:incidentId,actor,owner,asset,kind,at,severity:20,loss,healthBefore:before,healthAfter:after,source,version:1};m.lastExposure[asset]=at;return incidentId;}
export function incidentsView(s:State,actor:string){return{records:Object.values(s.incidents?.records??{}).filter(i=>i.actor===actor||i.owner===actor).map(i=>({...i,actor:s.citizens[i.actor].id,owner:s.citizens[i.owner].id,source:undefined,invoice:i.invoice?{actor:s.citizens[i.invoice.actor]?.id,amount:i.invoice.amount,at:i.invoice.at}:undefined})),rules:'Server-recorded condition exposure only. At most one incident per asset daily; health has a protective floor. Incidents never create a conviction or automatic wallet debit.'};}
export function reconcileIncidents(s:State){for(const i of Object.values(s.incidents?.records??{}))if(!s.citizens[i.actor]||!s.citizens[i.owner]||!Number.isSafeInteger(i.loss)||i.loss<0||i.healthAfter>i.healthBefore||i.healthAfter<60)throw new Error('Incident evidence mismatch');for(const i of Object.values(s.incidents?.records??{}))if(i.invoice){const receipt=s.commands[i.invoice.command]?.receipt;if(!receipt||receipt.actorId!==i.invoice.actor||receipt.detail.fee!==i.invoice.amount||!['RepairProperty','CompleteVehicleRepair'].includes(receipt.type)||(receipt.detail.propertyId??receipt.detail.vehicleId)!==i.asset)throw new Error('Incident paid invoice mismatch');}}

export function recordIncidentExpense(s:State,actor:string,asset:string,amount:number,command:string,now:number){const incident=Object.values(s.incidents?.records??{}).filter(i=>i.asset===asset&&!i.invoice&&now>=i.at&&now-i.at<=7*DAY).sort((a,b)=>b.at-a.at)[0];if(incident){incident.invoice={actor,amount,command,at:now};incident.version++;}return incident?.id??null;}
