import {createHash} from 'node:crypto';
import {DomainError,post} from './domain.ts';
import type {State,Command} from './domain.ts';
import {DAY} from './rules.ts';
import {companyPermission} from './commerce.ts';
import {hasLicence} from './education.ts';
export const INSURANCE_RULES={version:'insurance-1.0',premium:5000,limit:50000,excess:5000,duration:30*DAY,waiting:DAY,filing:7*DAY,appealWindow:7*DAY,reserveBps:10000,npcDailyBacking:1000000};
type Insurer={id:string;company:string;active:boolean;version:number};
export type Policy={id:string;actor:string;provider:string;coverage:'health'|'vehicle'|'property';asset:string|null;startsAt:number;expiresAt:number;premium:number;premiumEarned:boolean;limit:number;remaining:number;excess:number;status:'active'|'cancelled'|'closed';version:number};
type Claim={id:string;policy:string;actor:string;reference:string;kind:'health'|'vehicle'|'property';status:'submitted'|'evidence-requested'|'investigated'|'approved'|'denied'|'paid'|'appealed';submittedAt:number;evidence:string[];investigator:string|null;findings:string|null;eligible:boolean;payout:number;appealUsed:boolean;decidedAt?:number;version:number};
export type InsuranceState={providers:Record<string,Insurer>;policies:Record<string,Policy>;claims:Record<string,Claim>;npcBacking:Record<string,number>;risk:{id:string;reason:string;at:number;reference:string}[]};
const get=(s:State)=>s.insurance??={providers:{},policies:{},claims:{},npcBacking:{},risk:[]};
const id=(key:string)=>createHash('sha256').update(key).digest('hex').slice(0,24);
function provider(s:State,providerId:string){if(providerId==='npc')return{account:'system:npc-insurance-capital',active:true};const p=get(s).providers[providerId];if(!p)throw new DomainError('INSURER_NOT_FOUND','Choose a registered insurer.');return{account:'company:'+p.company,active:p.active&&s.commerce?.companies[p.company]?.status!=='closed'};}
function handler(s:State,actor:string,policy:Policy,now:number){if(s.life?.blocks[actor]?.includes(policy.actor)||s.life?.blocks[policy.actor]?.includes(actor))return false;if(policy.provider==='npc')return false;const p=get(s).providers[policy.provider],company=s.commerce?.companies[p?.company];return !!company&&hasLicence(s,actor,'insurance',now)&&['founder','cofounder','ceo','manager'].includes(company.members[actor]);}
function evidence(s:State,policy:Policy,reference:string,now:number){let amount=0,at=0,reason='',links:string[]=[];
 if(policy.coverage==='health'){const c=s.healthcare?.cases[reference];if(!c||c.patient!==policy.actor||c.status!=='completed')return{eligible:false,payout:0,reason:'A completed own clinical episode and settled invoice are required.',links};at=c.exposureAt??c.createdAt;amount=c.fee+(c.paidConsultation??0);links=['healthcare.case:'+c.id,...(c.incidentId?['incident.record:'+c.incidentId]:[])];if(c.condition==='routine')reason='Routine elective care is excluded by the published policy.';}
 else{const i=s.incidents?.records[reference],expected=policy.coverage==='vehicle'?'vehicle-breakdown':'property-fire';if(!i||i.kind!==expected||i.owner!==policy.actor||i.asset!==policy.asset||!i.invoice||i.invoice.actor!==policy.actor)return{eligible:false,payout:0,reason:'An owned covered asset, server incident and own settled repair invoice are required.',links};at=i.at;amount=Math.min(i.loss,i.invoice.amount);links=['incident.record:'+i.id,'command:'+i.invoice.command];}
 if(at<policy.startsAt+INSURANCE_RULES.waiting||at>=policy.expiresAt)reason='Exposure predates the waiting period or is outside the coverage interval.';if(now>at+INSURANCE_RULES.filing)reason='The seven-day filing window expired.';if(policy.status!=='active')reason='This policy is no longer active.';const already=Object.values(get(s).claims).filter(c=>c.reference===reference&&['approved','paid'].includes(c.status)).reduce((n,c)=>n+c.payout,0),payout=Math.min(policy.remaining,Math.max(0,amount-policy.excess-already));if(!payout&&!reason)reason='The excess, prior reimbursement or remaining coverage leaves no payable amount.';return{eligible:!reason&&payout>0,payout:reason?0:payout,reason:reason||'Server episode/incident, paid invoice, ownership, interval and remaining funded coverage reconcile.',links};
}
export function insuranceCommand(s:State,actor:string,c:Command,now:number,key:string):Record<string,unknown>|undefined{
 const types=['RegisterInsurer','CloseInsurer','BuyInsurance','EarnPolicyPremium','CancelInsurance','CloseExpiredPolicy','SubmitClaim','RequestClaimEvidence','SupplyClaimEvidence','InvestigateClaim','NPCInvestigateClaim','DecideClaim','PayClaim','AppealClaim'];if(!types.includes(c.type))return;
 if(!s.citizens[actor])throw new DomainError('CITIZEN_REQUIRED','Create your citizen first.');const m=get(s),p=c.payload;
 if(c.type==='RegisterInsurer'){const company=companyPermission(s,actor,String(p.companyId),'govern',now);if(company.sector!=='finance'||!hasLicence(s,actor,'insurance',now))throw new DomainError('INSURANCE_LICENCE_REQUIRED','A finance company and current insurance licence are required.');if((s.balances['company:'+company.id]??0)<500000)throw new DomainError('INSURANCE_CAPITAL','Retain at least ₦5,000 operating capital.');if(Object.values(m.providers).some(i=>i.company===company.id))throw new DomainError('INSURER_EXISTS','This company already has an insurer.');const insurerId='insurer_'+id(key);m.providers[insurerId]={id:insurerId,company:company.id,active:true,version:1};return{insurerId,message:'Insurer registered. Each policy reserves its entire maximum liability before coverage is sold.'};}
 if(c.type==='CloseInsurer'){const insurer=m.providers[String(p.insurerId)];if(!insurer)throw new DomainError('INSURER_NOT_FOUND','Choose your insurer.');companyPermission(s,actor,insurer.company,'govern',now);insurer.active=false;insurer.version++;return{message:'New sales closed. Customer policy and approved-claim reserves remain protected and payable.'};}
 if(c.type==='BuyInsurance'){const coverage=String(p.coverage);if(!['health','vehicle','property'].includes(coverage))throw new DomainError('POLICY_COVERAGE','Choose the listed game coverage.');const asset=coverage==='vehicle'?s.mobility?.vehicles[String(p.assetId)]:coverage==='property'?s.property?.assets[String(p.assetId)]:null;if(coverage!=='health'&&(!asset||asset.owner!==actor))throw new DomainError('POLICY_OWNERSHIP','Only the recorded asset owner can insure this asset.');if(Object.values(m.policies).some(x=>x.actor===actor&&x.coverage===coverage&&x.asset===(asset?.id??null)&&x.status==='active'&&x.expiresAt>now))throw new DomainError('POLICY_ACTIVE','Equivalent current coverage already exists.');const source=provider(s,String(p.providerId));if(!source.active)throw new DomainError('INSURER_CLOSED','This insurer stopped new sales.');if(p.acceptedPremium!==INSURANCE_RULES.premium||p.acceptedLimit!==INSURANCE_RULES.limit||p.acceptedExcess!==INSURANCE_RULES.excess||p.acceptTerms!==true)throw new DomainError('POLICY_TERMS','Accept premium, excess, maximum cover, one-day waiting period, exclusions, filing and refund terms.');const policyId='policy_'+id(key),period=String(Math.floor(now/DAY));if(p.providerId==='npc'){if((m.npcBacking[period]??0)+INSURANCE_RULES.limit>INSURANCE_RULES.npcDailyBacking)throw new DomainError('INSURANCE_BUDGET','NPC period backing is fully committed. No unfunded coverage is sold.');m.npcBacking[period]=(m.npcBacking[period]??0)+INSURANCE_RULES.limit;}
  post(s,key,now,'Fully backed virtual insurance and premium reserve',[{account:'citizen:'+actor,amount:-INSURANCE_RULES.premium},{account:'policy-premium:'+policyId,amount:INSURANCE_RULES.premium},{account:source.account,amount:-INSURANCE_RULES.limit},{account:'policy:'+policyId,amount:INSURANCE_RULES.limit}]);m.policies[policyId]={id:policyId,actor,provider:String(p.providerId),coverage:coverage as Policy['coverage'],asset:asset?.id??null,startsAt:now,expiresAt:now+INSURANCE_RULES.duration,premium:INSURANCE_RULES.premium,premiumEarned:false,limit:INSURANCE_RULES.limit,remaining:INSURANCE_RULES.limit,excess:INSURANCE_RULES.excess,status:'active',version:1};if(coverage==='vehicle')s.mobility!.vehicles[asset!.id].insurance=policyId;return{policyId,message:'Maximum cover is fully reserved. Premium remains refundable during the first day before any claim.'};
 }
 if(['EarnPolicyPremium','CancelInsurance','CloseExpiredPolicy','SubmitClaim'].includes(c.type)){
  const policy=m.policies[String(p.policyId)];if(!policy||!(policy.actor===actor||handler(s,actor,policy,now)))throw new DomainError('POLICY_PERMISSION','Only the insured citizen or qualified provider staff may access this policy.',403);const source=provider(s,policy.provider);
  if(c.type==='EarnPolicyPremium'){if(policy.premiumEarned||policy.status!=='active'||now<policy.startsAt+DAY)throw new DomainError('PREMIUM_PENDING','Premium becomes earned after the disclosed first-day interval.');post(s,key,now,'Earned insurance premium',[{account:'policy-premium:'+policy.id,amount:-policy.premium},{account:policy.provider==='npc'?'system:npc-insurance-premiums':source.account,amount:policy.premium}]);policy.premiumEarned=true;policy.version++;return{message:'Earned premium released; coverage and claim reserves were preserved.'};}
  if(c.type==='CancelInsurance'){if(actor!==policy.actor||policy.status!=='active'||policy.premiumEarned||now>=policy.startsAt+DAY||Object.values(m.claims).some(x=>x.policy===policy.id))throw new DomainError('POLICY_COMMITTED','Cancellation requires your first-day unearned premium with no claim.');post(s,key,now,'Uncommitted insurance cancellation',[{account:'policy:'+policy.id,amount:-policy.remaining},{account:source.account,amount:policy.remaining},{account:'policy-premium:'+policy.id,amount:-policy.premium},{account:'citizen:'+actor,amount:policy.premium}]);policy.remaining=0;policy.status='cancelled';policy.version++;if(policy.coverage==='vehicle'&&s.mobility?.vehicles[policy.asset!]?.insurance===policy.id)s.mobility.vehicles[policy.asset!].insurance=null;return{message:'Premium refunded and unused backing returned without new money.'};}
  if(c.type==='CloseExpiredPolicy'){if(policy.status!=='active'||now<policy.expiresAt+INSURANCE_RULES.filing||Object.values(m.claims).some(x=>x.policy===policy.id&&(!['paid','denied'].includes(x.status)||(x.status==='denied'&&!x.appealUsed&&now<(x.decidedAt??now)+INSURANCE_RULES.appealWindow))))throw new DomainError('POLICY_OBLIGATIONS','The filing window and all unsettled claim obligations must finish first.');const premium=policy.premiumEarned?0:policy.premium;if(policy.remaining+premium)post(s,key,now,'Expired insurance obligation resolution',[{account:'policy:'+policy.id,amount:-policy.remaining},{account:'policy-premium:'+policy.id,amount:-premium},{account:policy.provider==='npc'?'system:npc-insurance-capital':source.account,amount:policy.remaining+premium}]);policy.remaining=0;policy.premiumEarned=true;policy.status='closed';policy.version++;if(policy.coverage==='vehicle'&&s.mobility?.vehicles[policy.asset!]?.insurance===policy.id)s.mobility.vehicles[policy.asset!].insurance=null;return{message:'Expired unused reserves released after the filing window; paid claims remain in history.'};}
  if(actor!==policy.actor||policy.status!=='active'||p.consent!==true)throw new DomainError('CLAIM_CONSENT','Only the insured citizen may consent to a claim and scoped evidence review.');const reference=String(p.referenceId);if(!reference||reference==='undefined'||Object.values(m.claims).some(x=>x.actor===actor&&x.reference===reference))throw new DomainError('CLAIM_DUPLICATE','One reviewable claim per insured expense reference is supported.');const claimId='claim_'+id(key),facts=evidence(s,policy,reference,now);m.claims[claimId]={id:claimId,policy:policy.id,actor,reference,kind:policy.coverage,status:'submitted',submittedAt:now,evidence:facts.links,investigator:null,findings:null,eligible:false,payout:0,appealUsed:false,version:1};if(!facts.links.length)m.risk.push({id:'risk_'+id(key),reason:'Missing server evidence; independent review required, no automatic fraud finding or confiscation.',at:now,reference:claimId});return{claimId,message:'Claim submitted. Game invoices and incident records are checked; this does not imply approval or a fraud conviction.'};
 }
 const claim=m.claims[String(p.claimId)],policy=claim?m.policies[claim.policy]:null;if(!claim||!policy||!(claim.actor===actor||handler(s,actor,policy,now)))throw new DomainError('CLAIM_PERMISSION','Only the insured citizen or current qualified reviewing staff may access this claim.',403);
 if(c.type==='RequestClaimEvidence'){if(!handler(s,actor,policy,now)||actor===claim.actor||!['submitted','investigated'].includes(claim.status))throw new DomainError('INVESTIGATOR_PERMISSION','An independent qualified reviewer may request scoped evidence.',403);claim.status='evidence-requested';claim.findings='Provide the linked official completed episode or repair invoice; private messages and unrelated records are not required.';claim.version++;return{message:claim.findings};}
 if(c.type==='SupplyClaimEvidence'){if(actor!==claim.actor||claim.status!=='evidence-requested'||p.consent!==true)throw new DomainError('CLAIM_EVIDENCE','Only the claimant may consent to linked official evidence.');const facts=evidence(s,policy,claim.reference,claim.submittedAt);claim.evidence=facts.links;claim.status='submitted';claim.version++;return{message:'Official evidence linked without accepting client-supplied amounts or diagnoses.'};}
 if(['InvestigateClaim','NPCInvestigateClaim'].includes(c.type)){if(!['submitted','evidence-requested','appealed',...(c.type==='NPCInvestigateClaim'?['investigated']:[])].includes(claim.status))throw new DomainError('CLAIM_REVIEW_CLOSED','Only a submitted or appealed claim can be investigated.');if(c.type==='InvestigateClaim'&&(!handler(s,actor,policy,now)||actor===claim.actor))throw new DomainError('REVIEW_CONFLICT','Use independent NPC review for a conflict or absent insurer staff.',403);if(claim.status==='appealed'&&c.type!=='NPCInvestigateClaim')throw new DomainError('INDEPENDENT_APPEAL','Appeals require separate NPC review.');const facts=evidence(s,policy,claim.reference,claim.submittedAt);claim.evidence=facts.links;claim.eligible=facts.eligible;claim.payout=facts.payout;claim.findings=facts.reason;claim.investigator=c.type==='NPCInvestigateClaim'?'npc':actor;claim.status='investigated';claim.version++;return{message:'Evidence investigated: '+facts.reason};}
 if(c.type==='DecideClaim'){if(claim.status!=='investigated'||p.choice!==0||claim.investigator!=='npc'&&(!handler(s,actor,policy,now)||actor===claim.actor))throw new DomainError('CLAIM_DECISION','Record the official investigated decision through an independent eligible reviewer.');const facts=evidence(s,policy,claim.reference,claim.submittedAt);claim.eligible=facts.eligible;claim.payout=facts.payout;claim.findings=facts.reason;claim.decidedAt=now;if(facts.eligible){post(s,key,now,'Approved insurance payout reserve',[{account:'policy:'+policy.id,amount:-facts.payout},{account:'claim:'+claim.id,amount:facts.payout}]);policy.remaining-=facts.payout;policy.version++;claim.status='approved';}else claim.status='denied';claim.version++;return{message:claim.status==='approved'?'Verified payout approved and fully reserved.':'Claim denied with a recorded factual reason and one independent appeal.'};}
 if(c.type==='PayClaim'){if(claim.status!=='approved')throw new DomainError('CLAIM_NOT_APPROVED','Only a funded approved claim may be paid.');post(s,key,now,'Reserved insurance reimbursement',[{account:'claim:'+claim.id,amount:-claim.payout},{account:'citizen:'+claim.actor,amount:claim.payout}]);claim.status='paid';claim.version++;return{amount:claim.payout,message:'Reserved reimbursement paid once, including when an insurer stops new sales.'};}
 if(c.type==='AppealClaim'){if(actor!==claim.actor||claim.status!=='denied'||claim.appealUsed||now>(claim.decidedAt??0)+INSURANCE_RULES.appealWindow)throw new DomainError('CLAIM_APPEAL_UNAVAILABLE','Only a denied claimant can use their independent appeal once.');claim.appealUsed=true;claim.status='appealed';claim.version++;return{message:'Independent appeal opened. NPC review cannot grant arbitrary payouts or erase evidence.'};}
 throw new Error('Unreachable insurance command');
}
export function insuranceView(s:State,actor:string,now:number){const m=s.insurance??{providers:{},policies:{},claims:{},npcBacking:{},risk:[]};return{rules:INSURANCE_RULES,providers:[{id:'npc',name:'Budgeted NPC insurer',active:true},...Object.values(m.providers).map(p=>({...p,active:p.active&&s.commerce?.companies[p.company].status!=='closed',name:s.commerce?.companies[p.company].name}))],policies:Object.values(m.policies).filter(p=>p.actor===actor||handler(s,actor,p,now)).map(p=>({...p,actor:s.citizens[p.actor].id})),claims:Object.values(m.claims).filter(c=>c.actor===actor||handler(s,actor,m.policies[c.policy],now)).map(c=>({...c,actor:s.citizens[c.actor].id,evidence:c.evidence.map(e=>e.startsWith('command:')?'receipt:'+id(e):e),investigator:c.investigator==='npc'?'npc':c.investigator?s.citizens[c.investigator]?.id:null,canReview:handler(s,actor,m.policies[c.policy],now)&&c.actor!==actor})),references:[...Object.values(s.healthcare?.cases??{}).filter(c=>c.patient===actor&&c.status==='completed').map(c=>({id:c.id,kind:'health',name:'Clinical episode '+c.condition})),...Object.values(s.incidents?.records??{}).filter(i=>i.owner===actor&&i.invoice).map(i=>({id:i.id,kind:i.kind==='vehicle-breakdown'?'vehicle':'property',asset:i.asset,name:i.kind+' repair'}))]};}
export function reconcileInsurance(s:State){const m=s.insurance;if(!m)return;for(const p of Object.values(m.policies)){const committed=Object.values(m.claims).filter(c=>c.policy===p.id&&['approved','paid'].includes(c.status)).reduce((n,c)=>n+c.payout,0);if(!Number.isSafeInteger(p.remaining)||p.remaining<0||p.remaining+committed>p.limit||(p.status==='active'&&p.remaining+committed!==p.limit)||(s.balances['policy:'+p.id]??0)!==p.remaining||(s.balances['policy-premium:'+p.id]??0)!==(p.status==='active'&&!p.premiumEarned?p.premium:0))throw new Error('Insurance backing mismatch');}for(const c of Object.values(m.claims))if(!m.policies[c.policy]||(s.balances['claim:'+c.id]??0)!==(c.status==='approved'?c.payout:0))throw new Error('Approved insurance reserve mismatch');}
