import {createHash} from 'node:crypto';
import {DomainError,post} from './domain.ts';
import type {State,Command} from './domain.ts';
import type {Trip} from './world.ts';
import {DAY} from './rules.ts';
import {positionFor,travelQuote} from './world.ts';
import {REGIONS} from './geography.ts';
import {hasLicence} from './education.ts';
import {getCommerce,consumeSupply} from './commerce.ts';
import {incidentRoll,recordIncident,getIncidents,recordIncidentExpense} from './incidents.ts';
import {stockPost} from './stock.ts';
export const VEHICLES=[{id:'compact',name:'Compact car',price:300000,tank:50,consumptionBps:600},{id:'van',name:'Delivery van',price:800000,tank:100,consumptionBps:1000}];
type Vehicle={id:string;model:string;owner:string;region:string;condition:number;fuel:number;fuelExpiresAt:number;tank:number;permitted:string[];status:'parked'|'travelling'|'reserved';trip:string|null;insurance:string|null;version:number};
type DriverInvite={id:string;vehicle:string;sender:string;recipient:string;expiresAt:number;status:'invited'|'accepted'|'declined';version:number};
type VehicleSale={id:string;vehicle:string;seller:string;price:number;status:'open'|'reserved'|'sold'|'cancelled';buyer:string|null;expiresAt:number;version:number};
type Repair={id:string;vehicle:string;customer:string;provider:string;fee:number;readyAt:number;status:'reserved'|'completed'|'refunded';version:number};
export type MobilityState={vehicles:Record<string,Vehicle>;invites:Record<string,DriverInvite>;sales:Record<string,VehicleSale>;repairs:Record<string,Repair>;npcStock:Record<string,number>};
const get=(s:State)=>s.mobility??={vehicles:{},invites:{},sales:{},repairs:{},npcStock:{}};
const hash=(key:string)=>createHash('sha256').update(key).digest('hex').slice(0,24);
const amount=(x:unknown,min=1,max=10000000)=>{if(!Number.isSafeInteger(x)||(x as number)<min||(x as number)>max)throw new DomainError('INVALID_AMOUNT','Use a whole amount within the displayed range.',400);return x as number;};
const blocks=(s:State,a:string,b:string)=>s.life?.blocks[a]?.includes(b)||s.life?.blocks[b]?.includes(a);
function vehicle(s:State,actor:string,id:unknown,ownerOnly=false){const v=get(s).vehicles[String(id)];if(!v||(ownerOnly?v.owner!==actor:!v.permitted.includes(actor))||(v.owner!==actor&&blocks(s,actor,v.owner)))throw new DomainError('VEHICLE_PERMISSION','Recorded ownership or current driver permission is required.',403);return v;}
function parked(s:State,v:Vehicle){if(Object.values(s.furnishing?.parking??{}).some(r=>r.vehicleId===v.id&&r.status==='parked'))throw new DomainError('VEHICLE_IN_PARKING','Retrieve the vehicle from its home parking space first.');if(v.status!=='parked'||Object.values(get(s).repairs).some(r=>r.vehicle===v.id&&r.status==='reserved'))throw new DomainError('VEHICLE_BUSY','Finish the journey, reservation or repair first.');}
export function vehicleQuote(s:State,v:Vehicle,destination:string){const route=travelQuote(v.region,destination,s),model=VEHICLES.find(x=>x.id===v.model)!,fuel=Math.ceil(route.distance*model.consumptionBps/10000),wear=Math.ceil(route.distance/100)+Math.ceil((100-(s.commerce?.roads[v.region+'>'+destination]??100))/20);return{distance:route.distance,fuel,toll:route.distance*2,duration:Math.ceil(route.duration*(1+(100-v.condition)/100)),wear:Math.max(1,Math.min(10,wear)),condition:v.condition,explanation:'Fuel follows distance and model consumption. Recorded condition and road quality affect time and wear. Fuel stays reserved until departure settlement.'};}
export function settleVehicleJourney(s:State,trip:Trip,key:string,now:number,cancel:boolean){if(!trip.vehicleId)return;const v=get(s).vehicles[trip.vehicleId];if(!v||v.trip!==trip.id||v.status!=='travelling')throw new Error('Vehicle journey ownership mismatch');const fuel=trip.vehicleFuel!;stockPost(s,{id:'vehicle-trip:'+key,goods:'fuel',at:now,reason:cancel?'Cancelled vehicle fuel reservation':'Completed vehicle fuel consumption',entries:[{account:'trip-fuel:'+trip.id,quantity:-fuel},{account:cancel?'vehicle:'+v.id:'system:vehicle-fuel-consumed',quantity:fuel}]});if(cancel)v.fuel+=fuel;else{const before=v.condition;v.condition=Math.max(20,v.condition-trip.vehicleWear!);v.region=trip.destination;const chance=Math.min(20,Math.max(0,Math.floor((70-before)/2)));if(chance>0&&incidentRoll(s,trip.id)<chance&&now-(getIncidents(s).lastExposure[v.id]??-DAY)>=DAY){const damage=Math.min(20,v.condition-20);if(damage>0){v.condition-=damage;recordIncident(s,trip.actor,v.owner,v.id,'vehicle-breakdown',now,damage*500,trip.id);}}}v.trip=null;v.status='parked';v.version++;}
export function mobilityCommand(s:State,actor:string,c:Command,now:number,key:string):Record<string,unknown>|undefined{
 const types=['BuyNPCVehicle','InviteVehicleDriver','AcceptVehicleDriver','DeclineVehicleDriver','RevokeVehicleDriver','RefuelVehicle','DisposeVehicleFuel','BeginVehicleTravel','OfferVehicleSale','ReserveVehicleSale','CompleteVehicleSale','CancelVehicleSale','RequestVehicleRepair','CompleteVehicleRepair','CancelVehicleRepair'];if(!types.includes(c.type))return;
 const citizen=s.citizens[actor];if(!citizen)throw new DomainError('CITIZEN_REQUIRED','Create your citizen first.');const m=get(s),p=c.payload,pos=positionFor(s,citizen,now);
 if(c.type==='BuyNPCVehicle'){const model=VEHICLES.find(x=>x.id===p.modelId);if(!model||p.acceptedPrice!==model.price||p.acceptTerms!==true)throw new DomainError('VEHICLE_TERMS','Accept the listed vehicle price, fuel, condition and operating requirements.');const period=pos.region+':'+Math.floor(now/DAY)+':'+model.id;if((m.npcStock[period]??0)>=20)throw new DomainError('VEHICLE_STOCK_LIMIT','This region’s finite NPC daily supply is sold out.');const vehicleId='vehicle_'+hash(key);post(s,key,now,'Recorded finite NPC vehicle purchase',[{account:'citizen:'+actor,amount:-model.price},{account:'system:vehicle-provider',amount:model.price}]);m.npcStock[period]=(m.npcStock[period]??0)+1;m.vehicles[vehicleId]={id:vehicleId,model:model.id,owner:actor,region:pos.region,condition:100,fuel:0,fuelExpiresAt:0,tank:model.tank,permitted:[actor],status:'parked',trip:null,insurance:null,version:1};return{vehicleId,message:'Vehicle title recorded at this location. It has an empty tank; driving requires a current scoped licence.'};}
 if(['AcceptVehicleDriver','DeclineVehicleDriver'].includes(c.type)){const invite=m.invites[String(p.invitationId)],v=invite?m.vehicles[invite.vehicle]:null;if(!invite||!v||invite.recipient!==actor||invite.status!=='invited'||invite.expiresAt<=now||v.owner!==invite.sender||blocks(s,actor,v.owner))throw new DomainError('INVITATION_CLOSED','This driving invitation is unavailable.');if(c.type==='AcceptVehicleDriver'){if(p.consent!==true||!hasLicence(s,actor,'driving',now))throw new DomainError('DRIVER_ELIGIBILITY','Accept scoped driving permission with a current game driving licence.');if(!v.permitted.includes(actor))v.permitted.push(actor);invite.status='accepted';v.version++;}else invite.status='declined';invite.version++;return{message:'Driving invitation decision recorded; ownership and personal assets stay separate.'};}
 if(['CompleteVehicleSale','CancelVehicleSale'].includes(c.type)){const sale=m.sales[String(p.saleId)],v=sale?m.vehicles[sale.vehicle]:null;if(!sale||!v||!['open','reserved'].includes(sale.status)||![sale.seller,sale.buyer].includes(actor))throw new DomainError('SALE_PERMISSION','Choose your active vehicle sale.',403);if(c.type==='CompleteVehicleSale'&&sale.status==='reserved'&&sale.buyer===actor&&now<sale.expiresAt){post(s,key,now,'Consented vehicle title transfer',[{account:'vehicle-sale:'+sale.id,amount:-sale.price},{account:'citizen:'+sale.seller,amount:sale.price}]);v.owner=actor;v.permitted=[actor];v.insurance=null;v.status='parked';v.version++;sale.status='sold';sale.version++;return{message:'Title transferred once. Old driver permissions and personal coverage did not transfer.'};}if(sale.status==='reserved'){if(now<sale.expiresAt&&actor!==sale.buyer)throw new DomainError('SALE_RESERVED','The buyer may complete or cancel during the reserved interval.');post(s,key,now,'Vehicle purchase refund',[{account:'vehicle-sale:'+sale.id,amount:-sale.price},{account:'citizen:'+sale.buyer,amount:sale.price}]);v.status='parked';v.version++;}sale.status='cancelled';sale.version++;return{message:'Sale cancelled and any reserved price returned to its buyer.'};}
 if(['CompleteVehicleRepair','CancelVehicleRepair'].includes(c.type)){const repair=m.repairs[String(p.repairId)],v=repair?m.vehicles[repair.vehicle]:null;if(!repair||!v||repair.customer!==actor||repair.status!=='reserved')throw new DomainError('REPAIR_UNAVAILABLE','Choose your own unfinished service.');if(c.type==='CancelVehicleRepair'){if(now>=repair.readyAt)throw new DomainError('REPAIR_COMPLETED','Earned service is payable after the completion time.');post(s,key,now,'Cancelled repair labour',[{account:'repair:'+repair.id,amount:-repair.fee},{account:'citizen:'+actor,amount:repair.fee}]);repair.status='refunded';repair.version++;return{message:'Labour refunded. Already committed material remains consumed and audited.'};}if(now<repair.readyAt)throw new DomainError('REPAIR_PENDING','The verified service is still in progress.');post(s,key,now,'Verified repair labour',[{account:'repair:'+repair.id,amount:-repair.fee},{account:repair.provider==='npc'?'system:vehicle-repair':'company:'+repair.provider,amount:repair.fee}]);v.condition=100;v.version++;repair.status='completed';repair.version++;const incidentId=recordIncidentExpense(s,actor,v.id,repair.fee,key,now);return{repairId:repair.id,vehicleId:v.id,fee:repair.fee,incidentId,message:'Verified repair restored condition and settled the funded provider once.'};}
 if(c.type==='ReserveVehicleSale'){const sale=m.sales[String(p.saleId)],v=sale?m.vehicles[sale.vehicle]:null;if(!sale||!v||sale.status!=='open'||sale.expiresAt<=now||sale.seller!==v.owner||v.owner===actor||v.region!==pos.region||blocks(s,actor,v.owner))throw new DomainError('SALE_UNAVAILABLE','Choose an available local vehicle.');parked(s,v);if(p.acceptedPrice!==sale.price||p.acceptTerms!==true)throw new DomainError('VEHICLE_TERMS','Accept the exact price, actual condition, tank and location.');post(s,key,now,'Vehicle purchase reservation',[{account:'citizen:'+actor,amount:-sale.price},{account:'vehicle-sale:'+sale.id,amount:sale.price}]);sale.status='reserved';sale.buyer=actor;sale.expiresAt=now+60000;sale.version++;v.status='reserved';v.version++;return{saleId:sale.id,message:'Price and title reserved for one minute. Review actual condition and fuel before settlement.'};}
 const ownerOnly=['InviteVehicleDriver','RevokeVehicleDriver','OfferVehicleSale'].includes(c.type),v=vehicle(s,actor,p.vehicleId,ownerOnly);
 if(c.type==='InviteVehicleDriver'){const recipient=Object.values(s.citizens).find(x=>x.id===p.citizenId);if(!recipient||recipient.actorId===actor||blocks(s,actor,recipient.actorId))throw new DomainError('DRIVER_INVITATION','Choose an eligible consenting contact.');const invitationId='driver_'+hash(key);m.invites[invitationId]={id:invitationId,vehicle:v.id,sender:actor,recipient:recipient.actorId,expiresAt:now+7*DAY,status:'invited',version:1};return{invitationId,message:'Scoped driving permission offered. Acceptance does not transfer vehicle title.'};}
 if(c.type==='RevokeVehicleDriver'){const recipient=Object.values(s.citizens).find(x=>x.id===p.citizenId);if(!recipient||recipient.actorId===actor)throw new DomainError('INVALID_TARGET','Choose another driver.');v.permitted=v.permitted.filter(x=>x!==recipient.actorId);v.version++;return{message:'Future driving permission revoked. An already-started journey can still arrive safely.'};}
 parked(s,v);if(v.region!==pos.region)throw new DomainError('VEHICLE_LOCATION','Travel to the vehicle’s recorded storage location first.');
 if(c.type==='RefuelVehicle'){const litres=amount(p.litres,1,v.tank-v.fuel),batches=Object.values(getCommerce(s).batches).filter(b=>b.owner==='citizen:'+actor&&b.region===v.region&&b.goods==='fuel'&&b.quantity>0&&b.expiresAt>now);const expiry=Math.min(...batches.map(b=>b.expiresAt));consumeSupply(s,'citizen:'+actor,v.region,'fuel',litres,now,key,'vehicle:'+v.id,'Stored vehicle fuel');v.fuelExpiresAt=v.fuel?Math.min(v.fuelExpiresAt,expiry):expiry;v.fuel+=litres;v.version++;return{message:'Actual local fuel transferred into the tank with its original shelf-life limit.'};}
 if(c.type==='DisposeVehicleFuel'){if(!v.fuel||v.fuelExpiresAt>now)throw new DomainError('FUEL_NOT_EXPIRED','Only expired tank fuel may be disposed.');stockPost(s,{id:'vehicle-disposal:'+key,goods:'fuel',at:now,reason:'Expired vehicle tank fuel',entries:[{account:'vehicle:'+v.id,quantity:-v.fuel},{account:'system:expired-fuel',quantity:v.fuel}]});v.fuel=0;v.version++;return{message:'Expired fuel disposed with quantity conservation.'};}
 if(c.type==='OfferVehicleSale'){if(Object.values(m.sales).some(x=>x.vehicle===v.id&&['open','reserved'].includes(x.status)))throw new DomainError('SALE_EXISTS','Close the current offer first.');const saleId='vehicle-sale_'+hash(key);m.sales[saleId]={id:saleId,vehicle:v.id,seller:actor,price:amount(p.price),status:'open',buyer:null,expiresAt:now+7*DAY,version:1};return{saleId,message:'Vehicle offered with recorded condition, fuel and location disclosed.'};}
 if(c.type==='RequestVehicleRepair'){const fee=Math.max(1000,(100-v.condition)*500),provider=p.providerId?getCommerce(s).companies[String(p.providerId)]:null;if(p.providerId&&(!provider||provider.sector!=='transport'||provider.region!==v.region||provider.status==='closed'||!Object.keys(provider.members).some(a=>hasLicence(s,a,'technical',now))))throw new DomainError('REPAIR_PROVIDER','Choose a local transport business with a current qualified technician.');if(p.acceptedFee!==fee)throw new DomainError('QUOTE_CHANGED','Accept the current condition-based repair labour price.');consumeSupply(s,'citizen:'+actor,v.region,'materials',1,now,key);const repairId='repair_'+hash(key);post(s,key,now,'Vehicle repair labour reservation',[{account:'citizen:'+actor,amount:-fee},{account:'repair:'+repairId,amount:fee}]);m.repairs[repairId]={id:repairId,vehicle:v.id,customer:actor,provider:provider?.id??'npc',fee,readyAt:now+60000,status:'reserved',version:1};return{repairId,message:'Material committed and labour reserved. NPC service remains available when player providers are absent.'};}
 if(c.type==='BeginVehicleTravel'){if(!hasLicence(s,actor,'driving',now))throw new DomainError('DRIVING_LICENCE_REQUIRED','Obtain a current scoped game driving licence.');if(s.world!.activeTrips[actor]||pos.interior)throw new DomainError('LOCATION_BUSY','Finish the active journey and exit to the street first.');if(v.condition<40||v.fuelExpiresAt<=now)throw new DomainError('VEHICLE_UNSAFE','Repair unsafe condition or replace expired fuel.');const quote=vehicleQuote(s,v,String(p.destination));if(p.acceptedFuel!==quote.fuel||p.acceptedToll!==quote.toll||p.acceptTerms!==true)throw new DomainError('ROUTE_TERMS','Accept the exact route fuel, toll and condition cost.');if(v.fuel<quote.fuel)throw new DomainError('FUEL_REQUIRED','The tank does not hold the actual fuel required for this route.');const tripId='vehicle-trip_'+hash(key);post(s,key,now,'Reserved vehicle route toll',[{account:'citizen:'+actor,amount:-quote.toll},{account:'escrow:'+tripId,amount:quote.toll}]);stockPost(s,{id:'vehicle-route:'+key,goods:'fuel',at:now,reason:'Vehicle route fuel reservation',entries:[{account:'vehicle:'+v.id,quantity:-quote.fuel},{account:'trip-fuel:'+tripId,quantity:quote.fuel}]});v.fuel-=quote.fuel;v.status='travelling';v.trip=tripId;v.version++;s.world!.trips[tripId]={id:tripId,actor,origin:pos.region,destination:String(p.destination),departAt:now,arriveAt:now+quote.duration,fee:quote.toll,status:'travelling',leaseVersion:pos.leaseVersion,vehicleId:v.id,vehicleFuel:quote.fuel,vehicleWear:quote.wear};s.world!.activeTrips[actor]=tripId;return{tripId,...quote,message:'One location lease locked. Vehicle, fuel and toll are reserved for the same journey.'};}
 throw new Error('Unreachable mobility command');
}
export function mobilityView(s:State,actor:string,now:number){if(!s.citizens[actor])return null;const m=s.mobility??{vehicles:{},invites:{},sales:{},repairs:{},npcStock:{}};return{models:VEHICLES,licensed:hasLicence(s,actor,'driving',now),vehicles:Object.values(m.vehicles).filter(v=>v.owner===actor||v.permitted.includes(actor)&&!blocks(s,actor,v.owner)).map(v=>({...v,owner:s.citizens[v.owner].id,permitted:v.permitted.map(a=>s.citizens[a].id),repairFee:Math.max(1000,(100-v.condition)*500),routes:REGIONS.filter(r=>r.name!==v.region).map(r=>({destination:r.name,...vehicleQuote(s,v,r.name)}))})),invitations:Object.values(m.invites).filter(i=>i.recipient===actor&&i.status==='invited'&&i.expiresAt>now).map(i=>({...i,sender:s.citizens[i.sender].id,recipient:s.citizens[i.recipient].id})),sales:Object.values(m.sales).filter(x=>x.status==='open'||x.seller===actor||x.buyer===actor).map(x=>({...x,seller:s.citizens[x.seller].id,buyer:x.buyer?s.citizens[x.buyer].id:null,vehicle:{...m.vehicles[x.vehicle],owner:s.citizens[m.vehicles[x.vehicle].owner].id,permitted:[]}})),repairs:Object.values(m.repairs).filter(x=>x.customer===actor)};}
export function reconcileMobility(s:State){const m=s.mobility;if(!m)return;for(const v of Object.values(m.vehicles)){if(!s.citizens[v.owner]||!v.permitted.includes(v.owner)||!Number.isSafeInteger(v.fuel)||v.fuel<0||v.fuel>v.tank||v.fuel!==(s.commerce?.stock?.balances['fuel:vehicle:'+v.id]??0))throw new Error('Vehicle title or fuel mismatch');if(v.status==='travelling'&&(!v.trip||s.world?.trips[v.trip]?.vehicleId!==v.id||s.world.trips[v.trip].status!=='travelling'))throw new Error('Vehicle location mismatch');}for(const sale of Object.values(m.sales))if((s.balances['vehicle-sale:'+sale.id]??0)!==(sale.status==='reserved'?sale.price:0))throw new Error('Vehicle sale reserve mismatch');for(const repair of Object.values(m.repairs))if((s.balances['repair:'+repair.id]??0)!==(repair.status==='reserved'?repair.fee:0))throw new Error('Vehicle repair reserve mismatch');for(const trip of Object.values(s.world?.trips??{}))if(trip.vehicleId&&(s.commerce?.stock?.balances['fuel:trip-fuel:'+trip.id]??0)!==(trip.status==='travelling'?trip.vehicleFuel:0))throw new Error('Vehicle route fuel mismatch');}
