import {createHash} from 'node:crypto';
import {DomainError,post} from './domain.ts';
import type {State,Command} from './domain.ts';
import {DAY} from './rules.ts';
import {positionFor} from './world.ts';
import {incidentRoll,recordIncident,getIncidents,recordIncidentExpense} from './incidents.ts';
import {consumeSupply} from './commerce.ts';
import {releaseResidence,changeResidence} from './furnishing.ts';

export const PROPERTY_RULES={version:'property-1.0',rentPeriod:7*DAY,noticePeriod:7*DAY,taxPeriod:30*DAY,taxBps:50,offlinePeriods:2,constructionTime:60000};
export type Property={id:string;region:string;kind:'land'|'home'|'warehouse';owner:string;value:number;quality:number;fireSafety:number;maintenanceAt:number;taxAt:number;taxDue:number;utilities:{connected:boolean;power:number;water:number;bill:number;lastUseAt:number};status:'available'|'building'|'ready';version:number};
type Sale={id:string;property:string;seller:string;price:number;expiresAt:number;status:'open'|'reserved'|'sold'|'withdrawn';version:number};
type Purchase={id:string;sale:string;buyer:string;price:number;tax:number;expiresAt:number;status:'reserved'|'completed'|'refunded';version:number};
type Rental={id:string;property:string;owner:string;rent:number;deposit:number;status:'open'|'closed';version:number};
type Tenancy={id:string;property:string;tenant:string;rent:number;deposit:number;startedAt:number;paidUntil:number;arrears:number;reviewedAt:number;status:'active'|'notice'|'ended';noticeAt:number|null;noticeReason:string|null;review:'none'|'requested'|'approved'|'denied'|'appealed';appealUsed?:boolean;reviewReason:string|null;version:number};
type Build={id:string;property:string;owner:string;readyAt:number;cost:number;status:'building'|'completed';version:number};
type Inspection={id:string;property:string;at:number;findings:string[];complianceAt:number;status:'repair-required'|'passed';version:number};
export type PropertyState={assets:Record<string,Property>;sales:Record<string,Sale>;purchases:Record<string,Purchase>;rentals:Record<string,Rental>;tenancies:Record<string,Tenancy>;builds:Record<string,Build>;inspections:Record<string,Inspection>};
const get=(s:State)=>s.property??={assets:{},sales:{},purchases:{},rentals:{},tenancies:{},builds:{},inspections:{}};
const id=(key:string)=>createHash('sha256').update(key).digest('hex').slice(0,24);
const amount=(x:unknown,min=1,max=100000000)=>{if(!Number.isSafeInteger(x)||(x as number)<min||(x as number)>max)throw new DomainError('INVALID_AMOUNT','Use a whole amount within the published limits.',400);return x as number;};
export function propertyCatalogue(region:string){return [{id:'npc-'+region+'-land',kind:'land' as const,value:300000},{id:'npc-'+region+'-home',kind:'home' as const,value:500000},{id:'npc-'+region+'-warehouse',kind:'warehouse' as const,value:750000}].map(x=>({...x,region,price:x.value,tax:Math.ceil(x.value*.025)}));}
const activeLease=(s:State,property:string)=>Object.values(s.property?.tenancies??{}).find(t=>t.property===property&&t.status!=='ended');
function refresh(a:Property,now:number){const days=Math.min(7,Math.max(0,Math.floor((now-a.maintenanceAt)/DAY)));if(days){a.quality=Math.max(20,a.quality-days);a.fireSafety=Math.max(20,a.fireSafety-days);a.maintenanceAt=now;a.version++;}const periods=Math.min(PROPERTY_RULES.offlinePeriods,Math.max(0,Math.floor((now-a.taxAt)/PROPERTY_RULES.taxPeriod)));if(periods){a.taxDue+=Math.ceil(a.value*PROPERTY_RULES.taxBps/10000)*periods;a.taxAt=now;a.version++;}}
function ownerAsset(s:State,actor:string,propertyId:unknown,now:number){const a=get(s).assets[String(propertyId)];if(!a||a.owner!==actor)throw new DomainError('PROPERTY_PERMISSION','Only the recorded owner may take this action.',403);refresh(a,now);return a;}
function partyLease(s:State,actor:string,tenancyId:unknown,now:number,allowEnded=false){const t=get(s).tenancies[String(tenancyId)],a=t?get(s).assets[t.property]:null;if(!t||!a||(t.status==='ended'&&!allowEnded)||![t.tenant,a.owner].includes(actor))throw new DomainError('TENANCY_PERMISSION','Choose your active tenancy.',403);const periods=Math.min(2,Math.max(0,Math.floor((now-t.paidUntil)/PROPERTY_RULES.rentPeriod)+1));if(t.status!=='ended'&&now>=t.paidUntil&&periods){t.arrears=Math.min(2*t.rent,t.arrears+periods*t.rent);t.paidUntil=now+PROPERTY_RULES.rentPeriod;t.version++;}return{t,a};}
function end(s:State,t:Tenancy,key:string,now:number,reason:string){post(s,key,now,'Protected tenancy deposit return',[{account:'deposit:'+t.id,amount:-t.deposit},{account:'citizen:'+t.tenant,amount:t.deposit}]);releaseResidence(s,t.property,t.tenant);t.status='ended';t.version++;const c=s.citizens[t.tenant];if(c.housing===t.property)c.housing='Starter accommodation';return{message:reason+' Your deposit was returned; personal funds and stored goods were preserved.',tenancyId:t.id};}
export function propertyCommand(s:State,actor:string,c:Command,now:number,key:string):Record<string,unknown>|undefined{
 const types=['SetResidence','ReservePropertyPurchase','CompletePropertyPurchase','CancelPropertyPurchase','ListProperty','WithdrawPropertySale','OfferTenancy','AcceptTenancy','PayRent','GiveTenancyNotice','ReviewTenancyNotice','AppealTenancyNotice','EnforceTenancyNotice','LeaveTenancy','StartConstruction','FinishConstruction','InspectProperty','RepairProperty','PayPropertyTax','ConnectUtilities','UseHomeUtilities','PayUtilityBill'];if(!types.includes(c.type))return;
 const citizen=s.citizens[actor];if(!citizen)throw new DomainError('CITIZEN_REQUIRED','Create a citizen first.');const m=get(s),p=c.payload,pos=positionFor(s,citizen,now);
 if(c.type==='SetResidence'){
  if(pos.interior||s.world?.activeTrips[actor])throw new DomainError('RESIDENCE_LOCATION','Return to the local street after completing your journey before moving home.');
  if(p.acceptTerms!==true)throw new DomainError('RESIDENCE_TERMS','Moving stores your furnishings and releases parking. Existing rent and tax obligations continue.');
  if(p.propertyId===null){changeResidence(s,actor,'Starter accommodation');return{housing:citizen.housing,message:'Starter accommodation selected. Your property, stored furnishings and contractual obligations remain yours.'};}
  const a=m.assets[String(p.propertyId)],tenancy=a?activeLease(s,a.id):undefined;
  if(!a||a.kind!=='home'||a.status!=='ready'||a.region!==pos.region||(tenancy?tenancy.tenant!==actor:a.owner!==actor))throw new DomainError('RESIDENCE_PERMISSION','Choose a ready local home you own without another tenant, or your contracted tenancy.',403);
  refresh(a,now);if(p.propertyVersion!==a.version)throw new DomainError('PROPERTY_CHANGED','Review the current title and tenancy before moving home.');
  changeResidence(s,actor,a.id);return{housing:a.id,message:'Residence selected. Walk to its marked street entrance. Moving does not transfer title or end rent, tax or utility obligations.'};
 }
 if(c.type==='ReservePropertyPurchase'){
  let sale=m.sales[String(p.saleId)];if(!sale){const catalog=propertyCatalogue(pos.region).find(x=>x.id===p.propertyId);if(!catalog||m.assets[catalog.id])throw new DomainError('PROPERTY_UNAVAILABLE','Choose an available unit at your location.');sale={id:'sale-'+catalog.id,property:catalog.id,seller:'npc',price:catalog.price,expiresAt:now+DAY,status:'open',version:1};m.assets[catalog.id]={id:catalog.id,region:pos.region,kind:catalog.kind,owner:'npc',value:catalog.value,quality:100,fireSafety:100,maintenanceAt:now,taxAt:now,taxDue:0,utilities:{connected:false,power:0,water:0,bill:0,lastUseAt:0},status:'ready',version:1};m.sales[sale.id]=sale;}
  const a=m.assets[sale.property];refresh(a,now);const tax=Math.ceil(sale.price*.025);if(sale.status!=='open'||sale.expiresAt<=now||a.owner!==sale.seller||a.owner===actor||a.region!==pos.region||a.status!=='ready')throw new DomainError('PROPERTY_UNAVAILABLE','This unit cannot be reserved.');if(p.acceptedTotal!==sale.price+tax||p.acceptTerms!==true)throw new DomainError('PROPERTY_TERMS','Accept the exact price, transfer tax and disclosed continuing tenancy obligations.');const purchaseId='purchase_'+id(key);post(s,key,now,'Property purchase reservation',[{account:'citizen:'+actor,amount:-(sale.price+tax)},{account:'purchase:'+purchaseId,amount:sale.price+tax}]);m.purchases[purchaseId]={id:purchaseId,sale:sale.id,buyer:actor,price:sale.price,tax,expiresAt:now+60000,status:'reserved',version:1};sale.status='reserved';sale.version++;return{purchaseId,message:'Price and tax reserved. Existing tenancy, deposit and property liabilities survive ownership transfer.'};
 }
 if(['CompletePropertyPurchase','CancelPropertyPurchase'].includes(c.type)){
  const purchase=m.purchases[String(p.purchaseId)],sale=purchase?m.sales[purchase.sale]:null;if(!purchase||!sale||purchase.buyer!==actor||purchase.status!=='reserved')throw new DomainError('PURCHASE_UNAVAILABLE','Choose your unsettled reservation.');const a=m.assets[sale.property];refresh(a,now);if(c.type==='CancelPropertyPurchase'||now>=purchase.expiresAt){post(s,key,now,'Property reservation refund',[{account:'purchase:'+purchase.id,amount:-(purchase.price+purchase.tax)},{account:'citizen:'+actor,amount:purchase.price+purchase.tax}]);purchase.status='refunded';purchase.version++;sale.status='open';sale.expiresAt=Math.max(sale.expiresAt,now+DAY);sale.version++;return{message:'Reservation refunded; title stayed with the seller.'};}
  if(a.owner!==sale.seller)throw new DomainError('TITLE_CHANGED','The seller no longer has title. Cancel for a refund.');post(s,key,now,'Property title settlement',[{account:'purchase:'+purchase.id,amount:-(purchase.price+purchase.tax)},{account:sale.seller==='npc'?'system:property-provider':'citizen:'+sale.seller,amount:purchase.price},{account:'treasury:state:'+a.region,amount:purchase.tax}]);releaseResidence(s,a.id,a.owner);a.owner=actor;a.version++;purchase.status='completed';purchase.version++;sale.status='sold';sale.version++;for(const rental of Object.values(m.rentals))if(rental.property===a.id&&rental.status==='open')rental.status='closed';if(a.kind==='home'&&!activeLease(s,a.id))changeResidence(s,actor,a.id);return{propertyId:a.id,message:'Title transferred once. Existing tenants retain their contract and protected deposit.'};
 }
 if(c.type==='ListProperty'){
  const a=ownerAsset(s,actor,p.propertyId,now),price=amount(p.price);if(a.status!=='ready'||Object.values(m.sales).some(x=>x.property===a.id&&['open','reserved'].includes(x.status)))throw new DomainError('SALE_EXISTS','Complete construction or close the existing sale first.');const saleId='sale_'+id(key);m.sales[saleId]={id:saleId,property:a.id,seller:actor,price,expiresAt:now+7*DAY,status:'open',version:1};return{saleId,message:'Title offer published with existing tenancy and liabilities disclosed.'};
 }
 if(c.type==='WithdrawPropertySale'){const sale=m.sales[String(p.saleId)];if(!sale||sale.seller!==actor||sale.status!=='open')throw new DomainError('SALE_RESERVED','Only your unreserved offer can be withdrawn.');sale.status='withdrawn';sale.version++;return{message:'Sale withdrawn.'};}
 if(c.type==='OfferTenancy'){
  const a=ownerAsset(s,actor,p.propertyId,now),rent=amount(p.rent,1000,1000000),deposit=amount(p.deposit,1,2*rent);if(a.kind!=='home'||a.status!=='ready'||activeLease(s,a.id)||a.quality<50||a.fireSafety<50)throw new DomainError('HOME_UNAVAILABLE','Only an unoccupied safe completed home may be rented.');for(const offer of Object.values(m.rentals))if(offer.property===a.id)offer.status='closed';const rentalId='rental_'+id(key);m.rentals[rentalId]={id:rentalId,property:a.id,owner:actor,rent,deposit,status:'open',version:1};return{rentalId,message:'Weekly rent and refundable deposit offered. No power to debit a tenant or seize stored goods is granted.'};
 }
 if(c.type==='AcceptTenancy'){
  const offer=m.rentals[String(p.rentalId)],a=offer?m.assets[offer.property]:null;if(!offer||!a||offer.status!=='open'||a.owner!==offer.owner||a.owner===actor||a.region!==pos.region||activeLease(s,a.id)||a.quality<50||a.fireSafety<50||Object.values(m.tenancies).some(t=>t.tenant===actor&&t.status!=='ended'))throw new DomainError('HOME_UNAVAILABLE','Choose an available safe local home and end any existing lease first.');if(s.life?.blocks[actor]?.includes(a.owner)||s.life?.blocks[a.owner]?.includes(actor))throw new DomainError('CONTACT_BLOCKED','This contract is unavailable.',403);if(p.acceptTerms!==true||p.acceptedRent!==offer.rent||p.acceptedDeposit!==offer.deposit)throw new DomainError('TENANCY_TERMS','Review the exact weekly rent, deposit, capped arrears and seven-day notice process.');const tenancyId='tenancy_'+id(key);post(s,key,now,'Accepted tenancy and protected deposit',[{account:'citizen:'+actor,amount:-(offer.rent+offer.deposit)},{account:'citizen:'+a.owner,amount:offer.rent},{account:'deposit:'+tenancyId,amount:offer.deposit}]);m.tenancies[tenancyId]={id:tenancyId,property:a.id,tenant:actor,rent:offer.rent,deposit:offer.deposit,startedAt:now,paidUntil:now+PROPERTY_RULES.rentPeriod,arrears:0,reviewedAt:now,status:'active',noticeAt:null,noticeReason:null,review:'none',reviewReason:null,version:1};offer.status='closed';offer.version++;changeResidence(s,actor,a.id);if(s.citizens[a.owner].housing===a.id){releaseResidence(s,a.id,a.owner);s.citizens[a.owner].housing='Starter accommodation';}return{tenancyId,message:'Lease accepted. One period paid; deposit remains reserved and refundable.'};
 }
 if(['PayRent','GiveTenancyNotice','ReviewTenancyNotice','AppealTenancyNotice','EnforceTenancyNotice','LeaveTenancy'].includes(c.type)){
  const {t,a}=partyLease(s,actor,p.tenancyId,now,c.type==='PayRent');
  if(c.type==='PayRent'){if(t.tenant!==actor||!t.arrears||p.acceptedAmount!==t.arrears)throw new DomainError('RENT_REVIEW','Only the tenant may accept the exact capped amount due.');const rent=t.arrears;post(s,key,now,'Consented tenancy rent',[{account:'citizen:'+actor,amount:-rent},{account:'citizen:'+a.owner,amount:rent}]);t.arrears=0;t.version++;return{amount:rent,message:'Agreed rent paid. No account was debited automatically.'};}
  if(c.type==='LeaveTenancy'){if(t.tenant!==actor)throw new DomainError('TENANT_ONLY','Only the tenant can leave voluntarily.',403);return end(s,t,key,now,'Tenancy ended voluntarily.');}
  if(c.type==='GiveTenancyNotice'){if(a.owner!==actor||!['arrears','owner-use'].includes(String(p.reason)))throw new DomainError('NOTICE_PERMISSION','Owner notice requires a published reason.',403);if(t.status==='notice')throw new DomainError('NOTICE_EXISTS','An active notice already exists.');if(p.reason==='arrears'&&t.arrears<t.rent)throw new DomainError('NO_ARREARS','There is no evidenced unpaid period.');t.status='notice';t.noticeAt=now+PROPERTY_RULES.noticePeriod;t.noticeReason=String(p.reason);t.review='requested';t.version++;return{message:'Seven-day notice recorded. Independent review and appeal must precede enforcement.'};}
  if(t.status!=='notice')throw new DomainError('NOTICE_REQUIRED','There is no active notice.');
  if(c.type==='AppealTenancyNotice'){if(actor!==t.tenant||t.review!=='approved'||t.appealUsed)throw new DomainError('APPEAL_UNAVAILABLE','Only the tenant may appeal an approved notice.');t.review='appealed';t.appealUsed=true;t.noticeAt=Math.max(t.noticeAt!,now+7*DAY);t.version++;return{message:'Appeal recorded with a further seven-day protection window. Independent factual review is required.'};}
  if(c.type==='ReviewTenancyNotice'){if(!['requested','appealed'].includes(t.review))throw new DomainError('REVIEW_CLOSED','This notice has already been reviewed.');const valid=t.noticeReason==='owner-use'||t.arrears>=t.rent;t.review=valid?'approved':'denied';t.reviewReason=valid?'Recorded title, notice reason and capped arrears support notice.':'Arrears were cured; eviction on that ground is denied.';t.reviewedAt=now;if(!valid){t.status='active';t.noticeAt=null;}t.version++;return{message:'Independent NPC review: '+t.reviewReason};}
  if(actor!==a.owner||t.review!=='approved'||now<t.noticeAt!)throw new DomainError('DUE_PROCESS_REQUIRED','Owner enforcement requires completed independent review and the full notice or appeal interval.');if(t.noticeReason==='arrears'&&t.arrears===0)throw new DomainError('ARREARS_CURED','Arrears were paid. This notice cannot be enforced.');return end(s,t,key,now,'Reviewed tenancy ended with starter shelter fallback.');
 }
 if(c.type==='StartConstruction'){const a=ownerAsset(s,actor,p.propertyId,now);if(a.kind!=='land'||a.status!=='ready'||p.acceptedLabour!==50000)throw new DomainError('BUILD_TERMS','Choose an available plot and accept the ₦500 labour reserve.');consumeSupply(s,'citizen:'+actor,a.region,'materials',5,now,key+':materials');consumeSupply(s,'citizen:'+actor,a.region,'energy',2,now,key+':energy');const buildId='build_'+id(key);post(s,key,now,'Construction labour reservation',[{account:'citizen:'+actor,amount:-50000},{account:'build:'+buildId,amount:50000}]);m.builds[buildId]={id:buildId,property:a.id,owner:actor,readyAt:now+PROPERTY_RULES.constructionTime,cost:50000,status:'building',version:1};a.status='building';a.version++;return{buildId,message:'Actual materials and power committed; labour payment reserved until completion.'};}
 if(c.type==='FinishConstruction'){const b=m.builds[String(p.buildId)];if(!b||b.owner!==actor||b.status!=='building'||now<b.readyAt)throw new DomainError('CONSTRUCTION_PENDING','Construction must reach its recorded completion time.');const a=ownerAsset(s,actor,b.property,now);post(s,key,now,'Verified construction labour',[{account:'build:'+b.id,amount:-b.cost},{account:'system:construction-provider',amount:b.cost}]);a.kind='home';a.status='ready';a.quality=100;a.fireSafety=100;a.value+=60000;a.version++;b.status='completed';b.version++;return{propertyId:a.id,message:'Home completed and safety checked. Title remains unchanged.'};}
 const a=m.assets[String(p.propertyId)];if(!a)throw new DomainError('PROPERTY_NOT_FOUND','Choose an existing property.',404);const lease=activeLease(s,a.id),occupant=a.owner===actor||lease?.tenant===actor;if(!occupant)throw new DomainError('PROPERTY_PERMISSION','Only the owner or tenant may request this service.',403);refresh(a,now);
 if(c.type==='InspectProperty'){const findings=[];if(a.quality<80)findings.push('Repair building condition');if(a.fireSafety<80)findings.push('Restore fire-safety equipment');const inspectionId='inspection_'+id(key);m.inspections[inspectionId]={id:inspectionId,property:a.id,at:now,findings,complianceAt:now+7*DAY,status:findings.length?'repair-required':'passed',version:1};return{inspectionId,findings,message:'NPC inspection records measured condition only, with seven days for repair and no invented penalty.'};}
 if(c.type==='RepairProperty'){ownerAsset(s,actor,a.id,now);if(p.acceptedFee!==10000)throw new DomainError('QUOTE_CHANGED','Accept the ₦100 service fee.');consumeSupply(s,'citizen:'+actor,a.region,'materials',2,now,key);post(s,key,now,'Property repair service',[{account:'citizen:'+actor,amount:-10000},{account:'system:repair-provider',amount:10000}]);a.quality=100;a.fireSafety=100;a.maintenanceAt=now;a.version++;for(const i of Object.values(m.inspections))if(i.property===a.id&&i.status==='repair-required'){i.status='passed';i.version++;}const incidentId=recordIncidentExpense(s,actor,a.id,10000,key,now);return{propertyId:a.id,fee:10000,incidentId,message:'Consumed repair materials restored condition and fire safety.'};}
 if(c.type==='PayPropertyTax'){ownerAsset(s,actor,a.id,now);if(!a.taxDue||p.acceptedAmount!==a.taxDue)throw new DomainError('TAX_REVIEW','Accept the exact published property tax liability.');const tax=a.taxDue;post(s,key,now,'Published property tax',[{account:'citizen:'+actor,amount:-tax},{account:'treasury:state:'+a.region,amount:tax}]);a.taxDue=0;a.version++;return{amount:tax,message:'Property tax paid; no personal account was debited without consent.'};}
 if(c.type==='ConnectUtilities'){ownerAsset(s,actor,a.id,now);if(a.utilities.connected||p.acceptedFee!==5000)throw new DomainError('UTILITY_TERMS','Accept the one-time ₦50 service connection.');post(s,key,now,'Utility connection',[{account:'citizen:'+actor,amount:-5000},{account:'system:utility-provider',amount:5000}]);a.utilities.connected=true;a.version++;return{message:'Water and power connection enabled. Usage creates a visible capped bill.'};}
 if(c.type==='UseHomeUtilities'){if(!a.utilities.connected||a.kind!=='home'||now-a.utilities.lastUseAt<DAY)throw new DomainError('UTILITY_UNAVAILABLE','Connected home services are available once per day.');const power=2,water=4,bill=power*200+water*100;if(p.acceptedBill!==bill)throw new DomainError('UTILITY_TERMS','Accept the ₦8 metered-use bill.');if(a.utilities.bill>=7*bill)throw new DomainError('UTILITY_BILL_LIMIT','Pay the existing bill before taking more optional utility use. Basic shelter and care stay available.');consumeSupply(s,'citizen:'+actor,a.region,'energy',power,now,key+':power');consumeSupply(s,'citizen:'+actor,a.region,'water',water,now,key+':water');a.utilities.power+=power;a.utilities.water+=water;a.utilities.bill+=bill;a.utilities.lastUseAt=now;a.version++;citizen.life!.needs.energy=Math.min(100,citizen.life!.needs.energy+10);if(a.fireSafety<60&&incidentRoll(s,key)<Math.min(20,60-a.fireSafety)&&now-(getIncidents(s).lastExposure[a.id]??-DAY)>=DAY){const damage=Math.min(10,a.quality-20);if(damage>0){a.quality-=damage;a.fireSafety=Math.max(20,a.fireSafety-10);recordIncident(s,actor,a.owner,a.id,'property-fire',now,damage*1000,key);}}return{propertyId:a.id,power,water,bill,incidentIds:Object.values(s.incidents?.records??{}).filter(i=>i.source===key).map(i=>i.id),message:'Actual stored power and water consumed. Optional metered service bill recorded; no automatic debit.'};}
 if(c.type==='PayUtilityBill'){if(!a.utilities.bill||p.acceptedAmount!==a.utilities.bill)throw new DomainError('UTILITY_BILL_REVIEW','Accept the exact outstanding service bill.');const bill=a.utilities.bill;post(s,key,now,'Consented utility service payment',[{account:'citizen:'+actor,amount:-bill},{account:'system:utility-service',amount:bill}]);a.utilities.bill=0;a.version++;return{amount:bill,message:'Metered service bill settled.'};}
 throw new Error('Unreachable property command');
}
export function propertyView(s:State,actor:string,now:number){if(!s.citizens[actor])return null;const copy=structuredClone(s),m=get(copy),region=positionFor(copy,copy.citizens[actor],now).region;for(const a of Object.values(m.assets))refresh(a,now);for(const t of Object.values(m.tenancies))if(t.tenant===actor||m.assets[t.property].owner===actor)if(t.status!=='ended')partyLease(copy,actor,t.id,now);return{rules:PROPERTY_RULES,catalogue:propertyCatalogue(region).filter(a=>!m.assets[a.id]),assets:Object.values(m.assets).filter(a=>a.owner===actor||activeLease(copy,a.id)?.tenant===actor).map(a=>({...a,canReside:a.kind==='home'&&a.status==='ready'&&a.region===region&&(activeLease(copy,a.id)?activeLease(copy,a.id)!.tenant===actor:a.owner===actor),owner:s.citizens[a.owner]?.id??'npc'})),sales:Object.values(m.sales).filter(x=>x.status==='open'||x.seller===actor).map(x=>({...x,seller:s.citizens[x.seller]?.id??'npc',asset:{...m.assets[x.property],owner:s.citizens[m.assets[x.property].owner]?.id??'npc'},tenancy:activeLease(copy,x.property)?{rent:activeLease(copy,x.property)!.rent,deposit:activeLease(copy,x.property)!.deposit}:null})),purchases:Object.values(m.purchases).filter(x=>x.buyer===actor),rentals:Object.values(m.rentals).filter(x=>x.status==='open'||m.assets[x.property].owner===actor).map(x=>({...x,owner:s.citizens[x.owner]?.id,region:m.assets[x.property].region})),tenancies:Object.values(m.tenancies).filter(x=>x.tenant===actor||m.assets[x.property].owner===actor).map(x=>({...x,tenant:s.citizens[x.tenant].id,owner:s.citizens[m.assets[x.property].owner]?.id})),builds:Object.values(m.builds).filter(x=>x.owner===actor),inspections:Object.values(m.inspections).filter(x=>m.assets[x.property].owner===actor||activeLease(copy,x.property)?.tenant===actor)};}
export function reconcileProperty(s:State){const m=s.property;if(!m)return;for(const a of Object.values(m.assets))if((a.owner!=='npc'&&!s.citizens[a.owner])||!Number.isSafeInteger(a.taxDue)||a.taxDue<0||!Number.isSafeInteger(a.utilities.bill)||a.utilities.bill<0)throw new Error('Property ownership or liability mismatch');for(const t of Object.values(m.tenancies)){if(!m.assets[t.property]||!s.citizens[t.tenant]||(s.balances['deposit:'+t.id]??0)!==(t.status==='ended'?0:t.deposit)||t.arrears<0||t.arrears>2*t.rent)throw new Error('Tenancy reserve mismatch');}for(const p of Object.values(m.purchases))if((s.balances['purchase:'+p.id]??0)!==(p.status==='reserved'?p.price+p.tax:0))throw new Error('Property purchase reserve mismatch');for(const b of Object.values(m.builds))if((s.balances['build:'+b.id]??0)!==(b.status==='building'?b.cost:0))throw new Error('Construction reserve mismatch');for(const a of Object.values(m.assets))if(Object.values(m.tenancies).filter(t=>t.property===a.id&&t.status!=='ended').length>1)throw new Error('Duplicate property occupancy');}
