window.EconomyUI=(()=>{
 const $=id=>document.getElementById(id),cash=n=>new Intl.NumberFormat('en-NG',{style:'currency',currency:'NGN'}).format(n/100);
 let view,send,locked;
 const paragraph=text=>{const p=document.createElement('p');p.textContent=text;return p;};
 function card(target,title,text){const box=document.createElement('article'),h=document.createElement('h3');box.className='course-record';h.textContent=title;box.append(h,paragraph(text));$(target).append(box);return box;}
 function action(box,label,type,payload,disabled=false){const b=document.createElement('button');b.type='button';b.textContent=label;b.disabled=locked||disabled;b.addEventListener('click',()=>send(type,payload));box.append(b);return b;}
 function ask(box,label,handler,disabled=false){const b=document.createElement('button');b.type='button';b.textContent=label;b.disabled=locked||disabled;b.addEventListener('click',handler);box.append(b);}
 function select(id,values){const el=$(id),old=el.value;el.replaceChildren(...values.map(([value,text])=>{const o=document.createElement('option');o.value=value;o.textContent=text;return o;}));if(values.some(([v])=>v===old))el.value=old;}
 function render(data,perform,busy){view=data;send=perform;locked=busy;if(!view.citizen)return;const m=view.commerce,e=view.employment,cid=view.citizen.id;
  select('company-sector',m.sectors.map(s=>[s,s]));select('company-select',[['','Personal inventory'],...m.companies.map(c=>[c.id,c.name])]);select('supply-goods',m.goods.filter(g=>!['devices','tourism'].includes(g.id)).map(g=>[g.id,g.name+' · '+cash(g.price)]));select('vacancy-role',e.roles.map(r=>[r.id,r.name+(r.track?' · '+r.track+' licence':'')]));
  const company=m.companies.find(c=>c.id===$('company-select').value),companyId=company?.id,managed=company&&['founder','cofounder','ceo','manager'].includes(company.role),owner=company?'company:'+company.id:'citizen:'+view.citizen.actorId;
  renderFinance();
  ['company-summary','inventory-records','production-options','production-records','market-records','quote-records','order-records','company-invitations','vacancy-records','application-records','employment-records'].forEach(id=>$(id).replaceChildren());
  if(company)$('company-summary').append(paragraph(`${company.name} · ${company.region} · ${company.sector} · ${company.role??'shareholder'} · ${cash(company.balance)} company funds · ${(company.shareUnits/1000).toFixed(1)}% ownership.`));$('company-fund').hidden=!company;
  if(company?.sector==='finance'&&managed){const bank=view.finance.providers.find(b=>b.company===company.id);if(bank)action($('company-summary'),'Close new banking business; protect existing principal','CloseBank',{institutionId:bank.id});else action($('company-summary'),'Register bank with protected reserves','RegisterBank',{companyId});}
  m.inventory.filter(b=>b.owner===owner).forEach(b=>{const box=card('inventory-records',b.goods,`${b.quantity} available units · ${b.region} · cost ${cash(b.unitCost)}/unit · expires ${new Date(b.expiresAt).toLocaleDateString()}`);
   if(company&&b.quantity&&b.expiresAt>view.serverTime)ask(box,'Reserve units for a sale',()=>{const quantity=Number(prompt('Units to list',String(b.quantity))),price=Math.round(Number(prompt('Virtual naira price per unit',String(b.unitCost/100)))*100);if(quantity>0&&price>0)send('ListGoods',{companyId,batchId:b.id,quantity,price});},!managed);
   if(company&&b.quantity&&b.expiresAt<=view.serverTime)action(box,'Dispose expired available stock','DisposeExpiredStock',{companyId,batchId:b.id},!managed);
  });
  if(company)m.recipes.filter(r=>r.sector===company.sector).forEach(r=>{const box=card('production-options',r.name,`Consumes ${Object.entries(r.inputs).map(([g,n])=>n+' '+g).join(', ')}. Labour ${cash(r.labour)}. Produces ${r.quantity} ${r.output} after one minute.`);action(box,'Commit inputs and pay labour','StartProduction',{companyId,recipeId:r.id},!managed);});
  m.production.filter(r=>r.company===companyId&&r.status==='running').forEach(r=>action(card('production-records',r.recipe,'Ready '+new Date(r.readyAt).toLocaleTimeString()+'. Refresh to check.'),'Record verified output','FinishProduction',{companyId,productionId:r.id},!managed||view.serverTime<r.readyAt));
  m.listings.forEach(l=>{const box=card('market-records',l.goods+' · '+l.companyName,`${l.region} · ${l.remaining} available units · ${cash(l.price)}/unit. Carrier quotes include fuel and road wear.`);ask(box,'Request quantity and carrier quote',()=>{const quantity=Number(prompt('Quantity to quote','1'));if(quantity>0)send('QuoteOrder',{listingId:l.id,quantity});},!l.remaining);if(l.company===companyId)action(box,'Withdraw unsold listing','CancelListing',{companyId,listingId:l.id},!managed);});
  m.quotes.filter(q=>q.status==='quoted'&&q.expiresAt>view.serverTime).forEach(q=>action(card('quote-records','Purchase quote',`${q.quantity} units · goods ${cash(q.price)} + carrier ${cash(q.shipping)} = ${cash(q.price+q.shipping)}. Expires ${new Date(q.expiresAt).toLocaleTimeString()}. Goods unlock on acceptance; seller settlement is permitted after the 24-hour delivery review window.`),'Accept terms and fund purchase','FundOrder',{quoteId:q.id,acceptedTotal:q.price+q.shipping,acceptTerms:true}));
  m.orders.forEach(o=>{const box=card('order-records',`${o.quantity} ${o.goods} · ${o.status}`,`${o.origin} → ${o.destination} · arrival ${new Date(o.arriveAt).toLocaleTimeString()}. Custody: ${o.custody.map(c=>c.stage).join(' → ')}.`),buyer=o.buyer===cid;
   if(['funded','picked','carrier-assigned','dispatched','in-transit'].includes(o.status))action(box,'Advance verified NPC carrier','AdvanceOrder',{orderId:o.id},view.serverTime<o.lastStageAt+2000||(o.status==='in-transit'&&view.serverTime<o.arriveAt));
   if(buyer&&o.status==='funded')action(box,'Cancel before picking and refund','CancelOrder',{orderId:o.id});
   if(o.status==='delivered'){action(box,buyer?'Accept goods and settle':'Settle after delivery review','AcceptOrder',{orderId:o.id},!buyer&&view.serverTime<o.deliveredAt+86400000);if(buyer)ask(box,'Dispute this delivery',()=>{const reason=prompt('Explain the delivery issue. Funds remain reserved for independent review.');if(reason)send('DisputeOrder',{orderId:o.id,reason});});}
   if(o.status==='damaged')action(box,'Refund recorded expired cargo','RefundDamagedOrder',{orderId:o.id});
   if(buyer&&o.status==='accepted')ask(box,'Review this completed service',()=>{const score=Number(prompt('Rating 1 to 5','5')),text=prompt('Review (500 characters maximum)','');if(score>=1&&score<=5&&text!==null)send('ReviewService',{orderId:o.id,score,text});});
  });
  m.invitations.forEach(i=>action(card('company-invitations','Company role invitation',`${i.role} at ${i.company}. Accepting grants scoped duties and no shares; personal assets stay separate.`),'Accept these role terms','AcceptCompanyRole',{invitationId:i.id,consent:true}));
  const controls=new Set(m.companies.filter(c=>['founder','cofounder','ceo','manager'].includes(c.role)).map(c=>c.id));
  e.vacancies.forEach(v=>{const box=card('vacancy-records',e.roles.find(r=>r.id===v.role)?.name??v.role,`${v.companyName} · ${v.region} · ${v.remaining} positions · ${cash(v.wage)}/shift. ${v.terms}`);action(box,'Apply with relevant credentials','ApplyForJob',{vacancyId:v.id},!v.eligible||v.status!=='open'||!v.remaining||v.deadline<=view.serverTime);if(controls.has(v.company)&&v.status==='open')action(box,'Close uncommitted vacancy','CloseVacancy',{vacancyId:v.id});});
  e.applications.forEach(a=>{const vacancy=e.vacancies.find(v=>v.id===a.vacancy),box=card('application-records',a.name+' · '+a.status,a.reason??'Only relevant game credentials enter the hiring review.'),mine=a.actor===cid,employer=vacancy&&controls.has(vacancy.company);
   if(employer&&a.status==='submitted')for(const reject of [false,true])ask(box,reject?'Reject with reason':'Record relevant review',()=>{const reason=prompt('Relevant hiring reason');if(reason)send('ReviewApplication',{applicationId:a.id,reason,reject});});
   if(employer&&a.status==='reviewed')action(box,'Offer approved interview','OfferInterview',{applicationId:a.id});
   if(mine&&a.status==='interview-offered'){const form=document.createElement('form');e.interview.forEach((q,i)=>{const field=document.createElement('fieldset'),legend=document.createElement('legend');legend.textContent=q.prompt;field.append(legend);q.choices.forEach((text,j)=>{const label=document.createElement('label'),input=document.createElement('input');input.type='radio';input.name='interview'+i;input.value=j;input.required=true;label.append(input,document.createTextNode(text));field.append(label);});form.append(field);});const submit=document.createElement('button');submit.type='submit';submit.textContent='Complete offered interview';submit.disabled=locked;form.append(submit);form.addEventListener('submit',event=>{event.preventDefault();const data=new FormData(form);send('CompleteInterview',{applicationId:a.id,answers:e.interview.map((_,i)=>Number(data.get('interview'+i)))});});box.append(form);}
   if(employer&&a.status==='interview-completed'&&a.interviewPassed)action(box,'Offer secured employment','OfferEmployment',{applicationId:a.id});if(mine&&a.status==='offered')action(box,'Accept displayed employment terms','AcceptEmployment',{applicationId:a.id,acceptTerms:true});if(mine&&!['accepted','withdrawn'].includes(a.status))action(box,'Withdraw application','WithdrawApplication',{applicationId:a.id});
  });
  e.contracts.forEach(c=>{const active=e.shifts.find(s=>s.contract===c.id&&s.status==='active'),box=card('employment-records',e.roles.find(r=>r.id===c.role)?.name??c.role,`${c.status} · ${cash(c.wage)} gross/shift · ${c.remainingShifts} upcoming shifts · reserve ${cash(c.reserve)}.`),mine=c.actor===cid;
   if(mine&&c.status==='active'&&!active)action(box,'Begin secured work','BeginContractWork',{contractId:c.id},!c.remainingShifts);
   if(mine&&active){if(active.task){box.append(paragraph(active.task.label));active.task.choices.forEach((label,index)=>action(box,label,'ContractWorkStep',{contractId:c.id,choice:index},view.serverTime<active.nextStepAt));action(box,'Cancel uncompleted task','CancelContractWork',{contractId:c.id});}else action(box,'Settle earned wage and tax','SettleContractWork',{contractId:c.id},view.serverTime<active.settlementAt);}
   if(c.status==='active')ask(box,'Give one-day notice',()=>{const reason=prompt('Resignation or termination reason');if(reason)send('GiveEmploymentNotice',{contractId:c.id,reason});});if(c.status==='notice')action(box,'Finish employment; preserve started wages','FinishEmployment',{contractId:c.id},view.serverTime<c.noticeAt);
   if(controls.has(c.company)&&c.status==='active')ask(box,'Reserve additional payroll',()=>{const shifts=Number(prompt('Additional secured shifts (1–4)','1'));if(shifts>0)send('ReservePayroll',{contractId:c.id,shifts});});
  });
 }
 function renderFinance(){const f=view.finance;select('bank-provider',f.providers.map(b=>[b.id,b.name]));select('loan-course',[['','Ordinary disclosed loan'],...view.education.courses.map(c=>[c.id,c.name+' · restricted tuition '+cash(c.fee)])]);$('loan-terms').textContent=f.terms;$('loan-capacity').textContent='Additional capacity is checked against verified independent wages. Current total obligation ceiling: '+cash(f.affordabilityCap)+'.';$('savings-records').replaceChildren();$('loan-records').replaceChildren();
  f.savings.forEach(s=>{const box=card('savings-records','Protected savings',`${cash(s.principal)} reserved · ${cash(s.owed)} accrued unpaid interest. ${s.terms}`);action(box,'Collect funded interest','CollectSavingsInterest',{savingsId:s.id},!s.owed);ask(box,'Withdraw your principal',()=>{const amount=Math.round(Number(prompt('Virtual naira to withdraw',String(s.principal/100)))*100);if(amount>0)send('WithdrawSavings',{savingsId:s.id,amount});},!s.principal);});
  f.loans.forEach(l=>{const box=card('loan-records',l.status+' credit',`${cash(l.remaining)} remaining · instalment ${cash(l.instalment)} · next due ${new Date(l.nextDueAt).toLocaleString()} · late fee ${cash(l.lateFee)}.`);if(l.status!=='paid'){ask(box,'Make an agreed repayment',()=>{const amount=Math.round(Number(prompt('Virtual naira repayment',String(Math.min(l.remaining,l.instalment)/100)))*100);if(amount>0)send('RepayLoan',{loanId:l.id,amount});});action(box,'Review capped late charges','ReviewLoan',{loanId:l.id});if(!l.hardshipUsed)action(box,'Request the 14-day hardship extension','RequestLoanHardship',{loanId:l.id});}if(l.educationAward&&view.education.scholarships.some(a=>a.id===l.educationAward&&a.status==='offered'))action(box,'Cancel unused tuition credit and restore funding','CancelEducationLoan',{loanId:l.id});});
 }
 $('company-select').addEventListener('change',()=>{if(view)render(view,send,locked);});
 $('company-form').addEventListener('submit',event=>{event.preventDefault();send('RegisterCompany',{name:$('company-name').value,sector:$('company-sector').value,capital:Math.round(Number($('company-capital').value)*100)});});
 $('company-fund').addEventListener('submit',event=>{event.preventDefault();send('FundCompany',{companyId:$('company-select').value,amount:Math.round(Number($('company-gift').value)*100),acceptGift:true});});
 $('supply-form').addEventListener('submit',event=>{event.preventDefault();const g=view.commerce.goods.find(g=>g.id===$('supply-goods').value),companyId=$('company-select').value;send('BuyNPCSupply',{goodsId:g.id,quantity:Number($('supply-quantity').value),acceptedUnitPrice:g.price,...(companyId?{companyId}:{})});});
 $('vacancy-form').addEventListener('submit',event=>{event.preventDefault();send('PostVacancy',{companyId:$('company-select').value,roleId:$('vacancy-role').value,wage:Math.round(Number($('vacancy-wage').value)*100),slots:Number($('vacancy-slots').value),reserveShifts:Number($('vacancy-shifts').value),deadline:view.serverTime+7*86400000,acceptTerms:true});});
 $('savings-form').addEventListener('submit',event=>{event.preventDefault();const b=view.finance.providers.find(b=>b.id===$('bank-provider').value);send('DepositSavings',{providerId:b.id,amount:Math.round(Number($('savings-deposit').value)*100),acceptedRateBps:b.rateBps,acceptTerms:true});});
 $('loan-form').addEventListener('submit',event=>{event.preventDefault();const courseId=$('loan-course').value;send('RequestLoan',{providerId:$('bank-provider').value,principal:Math.round(Number($('loan-principal').value)*100),acceptedInterestBps:500,acceptTerms:true,...(courseId?{courseId}:{})});});
 $('transfer-form').addEventListener('submit',event=>{event.preventDefault();const citizenId=$('transfer-citizen').value.trim(),amount=Math.round(Number($('transfer-amount').value)*100);if(confirm(`Send ${cash(amount)} to citizen ${citizenId}? Verify their complete ID before confirming.`))send('TransferMoney',{citizenId,confirmRecipient:citizenId,amount});});
 return{render};
})();
