'use strict';
window.FurnishingUI=(()=>{
 let editing=null;
 const $=id=>document.getElementById(id),money=n=>new Intl.NumberFormat('en-NG',{style:'currency',currency:'NGN'}).format(n/100);
 const el=(tag,text)=>{const n=document.createElement(tag);if(text)n.textContent=text;return n;};
 function render(view,send,busy){const m=view.furnishing;$('furnishing-panel').hidden=!m;if(!m)return;const root=$('furnishing-records');root.replaceChildren();const inside=view.world?.position.interior==='shelter'&&view.world.home?.id===m.home.id;
  if(editing&&(!inside||editing.homeId!==m.home.id||editing.homeVersion!==m.home.version)){editing=null;window.dispatchEvent(new CustomEvent('furniture-edit',{detail:null}));}
  const draft=editing?{id:editing.itemId,x:editing.x.value,y:editing.y.value,rotation:editing.rotation.value,finish:editing.finish.value}:null;
  const button=(box,text,type,payload,disabled=false)=>{const b=el('button',text);b.type='button';b.disabled=busy||disabled;b.onclick=()=>send(type,payload);box.append(b);};
  const select=(values,value)=>{const s=el('select');for(const v of values){const o=el('option',String(v));o.value=String(v);o.selected=v===value;s.append(o);}return s;};
  const field=(form,label,input)=>{const l=el('label',label);l.append(input);form.append(l);return input;};
  root.append(el('p',`${view.world.residence.address} · ${m.home.width} × ${m.home.height} home · ${m.home.parkingSpaces} parking space${m.home.parkingSpaces===1?'':'s'}. Enter your home to arrange furnishings.`));
  const catalogue=el('details');catalogue.append(el('summary','Furniture shop'));for(const f of m.catalogue){const a=el('article');a.className='course-record';a.append(el('h3',f.name),el('p',`${f.category} · ${f.w} × ${f.h} floor tiles · ${money(f.price)}`));const finish=field(a,'Finish',select(m.finishes,'oak'));const buy=el('button','Review purchase');buy.type='button';buy.disabled=busy;buy.onclick=()=>{if(confirm(`Buy ${f.name} in ${finish.value} for ${money(f.price)}? It will go into your furniture storage.`))send('BuyFurniture',{modelId:f.id,acceptedPrice:f.price,finish:finish.value,acceptTerms:true});};a.append(buy);catalogue.append(a);}root.append(catalogue);
  const decorate=el('form');decorate.append(el('h3','Walls and flooring'));const wall=field(decorate,'Wall finish',select(m.finishes,m.home.wall)),floor=field(decorate,'Floor finish',select(m.finishes,m.home.floor)),save=el('button','Save room finishes');save.disabled=busy||!inside;decorate.append(save);decorate.onsubmit=e=>{e.preventDefault();send('CustomiseHome',{homeVersion:m.home.version,wall:wall.value,floor:floor.value});};root.append(decorate);
  const architecture=el('details');architecture.id='home-architecture';architecture.append(el('summary','Rooms, walls and doorways'),el('p',`Room plan: ${m.rooms.length} area${m.rooms.length===1?'':'s'}. ${m.construction.materials} available building-material units. Structural changes require ownership; finishes remain available to residents.`));
  for(const r of m.rooms){const form=el('form');form.append(el('h3',r.name),el('p',`${r.area} floor tiles`));const name=field(form,'Room name',el('input'));name.value=r.name;name.maxLength=40;name.required=true;const finish=field(form,'Room floor finish',select(m.finishes,r.floor)),save=el('button','Save this room');save.disabled=busy||!inside;form.append(save);form.onsubmit=e=>{e.preventDefault();send('CustomiseRoom',{roomId:r.id,name:name.value,floor:finish.value,homeVersion:m.home.version});};architecture.append(form);}
  const build=el('form');build.id='partition-build';build.append(el('h3','Build an interior wall line'));
  const number=(label,value,min,max)=>{const input=el('input');input.type='number';input.step='1';input.min=min;input.max=max;input.required=true;input.value=value;return field(build,label,input);};
  const axis=field(build,'Direction',select(['h','v'],'h'));axis.options[0].textContent='Horizontal';axis.options[1].textContent='Vertical';const bx=number('Start X',0,0,m.home.width-1),by=number('Start Y',3,0,m.home.height-1),length=number('Length in tile edges',m.home.width,1,20),door=number('Doorway offset (-1 for none)',4,-1,19),quote=el('p');quote.setAttribute('aria-live','polite');build.append(quote);
  const review=()=>{const n=Number(length.value),hasDoor=Number(door.value)>=0,materials=Math.ceil(n/m.construction.segmentsPerMaterial),labour=n*m.construction.labourPerSegment+(hasDoor?m.construction.doorSurcharge:0);quote.textContent=`${money(labour)} labour + ${materials} owned material units. Construction inputs are consumed without a resale or removal refund. Doorways must remain clear.`;return{labour,materials};};build.addEventListener('input',review);review();
  const buy=el('button','Buy the required materials');buy.type='button';buy.disabled=busy||!inside||!m.construction.canBuild;buy.onclick=()=>{const {materials}=review(),unit=view.commerce.goods.find(g=>g.id==='materials')?.price;if(unit&&confirm(`Buy ${materials} material units for ${money(materials*unit)} into personal inventory?`))send('BuyNPCSupply',{goodsId:'materials',quantity:materials,acceptedUnitPrice:unit});};build.append(buy);
  const submit=el('button','Review and build wall line');submit.disabled=busy||!inside||!m.construction.canBuild;build.append(submit);build.onsubmit=e=>{e.preventDefault();const {labour,materials}=review();if(confirm(`Build this wall line for ${money(labour)} and consume ${materials} material units? Removing it gives no refund.`))send('BuildHomePartition',{axis:axis.value,x:Number(bx.value),y:Number(by.value),length:Number(length.value),doorAt:Number(door.value)<0?null:Number(door.value),acceptedLabour:labour,acceptedMaterials:materials,acceptTerms:true,homeVersion:m.home.version});};architecture.append(build);
  for(const p of m.home.partitions??[]){const line=el('p',`${p.door?'Doorway':'Wall'} ${p.id}`),remove=el('button','Remove '+p.id);remove.type='button';remove.disabled=busy||!inside||!m.construction.canBuild;remove.onclick=()=>{if(confirm('Remove this segment without a labour or material refund?'))send('RemoveHomePartition',{partitionIds:[p.id],acceptDiscard:true,homeVersion:m.home.version});};line.append(remove);architecture.append(line);}root.append(architecture);
  for(const item of m.items){const f=m.catalogue.find(f=>f.id===item.model),form=el('form');form.className='course-record';form.append(el('h3',f.name),el('p',item.placement?`Placed at ${item.placement.x}, ${item.placement.y} · ${item.finish}`:'In your personal furniture storage'));
   const number=(value,max)=>{const n=el('input');n.type='number';n.min='0';n.max=String(max);n.step='1';n.value=String(value);n.required=true;return n;};const x=field(form,'Floor column',number(item.placement?.x??0,m.home.width-1)),y=field(form,'Floor row',number(item.placement?.y??0,m.home.height-1)),rotation=field(form,'Rotation',select([0,90,180,270],item.placement?.rotation??0)),finish=field(form,'Finish',select(m.finishes,item.finish)),place=el('button',item.placement?'Save new position':'Place in this home');place.disabled=busy||!inside;form.append(place);const choose=el('button','Choose position on the floor'),cancel=el('button','Cancel floor selection'),hint=el('p');choose.type=cancel.type='button';choose.disabled=busy||!inside;cancel.hidden=true;hint.className='hint';hint.setAttribute('role','status');form.append(choose,cancel,hint);
   const selectItem=()=>{editing={itemId:item.id,homeId:m.home.id,homeVersion:m.home.version,model:f,x,y,rotation,finish,hint,form,cancel};form.classList.add('furniture-selected');cancel.hidden=false;hint.textContent='Click a clear tile in your room, then save this position.';syncScene();};choose.onclick=()=>{if(editing){editing.form.classList.remove('furniture-selected');editing.cancel.hidden=true;editing.hint.textContent='';}selectItem();};cancel.onclick=()=>{editing=null;form.classList.remove('furniture-selected');cancel.hidden=true;hint.textContent='Floor selection cancelled.';syncScene();};
   for(const input of [x,y,rotation,finish])input.addEventListener('change',()=>{if(editing?.itemId===item.id)syncScene();});
   if(draft?.id===item.id){x.value=draft.x;y.value=draft.y;rotation.value=draft.rotation;finish.value=draft.finish;selectItem();}
   form.onsubmit=e=>{e.preventDefault();send('PlaceFurniture',{furnitureId:item.id,x:Number(x.value),y:Number(y.value),rotation:Number(rotation.value),finish:finish.value,homeVersion:m.home.version});};if(item.placement)button(form,'Put into storage','StoreFurniture',{furnitureId:item.id,homeVersion:m.home.version},!inside||item.starter&&['bed','pantry'].includes(item.model));root.append(form);
  }
  const entranceDoor=view.world.residence.door,atEntrance=!view.world.position.interior&&Math.abs(view.world.position.x-entranceDoor.x)+Math.abs(view.world.position.y-entranceDoor.y)<=1;const garage=el('article');garage.append(el('h3','Home parking'),el('p',atEntrance?'You are at the parking entrance.':'Walk outside to your home entrance to park or retrieve vehicles.'));for(let slot=1;slot<=m.home.parkingSpaces;slot++){const record=m.parking.find(p=>p.homeId===m.home.id&&p.slot===slot&&p.status==='parked');garage.append(el('p',`Space ${slot}: ${record?'occupied':'available'}`));if(record)button(garage,'Retrieve vehicle','UnparkVehicle',{vehicleId:record.vehicleId},!atEntrance);else for(const v of view.mobility?.vehicles.filter(v=>v.owner===view.citizen.id&&v.region===view.world.position.region&&v.status==='parked')??[])button(garage,`Park ${v.model} in space ${slot}`,'ParkVehicle',{vehicleId:v.id,slot},!atEntrance);}
  for(const record of m.parking.filter(p=>p.status==='parked'&&p.homeId!==m.home.id))button(garage,'Retrieve vehicle from previous residence','UnparkVehicle',{vehicleId:record.vehicleId});root.append(garage);
 }
 function syncScene(){window.dispatchEvent(new CustomEvent('furniture-edit',{detail:editing?{itemId:editing.itemId,homeId:editing.homeId,homeVersion:editing.homeVersion,w:editing.model.w,h:editing.model.h,rotation:Number(editing.rotation.value),finish:editing.finish.value,x:Number(editing.x.value),y:Number(editing.y.value)}:null}));}
 window.addEventListener('furniture-floor-select',event=>{const d=event.detail;if(!editing||d.itemId!==editing.itemId||d.homeId!==editing.homeId||d.homeVersion!==editing.homeVersion)return;editing.x.value=d.x;editing.y.value=d.y;editing.hint.textContent=d.valid?`Selected tile (${d.x}, ${d.y}). Save to check and record this layout.`:'This footprint is blocked or outside the room. Choose a different tile.';});
 return{render,syncScene};
})();
