'use strict';
window.InsuranceUI=(()=>{
 const $=id=>document.getElementById(id),money=n=>new Intl.NumberFormat('en-NG',{style:'currency',currency:'NGN'}).format(n/100);
 let view,send,locked;
 function card(title,text){const box=document.createElement('article');box.className='course-record';const h=document.createElement('h3'),p=document.createElement('p');h.textContent=title;p.textContent=text;box.append(h,p);$('insurance-records').append(box);return box;}
 function action(box,label,type,payload,disabled=false){const b=document.createElement('button');b.type='button';b.textContent=label;b.disabled=locked||disabled;b.addEventListener('click',()=>send(type,payload));box.append(b);}
 function select(parent,label,options,id){const l=document.createElement('label'),s=document.createElement('select');s.id=id;l.htmlFor=id;l.textContent=label;options.forEach(([value,text])=>{const o=document.createElement('option');o.value=value;o.textContent=text;s.append(o);});parent.append(l,s);return s;}
 function render(next,dispatch,busy){view=next;send=dispatch;locked=busy;const m=view.insurance;$('insurance-panel').hidden=!view.citizen;if(!view.citizen)return;$('insurance-records').replaceChildren();const rules=m.rules,cid=view.citizen.id;
  view.incidents.records.forEach(i=>card('Recorded '+i.kind,`Exposure ${new Date(i.at).toLocaleString()} · recorded asset loss ${money(i.loss)} · game health ${i.healthBefore} → ${i.healthAfter}. ${i.invoice?'Paid repair evidence '+money(i.invoice.amount)+'.':'Complete a real repair before submitting an asset claim.'}`));
  const purchase=card('Funded game coverage',`Premium ${money(rules.premium)} · maximum cover ${money(rules.limit)} · excess ${money(rules.excess)} · 30 days with a one-day waiting period. Covers verified paid incident repairs or nonroutine clinical care. Preexisting exposures and routine care are excluded. File within seven days; denied claims have one independent appeal within seven days. Premium is refundable during the first day before any claim.`),form=document.createElement('form'),provider=select(form,'Insurance provider',m.providers.filter(p=>p.active).map(p=>[p.id,p.name]),'insurance-provider'),coverage=select(form,'Coverage and owned asset',[['health','Own game-health episodes'],...view.mobility.vehicles.filter(v=>v.owner===cid).map(v=>['vehicle:'+v.id,v.model+' · '+v.region]),...view.property.assets.filter(a=>a.owner===cid).map(a=>['property:'+a.id,a.kind+' · '+a.region])],'insurance-coverage'),submit=document.createElement('button');submit.type='submit';submit.textContent='Accept disclosed coverage and reserve backing';submit.disabled=locked;form.append(submit);form.addEventListener('submit',event=>{event.preventDefault();const split=coverage.value.indexOf(':'),kind=split<0?coverage.value:coverage.value.slice(0,split),assetId=split<0?undefined:coverage.value.slice(split+1);send('BuyInsurance',{providerId:provider.value,coverage:kind,...(assetId?{assetId}:{}),acceptedPremium:rules.premium,acceptedLimit:rules.limit,acceptedExcess:rules.excess,acceptTerms:true});});purchase.append(form);
  const governs=view.commerce.companies.filter(c=>['founder','cofounder','ceo'].includes(c.role));governs.filter(c=>c.sector==='finance').forEach(c=>{const existing=m.providers.find(p=>p.company===c.id),box=card(c.name,'Insurance operations need current qualified staff and funded capital. Policy and approved-claim reserves stay protected after sales close.');if(existing?.active)action(box,'Close new sales; retain obligations','CloseInsurer',{insurerId:existing.id});else if(!existing)action(box,'Register qualified insurer','RegisterInsurer',{companyId:c.id});});
  m.policies.forEach(p=>{const mine=p.actor===cid,box=card(p.coverage+' policy · '+p.status,`${money(p.remaining)} unused backed coverage · expires ${new Date(p.expiresAt).toLocaleDateString()} · ${p.premiumEarned?'premium earned':'premium reserved'}.`);if(p.status!=='active')return;if(!p.premiumEarned)action(box,'Release premium after the disclosed first day','EarnPolicyPremium',{policyId:p.id},view.serverTime<p.startsAt+rules.waiting);if(mine&&!p.premiumEarned&&view.serverTime<p.startsAt+rules.waiting)action(box,'Cancel unused coverage and refund premium','CancelInsurance',{policyId:p.id},m.claims.some(c=>c.policy===p.id));action(box,'Resolve expired unused backing','CloseExpiredPolicy',{policyId:p.id},view.serverTime<p.expiresAt+rules.filing);
   if(mine){const refs=m.references.filter(r=>r.kind===p.coverage&&(!p.asset||r.asset===p.asset));if(refs.length){const f=document.createElement('form'),ref=select(f,'Official paid expense',refs.map(r=>[r.id,r.name]),'insurance-reference-'+p.id),b=document.createElement('button');b.type='submit';b.textContent='Consent to scoped evidence and submit claim';b.disabled=locked;f.append(b);f.addEventListener('submit',event=>{event.preventDefault();send('SubmitClaim',{policyId:p.id,referenceId:ref.value,consent:true});});box.append(f);}}
  });
  m.claims.forEach(c=>{const mine=c.actor===cid,box=card('Claim · '+c.status,`${c.findings??'Awaiting official evidence review.'} ${c.payout?'Verified amount '+money(c.payout)+'.':''}`);if(c.status==='submitted'&&c.canReview)action(box,'Request official episode or invoice evidence','RequestClaimEvidence',{claimId:c.id});if(c.status==='evidence-requested'&&mine)action(box,'Consent to linked official evidence','SupplyClaimEvidence',{claimId:c.id,consent:true});if(['submitted','evidence-requested','appealed'].includes(c.status)){action(box,'Request independent NPC investigation','NPCInvestigateClaim',{claimId:c.id});if(c.canReview&&c.status!=='appealed')action(box,'Perform qualified evidence investigation','InvestigateClaim',{claimId:c.id});}if(c.status==='investigated'&&c.investigator!=='npc')action(box,'Request independent NPC continuation','NPCInvestigateClaim',{claimId:c.id});if(c.status==='investigated'&&(c.investigator==='npc'||c.canReview))action(box,'Record the official factual decision','DecideClaim',{claimId:c.id,choice:0});if(c.status==='approved')action(box,'Pay the reserved reimbursement','PayClaim',{claimId:c.id});if(mine&&c.status==='denied'&&!c.appealUsed)action(box,'Open the independent appeal','AppealClaim',{claimId:c.id},view.serverTime>c.decidedAt+rules.appealWindow);});
 }
 return{render};
})();
