'use strict';
window.MobilityUI=(()=>{
 const $=id=>document.getElementById(id),money=n=>new Intl.NumberFormat('en-NG',{style:'currency',currency:'NGN'}).format(n/100);
 let view,send,locked;
 function card(title,text){const box=document.createElement('article');box.className='course-record';const h=document.createElement('h3'),p=document.createElement('p');h.textContent=title;p.textContent=text;box.append(h,p);$('mobility-records').append(box);return box;}
 function action(box,label,type,payload,disabled=false){const b=document.createElement('button');b.type='button';b.textContent=label;b.disabled=locked||disabled;b.addEventListener('click',()=>send(type,payload));box.append(b);}
 function ask(box,label,callback){const b=document.createElement('button');b.type='button';b.textContent=label;b.disabled=locked;b.addEventListener('click',callback);box.append(b);}
 function render(next,dispatch,busy){view=next;send=dispatch;locked=busy;const m=view.mobility;$('mobility-panel').hidden=!m;if(!m)return;$('mobility-records').replaceChildren();const cid=view.citizen.id;
  m.models.forEach(model=>action(card(model.name,`${money(model.price)} · tank ${model.tank} litres · purchased at your current location with an empty tank.`),'Accept vehicle purchase terms','BuyNPCVehicle',{modelId:model.id,acceptedPrice:model.price,acceptTerms:true}));
  m.vehicles.forEach(v=>{const own=v.owner===cid,box=card(m.models.find(x=>x.id===v.model).name,`${v.region} · ${v.status} · condition ${v.condition}/100 · fuel ${v.fuel}/${v.tank} litres. ${m.licensed?'Driving licence current.':'Complete the driving course, practice and licence before driving.'}`),available=v.status==='parked'&&v.region===view.world.position.region;
   if(available){ask(box,'Transfer stored fuel to this tank',()=>{const litres=Number(prompt('Litres from your available local fuel stock','5'));if(litres>0)send('RefuelVehicle',{vehicleId:v.id,litres});});if(v.fuel&&v.fuelExpiresAt<=view.serverTime)action(box,'Dispose expired tank fuel','DisposeVehicleFuel',{vehicleId:v.id});action(box,'Commit 1 material and repair labour '+money(v.repairFee),'RequestVehicleRepair',{vehicleId:v.id,acceptedFee:v.repairFee});
    const form=document.createElement('form'),label=document.createElement('label'),select=document.createElement('select'),terms=document.createElement('p'),submit=document.createElement('button');select.id='vehicle-route-'+v.id;label.htmlFor=select.id;label.textContent='Vehicle destination';v.routes.forEach(r=>{const o=document.createElement('option');o.value=r.destination;o.textContent=r.destination;select.append(o);});const route=()=>v.routes.find(r=>r.destination===select.value);const explain=()=>{const q=route();terms.textContent=`${q.fuel} litres reserved + ${money(q.toll)} toll · ${Math.ceil(q.duration/1000)} seconds · ${q.wear} condition points. Cancelling in the first five seconds returns toll and fuel.`;submit.disabled=locked||!m.licensed||v.fuel<q.fuel||v.fuelExpiresAt<=view.serverTime||v.condition<40;};select.addEventListener('change',explain);submit.type='submit';submit.textContent='Accept quoted route and drive';form.append(label,select,terms,submit);form.addEventListener('submit',event=>{event.preventDefault();const q=route();send('BeginVehicleTravel',{vehicleId:v.id,destination:q.destination,acceptedFuel:q.fuel,acceptedToll:q.toll,acceptTerms:true});});explain();box.append(form);
   }
   if(own){ask(box,'Invite a licensed driver',()=>{const citizenId=prompt('Exact citizen ID');if(citizenId)send('InviteVehicleDriver',{vehicleId:v.id,citizenId});});v.permitted.filter(id=>id!==cid).forEach(id=>action(box,'Revoke future driving for '+id,'RevokeVehicleDriver',{vehicleId:v.id,citizenId:id}));if(available)ask(box,'Offer vehicle title for sale',()=>{const price=Math.round(Number(prompt('Price in virtual naira'))*100);if(price>0)send('OfferVehicleSale',{vehicleId:v.id,price});});}
  });
  m.invitations.forEach(i=>{const box=card('Driver invitation','Consent gives driving permission; title and your personal funds remain separate.');action(box,'Accept driving duties','AcceptVehicleDriver',{invitationId:i.id,consent:true},!m.licensed);action(box,'Decline invitation','DeclineVehicleDriver',{invitationId:i.id});});
  m.sales.filter(s=>['open','reserved'].includes(s.status)).forEach(s=>{const v=s.vehicle,box=card('Vehicle title offer',`${v.region} · condition ${v.condition}/100 · fuel ${v.fuel} litres · ${money(s.price)} · ${s.status}.`);if(s.status==='open'&&s.seller!==cid)action(box,'Accept disclosed title and reserve price','ReserveVehicleSale',{saleId:s.id,acceptedPrice:s.price,acceptTerms:true});if(s.status==='reserved'&&s.buyer===cid)action(box,'Complete vehicle title transfer','CompleteVehicleSale',{saleId:s.id});if(s.buyer===cid||s.seller===cid)action(box,'Cancel eligible sale and refund','CancelVehicleSale',{saleId:s.id},s.status==='reserved'&&s.seller===cid&&view.serverTime<s.expiresAt);});
  m.repairs.filter(r=>r.status==='reserved').forEach(r=>{const box=card('Vehicle repair','Funded labour '+money(r.fee)+' · ready '+new Date(r.readyAt).toLocaleTimeString()+'.');action(box,'Verify completed repair and pay provider','CompleteVehicleRepair',{repairId:r.id},view.serverTime<r.readyAt);action(box,'Cancel unearned labour','CancelVehicleRepair',{repairId:r.id},view.serverTime>=r.readyAt);});
 }
 return{render};
})();
