'use strict';
window.PropertyUI=(()=>{
 const $=id=>document.getElementById(id),money=n=>new Intl.NumberFormat('en-NG',{style:'currency',currency:'NGN'}).format(n/100);
 let view,send,locked;
 const paragraph=text=>{const p=document.createElement('p');p.textContent=text;return p;};
 function card(title,text){const box=document.createElement('article');box.className='course-record';const h=document.createElement('h3');h.textContent=title;box.append(h,paragraph(text));$('property-records').append(box);return box;}
 function action(box,label,type,payload,disabled=false){const b=document.createElement('button');b.type='button';b.textContent=label;b.disabled=locked||disabled;b.addEventListener('click',()=>send(type,payload));box.append(b);}
 function ask(box,label,callback){const b=document.createElement('button');b.type='button';b.textContent=label;b.disabled=locked;b.addEventListener('click',callback);box.append(b);}
 function render(next,dispatch,busy){view=next;send=dispatch;locked=busy;const m=view.property;$('property-panel').hidden=!m;if(!m)return;$('property-records').replaceChildren();const actor=view.citizen.id;const outside=!view.world.position.interior&&!view.world.trip;const shelter=card('Choose your residence','Moving stores your furnishings and releases parking. Existing rent, tax and utility obligations continue.');action(shelter,'Accept moving terms and use starter accommodation','SetResidence',{propertyId:null,acceptTerms:true},!outside||view.citizen.housing==='Starter accommodation');
  m.catalogue.forEach(a=>action(card(a.kind+' · '+a.region,`One NPC unit. Price ${money(a.price)} + transfer tax ${money(a.tax)}. Reservation refunds if not completed within one minute.`),'Accept price and reserve title','ReservePropertyPurchase',{propertyId:a.id,acceptedTotal:a.price+a.tax,acceptTerms:true}));
  m.sales.filter(s=>s.status==='open').forEach(s=>{const a=s.asset,box=card(a.kind+' for sale',`${a.region} · ${money(s.price)}. Property liabilities: tax ${money(a.taxDue)}, utilities ${money(a.utilities.bill)}.${s.tenancy?' Existing tenancy continues; weekly rent '+money(s.tenancy.rent)+' and reserved deposit '+money(s.tenancy.deposit)+'.':''}`);if(s.seller===actor)action(box,'Withdraw unreserved sale','WithdrawPropertySale',{saleId:s.id});else action(box,'Accept disclosed commitments and reserve','ReservePropertyPurchase',{saleId:s.id,acceptedTotal:s.price+Math.ceil(s.price*.025),acceptTerms:true});});
  m.purchases.filter(p=>p.status==='reserved').forEach(p=>{const box=card('Reserved purchase',`${money(p.price+p.tax)} reserved. Expires ${new Date(p.expiresAt).toLocaleTimeString()}.`);action(box,'Complete title transfer','CompletePropertyPurchase',{purchaseId:p.id});action(box,'Cancel and refund reservation','CancelPropertyPurchase',{purchaseId:p.id});});
  m.assets.forEach(a=>{const own=a.owner===actor,box=card(a.kind+' · '+a.region,`Condition ${a.quality}/100 · fire safety ${a.fireSafety}/100. Tax ${money(a.taxDue)} · utility bill ${money(a.utilities.bill)}.`);if(a.canReside)action(box,'Accept moving terms and live here','SetResidence',{propertyId:a.id,propertyVersion:a.version,acceptTerms:true},!outside||view.citizen.housing===a.id);action(box,'Request measured safety inspection','InspectProperty',{propertyId:a.id});
   if(own){ask(box,'Offer title for sale',()=>{const price=Math.round(Number(prompt('Sale price in virtual naira'))*100);if(price>0)send('ListProperty',{propertyId:a.id,price});});if(a.kind==='home')ask(box,'Publish weekly tenancy terms',()=>{const rent=Math.round(Number(prompt('Weekly rent in virtual naira','100'))*100),deposit=Math.round(Number(prompt('Refundable deposit in virtual naira (at most two weeks)','200'))*100);if(rent>0&&deposit>0)send('OfferTenancy',{propertyId:a.id,rent,deposit});});if(a.kind==='land'&&a.status==='ready')action(box,'Commit 5 materials, 2 power and ₦500 labour','StartConstruction',{propertyId:a.id,acceptedLabour:50000});action(box,'Repair with 2 materials and ₦100 service','RepairProperty',{propertyId:a.id,acceptedFee:10000});if(a.taxDue)action(box,'Accept and pay published tax '+money(a.taxDue),'PayPropertyTax',{propertyId:a.id,acceptedAmount:a.taxDue});if(!a.utilities.connected)action(box,'Connect services for ₦50','ConnectUtilities',{propertyId:a.id,acceptedFee:5000});}
   if(a.kind==='home'&&a.utilities.connected)action(box,'Consume 2 power and 4 water; accept ₦8 bill','UseHomeUtilities',{propertyId:a.id,acceptedBill:800},view.serverTime<a.utilities.lastUseAt+86400000);if(a.utilities.bill)action(box,'Accept and pay utility bill','PayUtilityBill',{propertyId:a.id,acceptedAmount:a.utilities.bill});
  });
  m.rentals.filter(r=>r.status==='open'&&r.owner!==actor).forEach(r=>action(card('Home tenancy · '+r.region,`${money(r.rent)}/week · refundable deposit ${money(r.deposit)}. Arrears cap: two weeks. Notice and independent review precede eviction; starter shelter remains available.`),'Accept displayed lease and deposit terms','AcceptTenancy',{rentalId:r.id,acceptedRent:r.rent,acceptedDeposit:r.deposit,acceptTerms:true}));
  m.tenancies.forEach(t=>{const mine=t.tenant===actor,box=card('Tenancy · '+t.status,`${money(t.rent)}/week · ${money(t.deposit)} protected deposit · capped arrears ${money(t.arrears)}. Notice review: ${t.review}. ${t.reviewReason??''}`);if(mine&&t.arrears)action(box,'Accept and pay exact arrears','PayRent',{tenancyId:t.id,acceptedAmount:t.arrears});if(t.status==='ended')return;if(mine)action(box,'Leave and recover protected deposit','LeaveTenancy',{tenancyId:t.id});else if(t.status==='active'){action(box,'Give seven-day notice for evidenced arrears','GiveTenancyNotice',{tenancyId:t.id,reason:'arrears'},!t.arrears);action(box,'Give seven-day owner-use notice','GiveTenancyNotice',{tenancyId:t.id,reason:'owner-use'});}if(['requested','appealed'].includes(t.review))action(box,'Request independent factual review','ReviewTenancyNotice',{tenancyId:t.id});if(t.review==='approved'){if(mine)action(box,'Appeal and extend notice protection','AppealTenancyNotice',{tenancyId:t.id});else action(box,'Enforce reviewed notice with shelter fallback','EnforceTenancyNotice',{tenancyId:t.id},view.serverTime<t.noticeAt);}});
  m.builds.filter(b=>b.status==='building').forEach(b=>action(card('Construction in progress','Completion '+new Date(b.readyAt).toLocaleTimeString()),'Verify completion and settle labour','FinishConstruction',{buildId:b.id},view.serverTime<b.readyAt));
  m.inspections.forEach(i=>card('Inspection · '+i.status,`${i.findings.join('; ')||'No repair findings'}. Compliance window ends ${new Date(i.complianceAt).toLocaleDateString()}.`));
 }
 return{render};
})();
