window.TeachingUI=(()=>{
 const $=id=>document.getElementById(id);
 function render(view,send,locked){const ed=view.education;if(!ed){$('teaching-panel').hidden=true;return;}$('teaching-panel').hidden=false;const cid=view.citizen.id,provider=$('school-provider'),old=provider.value;provider.replaceChildren();const option=(value,text)=>{const o=document.createElement('option');o.value=value;o.textContent=text;provider.append(o);};option('','Official NPC teaching');ed.schools.filter(s=>s.status==='open').forEach(s=>option(s.id,`${s.name} · ${s.region} · ${s.available} places`));if([...provider.options].some(o=>o.value===old))provider.value=old;
  const root=$('teaching-records');root.replaceChildren();const box=text=>{const el=document.createElement('article');el.className='course-record';const p=document.createElement('p');p.textContent=text;el.append(p);root.append(el);return el;};const action=(parent,label,type,payload,disabled=false)=>{const b=document.createElement('button');b.type='button';b.textContent=label;b.disabled=locked||disabled;b.addEventListener('click',()=>send(type,payload));parent.append(b);};
  view.commerce.companies.filter(c=>c.sector==='education'&&['founder','cofounder','ceo'].includes(c.role)).forEach(c=>{const school=ed.schools.find(s=>s.company===c.id),el=box(c.name+' · approved teaching');if(school){el.append(document.createTextNode(`${school.courses.join(', ')} · ${school.status}`));if(school.status==='open')action(el,'Close new enrolments; preserve existing learning','CloseSchool',{schoolId:school.id});}else{const eligible=ed.courses.filter(c=>!c.licence||ed.licences.some(l=>l.track===c.track&&l.current)).map(c=>c.id);action(el,'Open listed official courses: '+eligible.join(', '),'OpenSchool',{companyId:c.id,courseIds:eligible},!view.citizen.certificate);}});
  ed.enrolments.filter(e=>!['completed','cancelled'].includes(e.status)).forEach(en=>{const el=box(en.courseName+' · voluntary mentoring');const b=document.createElement('button');b.type='button';b.textContent='Invite a qualified citizen';b.disabled=locked;b.addEventListener('click',()=>{const citizenId=prompt('Qualified mentor citizen ID. Only this course’s practice progress is shared.');if(citizenId)send('InviteMentor',{enrolmentId:en.id,citizenId});});el.append(b);});
  ed.mentorships.forEach(m=>{const el=box(`${m.course} · ${m.status} · shared practice progress ${m.progress??'closed'}/required sessions.`);if(m.mentor===cid&&m.status==='invited'){action(el,'Accept scoped mentoring terms','AcceptMentorship',{mentorshipId:m.id,consent:true});action(el,'Decline invitation','DeclineMentorship',{mentorshipId:m.id});}if(m.mentor===cid&&m.status==='accepted')action(el,'Record approved supervised procedure for student confirmation','OfferMentoredPractice',{mentorshipId:m.id,choice:0},m.statusOfCourse!=='exam-passed');if(!['ended','declined'].includes(m.status))action(el,'End mentoring and retain NPC support','LeaveMentorship',{mentorshipId:m.id});});
  ed.practiceSessions.filter(s=>s.student===cid&&s.status==='offered').forEach(s=>action(box('Your mentor offered a verified practice session. Confirm your participation; examinations and licence checks still apply.'),'Confirm this practice session','SupervisedPractice',{enrolmentId:s.enrolment,practiceSessionId:s.id,choice:0}));
 }
 return{render};
})();
